### ISSUE TITLE
Add a logo to the GCP app

### ISSUE THREAD

**Issue by matheuss** [zeit/now#10]
We need a 120px wide (😫) black on white logo to be shown when we ask the user to give us access to their GCP.

Let's use ZEIT's triangle, @rauchg @evilrabbit?

**Comment by aerickson** [comment]
https://zeit.co/logos has SVG's that can be scaled to any size.

**Comment by matheuss** [comment]
@Qix- they don't but I think it'll appear on a blue background.

@evilrabbit can you send me a png over please? 🙏 I think it's better to use Now's triangle 👍

**Comment by evilrabbit** [comment]
There we go!

![now-120x120 1x](https://user-images.githubusercontent.com/6880091/28213738-c69b9a02-687d-11e7-8f54-aef810f3151a.png)
![now-120x120 2x](https://user-images.githubusercontent.com/6880091/28213739-c6a470d2-687d-11e7-8b48-f63b5636c7b9.png)

**Comment by matheuss** [comment]
Added it, and... I thought they were going to show the logo here 🙄
![image](https://user-images.githubusercontent.com/4721750/28249558-7b9cfaca-6a2e-11e7-8280-fc42f3848f0d.png)

Thanks anyways @evilrabbit 🙌
