### ISSUE TITLE
deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

### ISSUE THREAD

**Issue by sarvex** [zeit/now#10027]
Whenever I use vercel plugin in the project. The below warning is emitted. 

`WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs`

**Comment by nostrorom** [comment]
Getting this issue as well as this other one:

https://github.com/vercel/vercel/issues/10222

**Comment by TooTallNate** [comment]
Please update to [`vercel@31.2.0`](https://github.com/vercel/vercel/releases/tag/vercel%4031.2.0) or newer.
