### ISSUE TITLE
Docker doesn't have required permissions to run

### ISSUE THREAD

**Issue by vighnesh153** [zeit/now#10026]
In my repo, my `build` step depends on the `test` step. 

The tests also include integration tests which need a running postgres server. When Vercel builds my repo on the build instance, it doesn't have enough privileges to start the docker daemon which I use to start a local postgres server. Is there a way I can elevate the permissions (or run as root) of the build instance?

I know granting `root` permissions might lead to security issues, but it would be great if you could at least exempt `dockerd` on the build instance, or have a pre-installed and running `dockerd`, it would help a lot.

Thanks.

[Link to discussion](https://github.com/orgs/vercel/discussions/2538)

**Comment by trek** [comment]
Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
