### ISSUE TITLE
Docs: Typo within vercel-postgres/quickstart

### ISSUE THREAD

**Issue by schneedotdev** [zeit/now#10042]
Location: https://vercel.com/docs/storage/vercel-postgres/quickstart

Problem sentence: "Create _an_ Postgres database called pets_postgres_db that's connected to one of your projects"

Solution: "an" should be "a" -> "Create a Postgres database"

**Comment by MohdMusharraf** [comment]
Hi @brianschnee 
I am not able to find Create an Postgres Keyword on the code repository.
Do you where it is?

**Comment by schneedotdev** [comment]
@MohdMusharraf When I first found this, I reached out through the Next.js discord for help, and a mod had told me this portion of the docs was yet to be OSS. I opened the issue but could not locate the problem area in the code base either.

**Comment by trek** [comment]
Hi @schneedotdev,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.

**Comment by trek** [comment]
This also looks to be fixed.

**Comment by oilseamangrid** [comment]
Cheapest API for claude code!

🚀 1k credits (10m tokens) - 5$
⚡ 10k credits (100m tokens) - 30$
🔥 1 credit ~10k tokens

WE CAN GIVE YOU TRIAL CREDITS BEFORE PAY
DM: https://t.me/Momeryal141
