### ISSUE TITLE
Vercel + Cloudflare Proxy = Incorrect location recognition

### ISSUE THREAD

**Issue by andriiPalko** [zeit/now#10102]
I tried to follow this [example](https://github.com/vercel/examples/tree/main/edge-middleware/geolocation) to get the user's geolocation headers but experienced the issue when my site is behind Cloudflare Proxy I am getting geolocation of Cloudflare Proxy IP address but not of a real user. As a workaround, I tried to get geolocation data from [Cloudflare headers](https://developers.cloudflare.com/fundamentals/get-started/reference/http-request-headers/#cf-ipcountry) but figured out that Vercel router is not transferring Cloudflare headers to my application.

Is there anything I can do to make this work?

**Comment by lott-ai** [comment]
@andriiPalko I ran into this issue as well, but ended up solving it by enabling a configuration in Cloudflare: https://developers.cloudflare.com/rules/transform/managed-transforms/configure/

Do you have this enabled in Cloudflare?

<img width="1022" alt="image" src="https://github.com/vercel/vercel/assets/7423098/4a3e3e81-e8ca-45e5-9e3a-3c5cb95e6949">

Also make sure you have IP Geolocation enabled in your Cloudflare network config:

<img width="909" alt="image" src="https://github.com/vercel/vercel/assets/7423098/6cba4bb9-ede2-44d1-9687-5d063504a2c8">

**Comment by andriiPalko** [comment]
@lottamus thank you for your response

yes, I have both these settings enabled in Cloudflare, but the fact that you made it work makes me think that maybe I am doing something wrong on my side. how do you read CF headers in your application? I was trying to read them in middleware, as shown in [this example](https://github.com/vercel/examples/blob/main/edge-middleware/geolocation/middleware.ts) (but reading CF headers obviously)
