### ISSUE TITLE
Vercel CLI Does Not Work on submodules

### ISSUE THREAD

**Issue by Shahaed** [zeit/now#10104]
The CLI checks the repo name via `.git/config` but in a submodule the `.git/config` is stored in the main git folder.

**Comment by Arinono** [comment]
I'd also add that it seems to have the same issue/behaviour with repo cloned `--bare` (and when using worktrees ?):

![image](https://github.com/vercel/vercel/assets/10957531/30bffbb8-5379-40ab-a7fd-e81a7a4a604f)

The config file is located at `<repo_directory>/config` in this case.

Lastly it seems to be a _regression_ as version `29.4.0` behaves nicely in my case

**Comment by arvinxx** [comment]
same problem +1

**Comment by dossy** [comment]
> Lastly it seems to be a regression as version 29.4.0 behaves nicely in my case

Vercel CLI 28.18.5 works as expected for me, while 30.2.1 is broken.

Why does `vercel env pull` even _need_ to touch anything git-related, anyway?

```
$ /usr/local/Cellar/vercel-cli/30.2.1/bin/vercel env pull .env
Vercel CLI 30.2.1
Error: ENOTDIR: not a directory, lstat '[REDACTED]/.git/config'

$ /usr/local/Cellar/vercel-cli/28.18.5/bin/vercel env pull .env
Vercel CLI 28.18.5
> Overwriting existing .env file
> Downloading `development` Environment Variables for Project [REDACTED]
> No changes found.
✅  Updated .env file [338ms]
```

**Comment by thenbe** [comment]
Yeah same issue happens in a [worktree](https://git-scm.com/docs/git-worktree).

```
$ vercel ls
Vercel CLI 32.5.5
Error: ENOTDIR: not a directory, lstat '/home/nbe/projects/worktrees/feat1/.git/config'
```

**Comment by jorgerojas26** [comment]
Same issue here in a worktree

**Comment by darquill** [comment]
Would be neat if this could be fixed as we're going to use both submodules and worktrees in our project :)

Thanks!

**Comment by victorymakes** [comment]
@vercel-team Could you take a look?
