### ISSUE TITLE
Prefetching routes with `<Link />` and a basePath set in `next.config.js` returns 404 on Vercel deployment

### ISSUE THREAD

**Issue by antonioorct** [zeit/now#10129]
The prefetching fails if there is a `basePath` set in the Next config file and it only happens on Vercel's deployment.  
If I remove the basePath it starts working again.  
I've tried it locally with a built application (not dev) and also have it deployed on Heroku and on those it works but on Vercel it fails with a 404.

Minimum reproducable example:  
Example repository: https://github.com/antonioorct/nextjs-basepath-link-test  
Vercel deployment: https://nextjs-basepath-link-test-hajarqy7a-antonioorct.vercel.app/basepath  
Heroku deployment: https://testbasepath-3043b4c4a742.herokuapp.com/basepath

**Comment by trek** [comment]
Hi @antonioorct,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
