### ISSUE TITLE
Respect .gitignore file when deploying

### ISSUE THREAD

**Issue by motdotla** [zeit/now#10187]
Vercel's cli to deploy is great BUT it should respect the gitignore file.

If I'm using Vercel via a GitHub repo connection it respects that - since pushing to GitHub respects it.

But if I'm using Vercel solely from a local repo via the cli, it does not respect that. Instead it requires me to add and maintain a `.vercelignore` file.

Respecting the `.gitignore` file would follow the principle of least surprise and keep users safer.

additional info: https://vercel.com/docs/concepts/deployments/vercel-ignore

**Comment by EndangeredMassa** [comment]
Closing. Details: https://github.com/vercel/vercel/pull/10232#issuecomment-1645921123

**Comment by motdotla** [comment]
Thank you for considering.
