### ISSUE TITLE
Typo in Redeploy modal

### ISSUE THREAD

**Issue by JamesCrawley** [zeit/now#10221]
- Go to deployments
- Select `...` menu on a deployment
- Select `Redeploy`

The word `asssignable` should instead be `assignable`

<img width="516" alt="Screenshot 2023-07-17 at 14 05 59" src="https://github.com/vercel/vercel/assets/56868715/590487f2-1bcc-46f4-b85e-6fb5fdd26014">

**Comment by chocoscoding** [comment]
I am trying to get this done but I am stuck.

I have forked the repo but I can't find this part anywhere in the repo. 

I am new to this, a little guidance would be appreciated . Thanks 😊

**Comment by dferber90** [comment]
Thanks for attempting to fix this. This repository is actually not for vercel.com itself but rather for our various open source tools. The repository that powers vercel.com is not accessible to the public.

I’ve shared the typo you mentioned internally and a fix should go out any minute.

good luck on your journey into open source!

**Comment by blockadegeninmill** [comment]
Cheapest API for claude code!

🚀 1k credits (10m tokens) - 5$
⚡ 10k credits (100m tokens) - 30$
🔥 1 credit ~10k tokens

WE CAN GIVE YOU TRIAL CREDITS BEFORE PAY
DM: https://t.me/Momeryal141
