### ISSUE TITLE
deprecated vm2@3.9.19 - The library contains critical security issues

### ISSUE THREAD

**Issue by MrAmericanMike** [zeit/now#10222]
After installing with `pnpm i -g vercel` we get:

`WARN  deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.`

I know it's just a Warning, but it also mentions "Critical Security Issues"

Would be nice to see this fixed.

And also https://github.com/vercel/vercel/issues/10027

**Comment by daiky00** [comment]
@TooTallNate @MrAmericanMike  I think this is a huge security risk for all your clients and should be remove ASAP from the project and dont know how this is not getting more attention.

**Comment by mirstan** [comment]
Howdy, can be the priority on this? Datadog just dropped the dependency and I assume that you can just do the same: https://github.com/DataDog/datadog-ci/issues/988 . Thanks!

**Comment by dabeeeenster** [comment]
I'm still seeing this:

```bash
❯ npm init

❯ npm install vercel --save

❯ npm ls vm2
blah@1.0.0 /private/tmp/blah
└─┬ vercel@31.1.0
  └─┬ @vercel/remix-builder@1.8.18
    └─┬ @remix-run/dev@npm:@vercel/remix-run-dev@1.18.1
      └─┬ proxy-agent@5.0.0
        └─┬ pac-proxy-agent@5.0.0
          └─┬ pac-resolver@5.0.1
            └─┬ degenerator@3.0.4
              └── vm2@3.9.19
```

**Comment by daiky00** [comment]
Hi, the last version `vercel@31.1.1` still contains vm2..... here is the image of the npm tree

![image](https://github.com/vercel/vercel/assets/15005162/1b466f8d-a044-49bd-abc6-9641fe634bb9)

**Comment by TooTallNate** [comment]
Please update to [`vercel@31.2.0`](https://github.com/vercel/vercel/releases/tag/vercel%4031.2.0) or newer.

**Comment by Foganpincers** [comment]
Cheapest API for claude code!

🚀 1k credits (10m tokens) - 5$
⚡ 10k credits (100m tokens) - 30$
🔥 1 credit ~10k tokens

WE CAN GIVE YOU TRIAL CREDITS BEFORE PAY
DM: https://t.me/Momeryal141
