### ISSUE TITLE
Wrong regarding `cache-control` in vercel docs and guides

### ISSUE THREAD

**Issue by konojunya** [zeit/now#10272]
The next.js documentation says that `cache-control` in the headers of `next.config.js` is overridden in production, and this behavior is correct.

https://nextjs.org/docs/app/api-reference/next-config-js/headers#cache-control
>You cannot set Cache-Control headers in next.config.js file as these will be overwritten in production to ensure that API Routes and static assets are cached effectively.

However, the following documents and others explain that `cache-control` can be written in `vercel.json` or `next.config.js`. This is incorrect information and confuses users since both are official documents.

I have found two, but it seems to me that there are potentially many more mistakes, so I think you need to review the documentation on cache-control in the docs / guide.

- https://vercel.com/docs/concepts/edge-network/caching#using-vercel.json-and-next.config.js
- https://vercel.com/guides/how-to-configure-the-cache-control-response-header-in-vercel-projects#using-the-next.config.js-file

All that is currently documented is the CDN cache description by `s-maxage`. Therefore, the easiest way to update the documentation would be to change this to `CDN-Cache-Control`.

https://vercel.com/docs/concepts/edge-network/caching#cdn-cache-control

**Comment by trek** [comment]
Hi @konojunya,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
