### ISSUE TITLE
Vercel can not support Nodejs Backend? 

### ISSUE THREAD

**Issue by jsonchou** [zeit/now#10306]
Hi，

This is a vercel OUTPUT structure

<img width="403" alt="image" src="https://github.com/vercel/vercel/assets/2245371/ba7102ea-663b-4f49-a78b-a29a5d0128ea">

Such a standard Nodejs （nestjs+prisma） structure, tried dozens of builds and can never get the project to work. 

While this code has been working fine for months in a docker container.

The route shows 404 again and again...

Vercel is a Nodejs starter, but in the end, just a static res holder?

Related articles:
https://vercel.com/guides/using-express-with-vercel
https://vercel.com/guides/npm-run-start-not-working

All of codes MUST be moved to the **/api** directory?

**Comment by Chalkzhu** [comment]
Hi, I had the same problem as you, has it been solved yet?

**Comment by jsonchou** [comment]
> Hi, I had the same problem as you, has it been solved yet?

I use render.com docker way.

**Comment by mthmcalixto** [comment]
Yes bro, vercel supports nestjs: 

vercel.json:
```json
{
  "version": 2,
  "builds": [
    {
      "src": "src/main.ts",
      "use": "@vercel/node"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "src/main.ts",
      "methods": ["GET", "POST", "PUT", "DELETE"]
    }
  ]
}
```

**Comment by comfycush** [comment]
> Yes bro, vercel supports nestjs:
> 
> vercel.json:
> 
> ```json
> {
>   "version": 2,
>   "builds": [
>     {
>       "src": "src/main.ts",
>       "use": "@vercel/node"
>     }
>   ],
>   "routes": [
>     {
>       "src": "/(.*)",
>       "dest": "src/main.ts",
>       "methods": ["GET", "POST", "PUT", "DELETE"]
>     }
>   ]
> }
> ```

Hi, I have added this file, but this error appeared
![image](https://github.com/vercel/vercel/assets/72155210/e403d5bf-4c37-4e93-bdf7-88f0fdc23e59)

and I see this error on vercel log
``Cannot find module 'src/services/password.service'
Require stack:
- /var/task/src/users/users.service.js
- /var/task/src/users/users.module.js
- /var/task/src/auth/auth.module.js
- /var/task/src/app.module.js
- /var/task/src/main.js
Did you forget to add it to "dependencies" in `package.json`?
INIT_REPORT Init Duration: 726.02 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
Cannot find module 'src/services/password.service'
Require stack:
- /var/task/src/users/users.service.js
- /var/task/src/users/users.module.js
- /var/task/src/auth/auth.module.js
- /var/task/src/app.module.js
- /var/task/src/main.js
Did you forget to add it to "dependencies" in `package.json`?
INIT_REPORT Init Duration: 1287.99 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Error: Runtime exited with error: exit status 1
``
did I miss something here?

**Comment by leechanghoon3024** [comment]
> 네, vercel은 Nestjs를 지원합니다:
> 
> vercel.json:
> 
> ```json
> {
>   "version": 2,
>   "builds": [
>     {
>       "src": "src/main.ts",
>       "use": "@vercel/node"
>     }
>   ],
>   "routes": [
>     {
>       "src": "/(.*)",
>       "dest": "src/main.ts",
>       "methods": ["GET", "POST", "PUT", "DELETE"]
>     }
>   ]
> }
> ```
In my case, this doesn't work.

**Comment by CodeGetters** [comment]
> Yes bro, vercel supports nestjs:是的，兄弟，vercel 支持 nestjs：
> 
> vercel.json:  vercel.json：
> 
> ```json
> {
>   "version": 2,
>   "builds": [
>     {
>       "src": "src/main.ts",
>       "use": "@vercel/node"
>     }
>   ],
>   "routes": [
>     {
>       "src": "/(.*)",
>       "dest": "src/main.ts",
>       "methods": ["GET", "POST", "PUT", "DELETE"]
>     }
>   ]
> }
> ```

I have the same problem, here is my configuration information
```json
{
  "version": 2,
  "buildCommand": "pnpm build",
  "devCommand": "pnpm start:dev",
  "installCommand": "pnpm install",
  "outputDirectory": "dist",
  "builds": [
    {
      "src": "dist/main.js",
      "use": "@vercel/node"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "methods": ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
      "headers": {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type, Accept"
      },
      "dest": "dist/main.js"
    }
  ],
}
```

The following warning occurs at deployment time

```text
WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
```

this is my package.json
```json
{
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json",
    "schema:merge": "node prisma/mergeSchemas.js",
    "generate": "nest generate"
}
```
I haven't been able to find a solution to this problem
