### ISSUE TITLE
Migrate to TypeScript leads to error Can't resolve '@/styles/globals.css'

### ISSUE THREAD

**Issue by setoelkahfi** [zeit/now#10322]
I'm playing around with the [boilerplate template](https://vercel.com/templates/next.js/nextjs-boilerplate) and found this strange issue when trying to use TypeScript with the default NextJS configuration. I mean, by changing the file from `.js` to `.tsx` / `.tsx`. I tried several versions of NextJS 13 up to the latest. And also the TypeScript 5 and 4.

```
error - ./pages/_app.tsx:1:0
Module not found: Can't resolve '@/styles/globals.css'
> 1 | import '@/styles/globals.css'
  2 | import { Analytics } from '@vercel/analytics/react'
  3 |
  4 | export default function App({ Component, pageProps }) {

https://nextjs.org/docs/messages/module-not-found
```

My VSCode cannot find the file when I command+click it, but when I changed the file to `Globals.module.css,` it could. But the error still exists: module not found.

Any pointers?

**Comment by Andes0113** [comment]
Inside your tsconfig.json, add to paths under compilerOptions: 
`
  "compilerOptions": {
    "paths": {
      "@/*": ["./*"],
    },
`
This makes TypeScript recognize this type of import, pulling files from root when prefaced with @.

**Comment by setoelkahfi** [comment]
Hey @Andes0113 
Thanks. But I ended up using the latest example. I'll close this issue.

**Comment by skillitzimberg** [comment]
> Inside your tsconfig.json, add to paths under compilerOptions: `"compilerOptions": { "paths": { "@/*": ["./*"], },` This makes TypeScript recognize this type of import, pulling files from root when prefaced with @.

This does not work in my set up.

I generated the project with `npx create-next-app@latest` so I expect everything to work from the start. Still looking for a solution.

**Comment by Andes0113** [comment]
@skillitzimberg 
When you were using `npx create-next-app`, what options did you check? Otherwise it's difficult for me to reproduce the issue. 

I'm not sure what might be the issue on your end, but this fix wouldn't work if you're using the src directory. In that case, you'd need to substitute `"./src/*"` for `./*`. If you could link me to a repo where you're running into this issue I could possibly help you out more.

**Comment by Michaecyber** [comment]
hi am using nextjs 14 App same issue doesnt work

**Comment by richardtknight** [comment]
@Michaecyber I came across the same problem using NextJS 15.5.5 and Typescript 5.8.3
The solution for me was to add:
```ts
declare module '*.css' {
  const content: Record<string, string>
  export default content
}
```

to src > types > global.d.ts

Basically this just allows typescript to recognise CSS imports.
Hopefully this is helpful to somebody who experiences the same issue.
