### ISSUE TITLE
Golang functions failing deployment at `go mod tidy`

### ISSUE THREAD

**Issue by ededejr** [zeit/now#10357]
Hello! I'm cross-posting here for visibility but also have another discussion open [here](https://github.com/orgs/vercel/discussions/3644). I've been building standalone APIs using Golang functions on Vercel. With some deployments and locally as well, I get the following error when running `go mod tidy`:

```
routes/node_modules/@vercel/go/dist: import path "routes/node_modules/@vercel/go/dist" should not have @version
failed to `go mod tidy`
Error: Command failed: go mod tidy
```

Locally this can be fixed this by:
* Running `go mod tidy` before installing `node_modules`
* By deleting `node_modules`

However this is blocking my deployments. Any help would be appreciated 🙂

**Comment by laulauland** [comment]
Seeing this as well - deploys are blocked on Vercel due to the issue

**Comment by ededejr** [comment]
I unblocked myself by uninstalling `vercel` as a dep from the project and making it a global dependency instead.

cc @keturiosakys if that helps
