### ISSUE TITLE
Docs: Conflicting Streaming examples

### ISSUE THREAD

**Issue by PrinceRajRoy** [zeit/now#10405]
Hi, 
there seems to be a conflict in the file path under `/pages` example in [Streaming](https://vercel.com/docs/frameworks/nextjs#streaming)

![image](https://github.com/vercel/vercel/assets/47452572/85aae740-c664-4dbe-8266-ddfa488d5019)

Shouldn't it be `app/api/streaming-example/route.ts`, since streaming responses are only available with Route Handlers.

Conflicts with the example in [Streaming data with Edge Functions](https://vercel.com/docs/functions/edge-functions/streaming#streaming-data-with-edge-functions)

![image](https://github.com/vercel/vercel/assets/47452572/2ffc6610-e9bd-4345-87b5-33820df1e411)

**Comment by trek** [comment]
Hi @PrinceRajRoy,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
