### ISSUE TITLE
swagger does not load on vercel

### ISSUE THREAD

**Issue by m0x61h0x64i** [zeit/now#10412]
Hi, yesterday I could load my swagger docs using its URL, but today when i committed my new changes it no longer loads my swagger docs on production, but on the development everything works fine.

my last commit was on Jul 3, at that moment until new commit which was today i dint have problem because yesterday docs loaded fine

after i pushed my new commit today, swagger does not load on production, i can see some errors in the console :

![image](https://github.com/scottie1984/swagger-ui-express/assets/109550653/37967684-1d9b-42a7-b165-09fe84a57d00)
```
swagger-ui-bundle.js:3 Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-bundle.js:3:1)
swagger-ui-standalone-preset.js:3 Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-standalone-preset.js:3:1)
DevTools failed to load source map: Could not load content for https://*/api-docs/swagger-ui.css.map: Unexpected token '<', "
<!-- HTML "... is not valid JSON
swagger-ui-init.js:58 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (swagger-ui-init.js:58:7)
```

I have tried disabling all routes, cause i have written new routes and docs, but that didnt help.

now this is my localhost : 
![image](https://github.com/scottie1984/swagger-ui-express/assets/109550653/26607df6-28c0-4bf6-8621-4c2e4cbc7a58)

and this is my production swagger : 
![image](https://github.com/scottie1984/swagger-ui-express/assets/109550653/c30aff09-bd85-4c49-99da-800082584cb0)

swagger-jsdoc version : 6.2.8
swagger-ui-express version : 5.0.0
hosting: vercel

my problem wont be my code, i have checked my Jul 3 commit and it is the same code as it is and also i removed the routes to test if it can be loaded or not but it didnt load swagger doc on production. 

EDIT: I have gone to my Jul 3 commit which was the working state of the swagger doc, and it works.

I found the bug, the bug here is that the new version of swagger-ui-express is not compatible with swagger-jsdoc version 6.2.8 but with swagger-ui-express version 4.6.3 and swagger-jsdoc version 6.2.8 it works as expected.

**Comment by m0x61h0x64i** [comment]
the problem is lib side, i apologies for the issue

**Comment by akinsanmi60** [comment]
@m0x61h0x64i degrading the swagger-ui-express version to 4.6.3 worked for me. Thank you very much

**Comment by m0x61h0x64i** [comment]
> @m0x61h0x64i degrading the swagger-ui-express version to 4.6.3 worked for me. Thank you very much

welcome

**Comment by brandbold-Ch** [comment]
Me ayudó mucho ese info, muchas gracias

**Comment by brandbold-Ch** [comment]
ayudó

**Comment by brandbold-Ch** [comment]
Me funcionó mucho

**Comment by BhavyaKachhadiya** [comment]
thank you

**Comment by MD-SanjayKumar** [comment]
Facing issue on deployed express ts api on vercel, works fine on local. shows No operations defined in spec! on vercel while on local i'm able to see specs and works fine.

**Comment by kyleysrael** [comment]
> Facing issue on deployed express ts api on vercel, works fine on local. shows No operations defined in spec! on vercel while on local i'm able to see specs and works fine.

Have you figured this out? I'm having the same issue.

![image](https://github.com/user-attachments/assets/e251e3af-6352-4e1a-bf7b-269d65d3f6c2)
![image](https://github.com/user-attachments/assets/11782728-27d9-404e-a386-f00532434815)
![image](https://github.com/user-attachments/assets/f1a69765-0723-4411-981c-b762215d5ec9)

**Comment by leszekkrol** [comment]
Same issue any thoughts ?

**Comment by agustin-sanc** [comment]
I'm using Nest.js, I added these objects inside the `routes` array inside of the `vercel.json` file and now the Swagger styles and JavaScript files are working fine.

```json
{
      "src": "/api/swagger-ui.css",
      "dest": "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui.min.css"
    },
    {
      "src": "/api/swagger-ui-bundle.js",
      "dest": "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-bundle.min.js"
    },
    {
      "src": "/api/swagger-ui-standalone-preset.js",
      "dest": "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-standalone-preset.min.js"
    },
```

**Comment by atalayio** [comment]
> I'm using Nest.js, I added these objects inside the `routes` array inside of the `vercel.json` file and now the Swagger styles and JavaScript files are working fine.
> 
> {
>       "src": "/api/swagger-ui.css",
>       "dest": "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui.min.css"
>     },
>     {
>       "src": "/api/swagger-ui-bundle.js",
>       "dest": "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-bundle.min.js"
>     },
>     {
>       "src": "/api/swagger-ui-standalone-preset.js",
>       "dest": "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-standalone-preset.min.js"
>     },

This didn't help me completely, it worked for some issues but it was still showing blank. The problem was solved with this vercel.json:

```json
//vercel.json
  "routes": [
    {
      "src": "/api-docs/swagger-ui.css",
      "dest": "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui.min.css"
    },
    {
      "src": "/api-docs/swagger-ui-bundle.js",
      "dest": "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-bundle.min.js"
    },
    {
      "src": "/api-docs/swagger-ui-standalone-preset.js",
      "dest": "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-standalone-preset.min.js"
    },
    {
      "src": "/api-docs/swagger-ui-init.js",
      "dest": "app.js"
    },
    {
      "src": "/api-docs.json",
      "dest": "app.js"
    },
    {
      "src": "/(.*)",
      "dest": "app.js"
    }
  ]
```

**Comment by Chernik1991** [comment]
vercel.json
{
  "version": 2,
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "name": "bloggerPlatform",
  "buildCommand": "pnpm run build",
  "builds": [
    { "src": "src/index.ts", "use": "@vercel/node",
      "config": {
        "includeFiles":["./node_modules/**","src/**/*.yml"]
      }
    }
  ],
  "routes": [
    { "src": "/(.*)", "dest": "src/index.ts"}
  ]
}

and add in package.json  "build": "tsc && cpx \"src/**/*.yml\" dist", end install cpx

**Comment by ahmedatef286** [comment]
I faced a similar issue. In your project if you have the swagger documentation in a separate folder (ie /docs/sth.js). Vercel doesn't include these files in the build process i think. Adding
 ` "config": {
        "includeFiles": ["docs/**"]
      }` 
to the vercel.json for me fixed it , here is it in full : 
`{
  "version": 2,
  "builds": [
    {
      "src": "server.js",
      "use": "@vercel/node",
        "config": {
        "includeFiles": ["docs/**"]
      }
    }
  ],
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/server.js"
    }
  ]
}`

**Comment by PhanNhatLoi** [comment]
I ran into the same issue recently and found a different workaround that worked for me on Vercel.
After testing it in a real deployment, Swagger UI loaded correctly and all assets were served as expected.
I've put together a minimal reproducible example with the required Vercel configuration here:
https://github.com/PhanNhatLoi/vercel-swagger

<img width="1846" height="1100" alt="Image" src="https://github.com/user-attachments/assets/662ab433-2c23-42a9-8253-28f36060129e" />

**Comment by flyingduck92** [comment]
> Hi, yesterday I could load my swagger docs using its URL, but today when i committed my new changes it no longer loads my swagger docs on production, but on the development everything works fine.
> 
> my last commit was on Jul 3, at that moment until new commit which was today i dint have problem because yesterday docs loaded fine
> 
> after i pushed my new commit today, swagger does not load on production, i can see some errors in the console :
> 
> ![image](https://github.com/scottie1984/swagger-ui-express/assets/109550653/37967684-1d9b-42a7-b165-09fe84a57d00)
> 
> ```
> swagger-ui-bundle.js:3 Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-bundle.js:3:1)
> swagger-ui-standalone-preset.js:3 Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-standalone-preset.js:3:1)
> DevTools failed to load source map: Could not load content for https://*/api-docs/swagger-ui.css.map: Unexpected token '<', "
> <!-- HTML "... is not valid JSON
> swagger-ui-init.js:58 Uncaught ReferenceError: SwaggerUIBundle is not defined
>     at window.onload (swagger-ui-init.js:58:7)
> ```
> 
> I have tried disabling all routes, cause i have written new routes and docs, but that didnt help.
> 
> now this is my localhost : ![image](https://github.com/scottie1984/swagger-ui-express/assets/109550653/26607df6-28c0-4bf6-8621-4c2e4cbc7a58)
> 
> and this is my production swagger : ![image](https://github.com/scottie1984/swagger-ui-express/assets/109550653/c30aff09-bd85-4c49-99da-800082584cb0)
> 
> swagger-jsdoc version : 6.2.8 swagger-ui-express version : 5.0.0 hosting: vercel
> 
> my problem wont be my code, i have checked my Jul 3 commit and it is the same code as it is and also i removed the routes to test if it can be loaded or not but it didnt load swagger doc on production.
> 
> EDIT: I have gone to my Jul 3 commit which was the working state of the swagger doc, and it works.
> 
> I found the bug, the bug here is that the new version of swagger-ui-express is not compatible with swagger-jsdoc version 6.2.8 but with swagger-ui-express version 4.6.3 and swagger-jsdoc version 6.2.8 it works as expected.

I had this issue currently, the swagger route display a blank white page
my packages: 
```
    "swagger-autogen": "^2.23.7",
    "swagger-ui-dist": "^5.32.6",
    "swagger-ui-express": "^5.0.1",
```
