### ISSUE TITLE
Bun with Remix fails to build on a fresh project

### ISSUE THREAD

**Issue by emadabdulrahim** [zeit/now#10488]
Steps to repro:
- `bunx create-remix` 
- run `bun install` locally to create a `bun.lockb` file
- deploy project on vercel with default `remix` settings

Errors on build
```
Running "bun run build"
--
19:56:45.059 | $ remix build
19:56:45.880 | info  building... (NODE_ENV=production)
19:56:46.753 | info  built (873ms)
19:56:46.817 | Error: File /vercel/path0/api/build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.js does not exist.
```

**Comment by TooTallNate** [comment]
Thanks for the report. Fix is here: https://github.com/vercel/vercel/pull/10489

As a temporary workaround, you can use this fix on your deployment by setting an environment variable with name `VERCEL_CLI_VERSION` and value `https://vercel-a71b36wfe.vercel.sh/tarballs/vercel.tgz`.

> [!NOTE]
> You should not be using the "Vercel" preset in `create-remix` at this point. Just use the default "Remix App Server" template. Vercel knows how to handle that format natively.
>
> Also, to get the full benefits of Remix when deploying to Vercel, be sure to use the `@vercel/remix` package throughout your application, instead of `@remix-run/node`. See here for more details: https://vercel.com/docs/frameworks/remix

**Comment by emadabdulrahim** [comment]
Thanks a lot @TooTallNate! Will update my setup to your recommendation.
