### ISSUE TITLE
Failed runtime on a fresh Remix + Bun setup

### ISSUE THREAD

**Issue by emadabdulrahim** [zeit/now#10494]
Repro Steps:
- Install a fresh Remix project using https://github.com/vercel/vercel/tree/main/examples/remix
- Bun install, commit `Bun.lockb` file
- Delete `edge.tsx`
- Deploy to vercel

While the deployment succeeds, the site doesn't load as there's `500` server error

![CleanShot 2023-09-12 at 09 14 21@2x](https://github.com/vercel/vercel/assets/7950797/91b6897c-0321-4241-ab79-c37f5ed370b4)

## Logs
```
2023-09-12T23:15:51.918Z	undefined	ERROR	Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/build/build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.js' imported from /var/task/build/server-build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.mjs
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:329:11)
    at moduleResolve (node:internal/modules/esm/resolve:992:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:936:12)
    at defaultResolve (node:internal/modules/esm/resolve:1178:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
RequestId: d3880205-6853-4d3a-84a8-b87fb9ed227b Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by Sandy-Garrido** [comment]
Same issue here.
I instead switched out pnpm directly for bun and that alone just caused it to fail
(Just removed pnpm lock & up'd the bun lock file, no other files changed)

**Comment by sandy-garrido** [comment]
I actually seem to be hitting this also!
Mine isn't a fresh build though, it was an existing working vercel deployed project with Remix that I'd simply replaced pnpm for bun as the package manager. I have the exact same issue as the one in description

**Comment by sandy-garrido** [comment]
@emadabdulrahim Are you using remix v2 pre-release? (though, as the OP suggest, probably not.)

Weird, I just downgraded my pre-release to 1.19.3 and bun install worked this time?

One thing I noticed in the logs is that the build step seems to ALWAYS install the latest release of @remix-run/dev which is 1.19.3. 

I'm suggesting the issue being likely related to Vercel's implementation of remix (maybe not compatible with v2 pre release) than the implementation of bun

**Comment by emadabdulrahim** [comment]
I'm using 1.19.3 as well but all Future Flags are turned on (Default settings after running `bunx create-remix`

Yeah I could see it being that. However, if you try to create a new remix project using `yarn` and deploy that, I believe it works fine. But then if you delete `yarn.lock` and add `bun.lockb` instead, the error will show up.

Or am I missing something?

**Comment by emadabdulrahim** [comment]
@Sandy-Garrido It seems to magically work now. I haven't even redeployed or anything, but that runtime error doesn't show up anymore.

**Comment by Gauravjadhav22** [comment]
I found this issue on https://ovio.org/projects and would love to contribute! [add other relevant info about you]

**Comment by emadabdulrahim** [comment]
Also Remix v2 doesn't seem to work on Vercel. Try a default Remix app using `bunx create-remix`. Deployment succeeded but there's a runtime error 

```
file:///var/task/build/server-build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.mjs:2
  AbortController as NodeAbortController,
  ^^^^^^^^^^^^^^^
SyntaxError: Named export 'AbortController' not found. The requested module '@remix-run/node' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@remix-run/node';

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
RequestId: c1fb58ba-f5be-4011-a60e-60bd87b26014 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Any clue how to fix?

**Comment by sandy-garrido** [comment]
> Also Remix v2 doesn't seem to work on Vercel. Try a default Remix app using `bunx create-remix`. Deployment succeeded but there's a runtime error 
> 
> ```
> file:///var/task/build/server-build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.mjs:2
>   AbortController as NodeAbortController,
>   ^^^^^^^^^^^^^^^
> SyntaxError: Named export 'AbortController' not found. The requested module '@remix-run/node' is a CommonJS module, which may not support all module.exports as named exports.
> CommonJS modules can always be imported via the default export, for example using:
> 
> import pkg from '@remix-run/node';
> 
>     at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
>     at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
> RequestId: c1fb58ba-f5be-4011-a60e-60bd87b26014 Error: Runtime exited with error: exit status 1
> Runtime.ExitError
> ```
> 
> Any clue how to fix?

Remix v2 pre release will most likely not work. The Vercel team work hard to make it work with Vercel platform.

Please follow this issue here for v2 support
 https://github.com/vercel/remix/issues/53

**Comment by benjaminleonard** [comment]
Running into the same issue on Remix 2.0.1:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/build/build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.js' imported from /var/task/build/server-build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.mjs
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:329:11)
    at moduleResolve (node:internal/modules/esm/resolve:992:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:936:12)
    at defaultResolve (node:internal/modules/esm/resolve:1178:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by emadabdulrahim** [comment]
I'm taking a break from trying to deploy remix to vercel until things get stable. When I have time to give cloudflare a try and see how it goes.

**Comment by franklinjavier** [comment]
@emadabdulrahim, did you manage to solve it? I'm stuck here as well.

**Comment by emadabdulrahim** [comment]
I managed to get it to work but I remember seeing intermittent runtime errors which made it seem Remix deploy wasn't very stable. However I took a break from the project so not sure what the current status is of deploying latest Remix on Vercel

**Comment by franklinjavier** [comment]
Thank you. 
I fixed the issue, but i still have the same concern

**Comment by franklinjavier** [comment]
Here is how I fixed: 

- add `serverModuleFormat: 'cjs',` to remix.config.js
- remove "type": "module" from package.json
- install `"@remix-run/vercel": "^1.19.3",` -- This is essential to be able to work :(

**Comment by TooTallNate** [comment]
This was fixed by https://github.com/vercel/vercel/pull/10489. Please open a new issue if there is still something not working correctly.

**Comment by JClackett** [comment]
Have posted a new issue related to this as I am now running into this all of a sudden on my remix app.

**Comment by Technoash** [comment]
https://discord.com/channels/770287896669978684/1172143181660422194 <-- same issue being discussed here
If you ended up here looking for a solution - this is what worked for me

1. [update vercel cli to the latest version](https://vercel.com/docs/cli#updating-vercel-cli)
2. run `vercel build` on your local
3. you might see that vercel-cli modified your package.json and remix.conf.js. they do some "magic" at build time in their build process that changes some vercel packages to their own (ref: https://github.com/vercel/vercel/blob/main/packages/remix/src/build.ts#L175)
4. make sure the build succeeds, commit your changes and deploy

This will get you closer to having a working build

Also note that for me having `serverBuildTarget: "cjs"` in remix config and not having `"type": "module"` in package.json only worked for me at the time of writing

**Comment by JClackett** [comment]
Alright I've found the reason why it's not working (for me). the `vercel-cli` package updated a week ago, and the new version isn't copying a file to the build output so it can't reference it.

<img width="461" alt="Screenshot 2023-12-04 at 13 34 30" src="https://github.com/vercel/vercel/assets/12549124/e0b43bbb-6091-4c75-bbaf-7d36d52e40c7">

In the new versions of vercel-cli `build-nodejs-xxx.js` isn't in the directory of the function. So this import in the `server-build-nodejs-xxx.mjs` file throws an error.:

```js
import * as build from './build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.js';
```

My remix app is also in a pnpm monorepo, under apps/remix, not sure if that would be affecting things in the newer cli's?


Reverting to vercel-cli 32.5.6 fixes it for me, so am manually deploying from cli for now, is there a way to set the vercel-cli in the actual vercel dashboard?

**Comment by alexeisamuta** [comment]
@JClackett 
You can try adding an environment variable with the name `VERCEL_CLI_VERSION` and a value `vercel@32.5.6`.

**Comment by franklinjavier** [comment]
> @JClackett You can try adding an environment variable with the name `VERCEL_CLI_VERSION` and a value `vercel@32.5.6`.

In my case, I deleted this env var from the Vercel panel

**Comment by JClackett** [comment]
> @JClackett 
> 
> You can try adding an environment variable with the name `VERCEL_CLI_VERSION` and a value `vercel@32.5.6`.

Yep, have set the env and now builds are running again :) will just pray a newer version of the cli works/vercel takes a look at my issue

**Comment by charklewis** [comment]
@TooTallNate this issue is ongoing, could you please re-open this issue? or is it best to open a new one with the same description?

**Comment by JClackett** [comment]
> @TooTallNate this issue is ongoing, could you please re-open this issue? or is it best to open a new one with the same description? 

Have one here https://github.com/vercel/vercel/issues/10893

**Comment by lyonsun** [comment]
Having the same issue.

**Comment by lopugit** [comment]
How's everyone going with this? 

I'm getting this on a remix(v2)/vite/vercel project 

![Screenshot 2024-07-24 at 02 02 14 PM - Google Chrome - thingtime – Deployment Runtime Logs – Vercel](https://github.com/user-attachments/assets/d459e9fb-3a42-4714-a910-89b582628af8)

EDIT:

Ok cool just adding `serverModuleFormat: 'cjs'` fixed the issue.

Some keywords for anyone experiencing this issue on Vercel Remix Vite Chakra UI Emotion JS / Remix V2 

Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
(node:12) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/var/task/build/server/index.js:1
import { jsx, jsxs, Fragment } from "react/jsx-runtime";
^^^^^^

SyntaxError: Cannot use import statement outside a module

This was the full error output:

```
(node:12) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/var/task/build/server/index.js:1
import { jsx, jsxs, Fragment } from "react/jsx-runtime";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:76:18)
    at wrapSafe (node:internal/modules/cjs/loader:1283:20)
    at Module._compile (node:internal/modules/cjs/loader:1328:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at /opt/rust/nodejs.js:1:11506
    at Function.Zt (/opt/rust/nodejs.js:1:11879)
    at Y.e.<computed>.Z._load (/opt/rust/nodejs.js:1:11476)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:203:29)
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
(node:12) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/var/task/build/server/index.js:1
import { jsx, jsxs, Fragment } from "react/jsx-runtime";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:76:18)
    at wrapSafe (node:internal/modules/cjs/loader:1283:20)
    at Module._compile (node:internal/modules/cjs/loader:1328:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at /opt/rust/nodejs.js:1:11506
    at Function.Zt (/opt/rust/nodejs.js:1:11879)
    at Y.e.<computed>.Z._load (/opt/rust/nodejs.js:1:11476)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:203:29)
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
```
