### ISSUE TITLE
curl -X DELETE on `/api/` endpoint causes TypeError: fetch failed

### ISSUE THREAD

**Issue by keithwhor** [zeit/now#10547]
macOS Monterey 12.5
node 20.6.1
vercel 32.2.5

Attempting a `curl localhost:3000/api/my_endpoint -X DELETE` triggers:

```
TypeError: fetch failed
    at fetch (/usr/local/lib/node_modules/vercel/node_modules/undici/index.js:109:13)
    at async file:///usr/local/lib/node_modules/vercel/node_modules/@vercel/node/dist/serverless-functions/serverless-handler.mjs:77:26
    at async Server.onDevRequest (file:///usr/local/lib/node_modules/vercel/node_modules/@vercel/node/dist/dev-server.mjs:72:43)
```

Interestingly, `GET`, `POST`, `PUT` all work fine.

**Comment by ErickLuis00** [comment]
I'm testing an ExpressJS API, and the only endpoint that doesn't work is DELETE. **However, it works if a body is included in the request.**

I'm using the following code:
```js
import express from 'express'
const app = express()

app.delete('/', (req, res) => { ... })

export default app
```

and running with:
```
vercel dev
```

Vercel CLI 32.3.0

**Comment by emirotin** [comment]
My vercel-based API just got entirely broken for usage from the browser because of this issue
The actual problem is this: https://github.com/nodejs/undici/issues/2046

In my case, the OPTIONS requests would start throwing 500 because they are also body-less

**Comment by yensresmann** [comment]
@emirotin I'm having the same issue. Updating **undici to 5.27.1** fixes this issue.

**Comment by trek** [comment]
Hi @keithwhor,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
