### ISSUE TITLE
CRON jobs runs only on main branch

### ISSUE THREAD

**Issue by ghost** [zeit/now#10550]
I added the CRON job to my development branch, but it only runs on the main branch. Is this expected? Can I check CRON jobs running outside the main branch? Vercel [documentation](https://vercel.com/docs/cron-jobs) doesn't seem to address this.

**Comment by reconcrete** [comment]
This is addressed in the link below. "Cron jobs are invoked only for production deployments"
[Vercel Docs](https://vercel.com/guides/how-to-setup-cron-jobs-on-vercel#deploy-your-project)

However, you right. It would be helpful to have at least in Preview

**Comment by barrynorman** [comment]
This does not make sense IMHO
Why is this only for prod?

**Comment by Shawns2759** [comment]
This was pretty hard to figure out...

**Comment by mtford90** [comment]
Most teams will have e.g. a sandbox/staging/test environment where the idea is to get as close to production environment as possible. The fact that cron jobs only run in production means we can't really use that feature, as it can't be tested!

The only workaround I can think of is to have a seperate app for the sandbox env which is rather awkward.

**Comment by gauthamp10** [comment]
This is a deal breaker!!!!. Please fix this!

**Comment by MW-Hochmann** [comment]
Why was this closed without comment? I just ran into the same issue and it doesn't specifically mention this limitation in the [docs](https://vercel.com/docs/cron-jobs) (the page only vaguely alludes to it "Vercel makes an HTTP GET request to your project's production deployment URL"). At least update the docs, so people can know that vercel cron jobs can't be tested in a regular way.
