### ISSUE TITLE
Build Error Due to material-tailwind/react

### ISSUE THREAD

**Issue by lbovboe** [zeit/now#10654]
It was working perfectly fine before yesterday. But after the patch today I'm unable to build in vercel without changing anything. the cause is material-tailwind/react and it seems not supported in new patch, it got this error of maximum stack exceed. Once I remove the usage of material-tailwind/react then it is working fine. But a lot of my UI r using it, how can I solve the issue? Thx!

**Comment by LikeFireAndSky** [comment]
I am experiencing the same error...🥲🥲

added...) I found the quick fix solution!!

I think there are errors on the next.js 13.5.4(latest version), so I downgrade next version to 13.5.3
```node
npm i next@13.5.3
```

After changing the version, I found problem in Vercel Production Domain, so I changed the Production Domain name same as Development url name...

It is just my quick fix solution!! If you found something better, please let me know 🥹🥹🥹
