### ISSUE TITLE
Error: Unable to find lambda for route: /en

### ISSUE THREAD

**Issue by gittygoo** [zeit/now#10665]
Trying to "vercel build" an app with "pages" routing and using next-translate yields this :

```
Traced Next.js server files in: 47.024ms
Created all serverless functions in: 794.415ms
Error: Unable to find lambda for route: /en
```
The only solution seems to be doing something like this: https://github.com/aralroca/next-translate/issues/1142#issuecomment-1708385197

however this seems like a bug on the vercel cli somehow ?

the same happens if we use the next-intl package instead

**Comment by trek** [comment]
Hi @gittygoo,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
