### ISSUE TITLE
Issue with Login - Unable to Access Account

### ISSUE THREAD

**Issue by hamzakashif5289** [zeit/now#10728]
**I Email this to registration@vercel.com one month ago and still no response from vercel and till now I didn't access my account.
The baddest customer support in life was vercel customer support.**

I am writing to seek assistance with a pressing issue I am encountering while trying to access my Vercel account. I have been facing a significant login problem, and I would appreciate your prompt attention to resolve this matter.

When attempting to log in using my registered email address, I consistently receive the following error message: "We are unable to complete your signup. Please read this guide for further details." This message has been preventing me from accessing my Vercel account and carrying out necessary actions.

Furthermore, I attempted to sign up again with the same email address to see if it would provide any clarity or solutions to the issue. However, during the signup process, I received a different message indicating that the email address was already associated with an account on Vercel.

This contradictory behavior has left me perplexed and unable to access my account, which is causing significant disruption to my work and projects hosted on Vercel. I have reviewed the guide mentioned in the error message, but it did not provide any insight or solutions for resolving this issue.

I kindly request your assistance in resolving this login problem as soon as possible. It is imperative that I regain access to my Vercel account to continue managing my projects and services. If there are any specific steps or information required from my end to expedite this process, please do not hesitate to inform me, and I will promptly provide the necessary details.

Thank you for your attention to this matter, and I look forward to your prompt response and assistance in resolving this issue.

Sincerely,

Hamza Kashif
[hamzakashif5289@gmail.com]
![Screenshot 2023-09-27 224959](https://github.com/vercel/vercel/assets/123292719/b40e02a5-2184-462c-a2b8-76a69ca8f02b)
![Screenshot 2023-09-27 225044](https://github.com/vercel/vercel/assets/123292719/40b4ec20-2bb1-4ee5-b6a0-524085217fd4)

**Comment by ghost** [comment]
I guess vercel isn't taking new accounts. 
Same issue happened to me. 

Till now no response. It just shows "user account is blocked"

**Comment by poullot-francois** [comment]
même souci depuis plus d'un mois et aucune réponse de leur services

**Comment by minimingchn** [comment]
Same problem for over four months, looking forward to the official reply.

**Comment by poullot-francois** [comment]
ils ne répondent pas ils s'en foutent royalement, en fait il faut créer un autre compte mail pour ouvrir un compte chez eux, sauf que moi le compte est celui de l'école, du coup dans la panade.

au moins je saurais qu'ils manquent totalement de professionnalisme (je fais une formation pro dev) je saurais qu'il ne faut pas les utiliser.

j'ai du coup préférer faire un hébergement normale avec un nom de domaine  web pour mes test tant pis

mais Vercel pas pro !! à fuir

**Comment by poullot-francois** [comment]
ils m'ont répondu et validé mon adresse, par contre il faut faire attention a la procédure de validation, pour moi maintenant avec l'adresse de mon école tout est ok

**Comment by alvinsjoy** [comment]
Try contacting vercel via support@vercel.com. It worked for me (#10000)

**Comment by Lawck** [comment]
my account is blocked for vercel can you unblock me ?

**Comment by poullot-francois** [comment]
Le 2024-01-09 14:05, Lawck a écrit :
> my account is blocked for vercel can you unblock me ?

bonjour, je n'appartient pas a la société vercel, je suis étudiant et 
c'est eux qui m'ont débloqué le compte.
