### ISSUE TITLE
Error: We could not upload the edge function temporarily. Please try again later.

### ISSUE THREAD

**Issue by Nedimko123** [zeit/now#10793]
What's going on, the build completes but now it won't deploy or something. It was working fine yesterday, I am using Qwik:

Build succeeds:

Deploying outputs...
<span>Injected preview comments middleware, you can disable this in your project settings.</span>

But after these, it just gets stuck and I get an error after a couple of minutes saying: Error: We could not upload the edge function temporarily. Please try again later.

**Comment by balintstorefront** [comment]
same happened with our project, apparently there is an issue with vercel currently
![vercel outage](https://github.com/vercel/vercel/assets/142796042/0fd961ca-f26a-44be-b57e-5808474c7229)

(src: https://www.vercel-status.com/)

**Comment by Nedimko123** [comment]
The solution should be to wait until it is resolved, nothing wrong with our code, then.

**Comment by aqibgatoo** [comment]
Same issue

**Comment by JVLandayan** [comment]
same

**Comment by ayinde-xyz** [comment]
same too

**Comment by ibrahimtuksal** [comment]
same

**Comment by XahidEx** [comment]
> The solution should be to wait until it is resolved, nothing wrong with our code, then.

Exactly

**Comment by joshdance** [comment]
I'm getting this error. Seems like the solution is to just wait? 

https://www.vercel-status.com/ status page says they are deploying a fix

**Comment by XahidEx** [comment]
> I'm getting this error. Seems like the solution is to just wait?
> 
> https://www.vercel-status.com/ status page says they are deploying a fix

Yeah, we'll have to wait. Although It's taking too long.

**Comment by xta** [comment]
Same right now

> Error: We could not upload the edge function temporarily. Please try again later.

**Comment by mathiasfc** [comment]
Same here

**Comment by Nedimko123** [comment]
same again

**Comment by rohanagarwal** [comment]
Happening to me too

**Comment by pedrovrima** [comment]
Same

**Comment by vule96** [comment]
Same here

**Comment by nimatrazmjo** [comment]
same here

**Comment by joshdance** [comment]
From the status page - "[Some Builds with Edge Functions and Middleware Failing](https://www.vercel-status.com/incidents/9pyk5640w5r7)
Resolved - From 15:24 - 15:54 UTC, some new builds experienced build failure due to an issue with edge functions and middleware. This issue was identified by one of our upstream providers, and they internally investigated and fixed the issue. New builds with edge functions and middleware are now building successfully again."

https://www.vercel-status.com/

So just wait, they will get it fixed.

**Comment by pedrovrima** [comment]
Can confim it is back working

Em seg., 8 de abr. de 2024 às 13:13, Joshua Dance ***@***.***>
escreveu:
