### ISSUE TITLE
Fetch not monkey-patchable on Vercel Edge Runtime

### ISSUE THREAD

**Issue by lforst** [zeit/now#10814]
Observability tools rely heavily on monkeypatching fetch to measure and trace the duration of I/O.

For some reason fetch can't be patched on the Vercel Edge runtime. Any attempts to do so make it seem like the global object is frozen in a way that will prevent `global.fetch` from being set.

 Based on this comment by the CF workers tech lead it should technically be possible https://news.ycombinator.com/item?id=29540018#:~:text=monkey%2Dpatch%20%60fetch()%60. 

Would it be possible to open up the fetch implementation in the Vercel edge runtime to be monkey-patchable?

**Comment by trek** [comment]
Hi @lforst,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
