### ISSUE TITLE
How do you use Deploy hooks with Ignore Build Step?

### ISSUE THREAD

**Issue by Nedimko123** [zeit/now#10812]
Currently my project has **Ignored Build Step** set to **Don't build Anything** and whenever I trigger a **DeployHook** or when I push it tries to build but fails because of that Ignored Build Step.

What I want:

-  Don't build or deploy on push or commit
- Only Build when I trigger a Deploy Hook

**Comment by Tobi-mmt** [comment]
I had the same problem. Looks like there is no solution for that.
Maybe this helps: https://github.com/orgs/vercel/discussions/2038

**Comment by trek** [comment]
Hello @Nedimko123,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.

**Comment by donnersvensson** [comment]
Has anybody found a solution to this problem? We are trying to make tinaCMS work with Next and Vercel. Everytime we save something there, a new commit is pushed to the repo which triggers a deploy. It would be nice to have the ignored build step for our production branch but not build if we trigger the deploy hook

//EDIT:
I just found it on vercel.community. if you put a vercel.json into your project with
`{
  "git": {
    "deploymentEnabled": {
      "main": false
    }
  }
}`
it will ingnore pushes to the repo, but not the deploy hook.

https://vercel.community/t/deploy-hook-only-in-ignored-build-step/1188

**Comment by boreens** [comment]
Deploy hook imo should ignore build step settings that are defined in vercel ui and trigger the build. What is the reason for current behaviour?
