### ISSUE TITLE
Change the status code to 404 for not found deployments

### ISSUE THREAD

**Issue by mericozkayagan** [zeit/now#10828]
https://github.com/vercel/vercel/blob/9472c22bf7192da264bcff8184ab651d3e726a49/packages/cli/src/util/alias/create-alias.ts#L79

When i am trying to access and alias not configured in my domains for example asd.mydomain.com and I have a Preview Deployment Suffix named mydomain.com, I get the following error
<img width="769" alt="image" src="https://github.com/vercel/vercel/assets/96292408/b46e23c4-1265-456e-bace-d827f8119ce0">
But in the Inspect section i see the following status code which is 204. When the alias is not found i think the following status code should be 404.

Here is the 204 request 
Request URL: https://asd.mydomain.com/cdn-cgi/rum?
Request Method: Post
Status Code: 204

**Comment by trek** [comment]
Hi @mericozkayagan,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
