### ISSUE TITLE
Could not find module for Gatsby/TypeScript site

### ISSUE THREAD

**Issue by datawookie** [zeit/now#10824]
Hi,

I posted this [question on StackOverflow](https://stackoverflow.com/questions/77433377/could-not-find-module-for-gatsby-typescript-site-on-vercel) a few days ago but did not receive any response. I'm hoping that there is a quick and easy answer to this. The site works fine on Netlify. However, I want to use Vercel rather than Netlify and there's this minor problem with getting the site to build on the platform. Full source code for the project is available at link below.

I have a test Gatsby site. The source code is [here](https://gitlab.com/datawookie/gatsby-whimsyweb/-/tree/18-vercel). I have converted my `gatsby-node.js` to `gatsby-node.ts`. All of the JavaScript files below `src/` have also been converted to TypeScript.

The site works fine in the following scenarios:

- local development server;
- local production server (build then serve); and
- deploying on Netlify (live site is [here](https://gatsby-whimsyweb-17-babel.netlify.app/1.2/)).

However, when I deploy to Vercel I get an error. I get the same error when I try to build locally using `vercel build`.

```
gatsby-node.ts:4:29 - error TS2306: File 'gatsby-whimsyweb/gatsby-node.ts.__vercel_builder_backup__.ts' is not a module.
4 import * as gatsbyNode from './gatsby-node.ts.__vercel_builder_backup__.ts';
gatsby-node.ts:6:15 - error TS2306: File 'gatsby-whimsyweb/gatsby-node.ts.__vercel_builder_backup__.ts' is not a module.
6 export * from './gatsby-node.ts.__vercel_builder_backup__.ts';
```

This error makes sense: there is no file called `gatsby-node.ts.__vercel_builder_backup__.ts`. But there is a file generated called `gatsby-node.ts.__vercel_builder_backup__.js` (the difference being in the final extension). Either I'm generating a file with the wrong extension (in which case, how do I change that?) or I'm trying to import a file with the wrong extension (again, how do I change this?).

An earlier (JavaScript version) of the site worked fine on Vercel too. It's only since trying to convert to TypeScript that things have gone awry.

In the interests of full disclosure, I don't know an awful lot about JavaScript or TypeScript. I am working on this project with the intention of learning.

I have scoured StackOverflow for help. [This post](https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam) was helpful to resolve an earlier issue. But now I'm stuck and have not made any progress for a while.

**Comment by TooTallNate** [comment]
Hi there, I would like to take a look to try and help, but the GitLab repo seems to not be public.

**Comment by datawookie** [comment]
Hi @TooTallNate, you are 100% correct. Thanks for pointing this out. I was assuming that it was public already. Just made the change. Can you access it now?

**Comment by TooTallNate** [comment]
Hmmm… I didn't do anything special at all. Just cloned the repo and ran `vercel deploy`. Seemed to deploy successfully for me: https://gatsby-whimsyweb-five.vercel.app/

**Comment by datawookie** [comment]
Hi @TooTallNate, ah, right. Sorry, the original link above referenced a specific branch. Would you mind please trying again with the content of the branch `18-vercel`? That's where I'm having the problem. Thanks, Andrew.

**Comment by TooTallNate** [comment]
The problem is that you are using `exports.createPages` (CommonJS syntax), but TypeScript expects `export function createPages` (Module syntax).

**Comment by datawookie** [comment]
Thank you, @TooTallNate. Made the change and now working 100%. Really appreciate your input. :+1:
