### ISSUE TITLE
Vercel Edge Runtime Source Maps not accessible for 3rd party consumption

### ISSUE THREAD

**Issue by lforst** [zeit/now#10829]
I don't have full insights into this on Vercel's side so some of the following are assumptions.

## Context

Third-party tools like Sentry would like to access source maps for a running application so that stack traces for logged errors can be source-mapped.

## Problem

Since functions deployed on the Vercel Edge Runtime are bundled in an additional step opaquely, there is no way for any SDKs to pick up the source maps to upload them to third-party services. This will make it impossible to trace the errors back to their original location. Currently stack traces look like this:

```
Error: Edge Stack Traces
    at (vc/edge/function:122:5661)
    at (vc/edge/function:125:10587)
    at (vc/edge/function:122:5622)
    at (vc/edge/function:147:11182)
    at (vc/edge/function:147:9157)
    at (vc/edge/function:147:11007)
}
```

## Solution brainstorm

- No additional bundling steps after building a Next.js application. (I don't know if feasible)
- Expose source maps to the runtime via some global variable. (probably would introduce too much memory overhead)
- Expose sourcemaps on a separate service (like S3) behind an auth token. Out of these, this is the approach that makes the most sense.

**Comment by jenwoodson** [comment]
We're running into this issue and would like to be able to see stacktraces/source maps from the edge runtime in Sentry for our NextJS projects running on Vercel. The same error pushed from my local environment has more helpful information available vs. when pushed from our Vercel environments.

Vercel:
<img width="958" alt="Screen Shot 2023-12-19 at 11 25 57 AM" src="https://github.com/vercel/vercel/assets/91624327/f656f093-59ca-4b63-8a0b-af41fdd12bde">

local:
<img width="797" alt="Screen Shot 2023-12-19 at 11 25 17 AM" src="https://github.com/vercel/vercel/assets/91624327/79ac4e39-3f72-4f52-a129-59e245ab7169">

**Comment by johnislarry** [comment]
Hello!  I'm here to say that unsymbolicated stacks from edge are still an issue, and it would be really great if someone found a way to get sourcemaps for prod builds (assuming that is the problem).

**Comment by charanjit-singh** [comment]
Any updates?

**Comment by jstjoe** [comment]
Can we get a sign about the future of this gap? Blink twice if it's never happening?

**Comment by trek** [comment]
Hi @lforst,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.

**Comment by charanjit-singh** [comment]
This is not completed from any angle.

**Comment by lforst** [comment]
Posted in community here: https://vercel.community/t/vercel-edge-runtime-source-maps-not-accessible-for-3rd-party-consumption/1206
