### ISSUE TITLE
Analytics Filtering

### ISSUE THREAD

**Issue by BalduinB** [zeit/now#10867]
I have observed this "Bug" a while now, maybe this is a feature doe.

When I am on the analytics page of my landing-page project and **filter for a custom event** "registration" and the **switch the project** to eg. the customer login project, the **filter is not getting cleared**, resulting in a analytics page without any event, because I **don't have this custom analytics event in that project**.

![Bildschirmfoto 2023-11-22 um 13 44 48](https://github.com/vercel/vercel/assets/43539017/8a5536d1-4d88-4bb2-8ec0-87a0f2c6fb00)

As said I don't know if that is a feature or if it is an easy fix to check the current applied filters exist in the project that got switched to.

**Comment by trek** [comment]
Hi @BalduinB,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
