### ISSUE TITLE
can't change namesilo name server to 'ns1.vercel-dns.com' or 'ns2.vercel-dns.com'

### ISSUE THREAD

**Issue by pkpakau** [zeit/now#10876]
### Discussed in https://github.com/vercel/vercel/discussions/4414

<div type='discussions-op-text'>

<sup>Originally posted by **liulei237136** May 19, 2020</sup>
  Hi,everybody.
  I bought  a domain in namesilo.com, but when I wanted to change its default name servers to "ns1.vercel-dns.com' and “ns2.vercel-dns.com” of vercel, namesilo.com show some errors as following:
 " There was a problem with the NameServers you entered for the following domains:
   xxxxxxx.com
   This is likely caused by the entered NameServers not being created yet. Please check the spelling of the NameServers you entered as well as checking to make sure they have been created at the applicable registry."
  so anybody know what's wrong with it ? I change the name servers of namesilo.com to other name servers such as "ns1.bluehost.com", it works and no errors.
  thanks.</div>

**Comment by trek** [comment]
Hi @pkpakau,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
