### ISSUE TITLE
v0 "Something went wrong" after deleting a project fork

### ISSUE THREAD

**Issue by wissam6** [zeit/now#10962]
**Steps to reproduce:**

1. Navigate to https://v0.dev/
2. Generate a Project
3. Fork the Project
4. Delete the forked project

You will first get a "Something went wrong" message on the screen, which will then change to "Application error: a client-side exception has occurred (see the browser console for more information)." with a couple of errors in the console:

![image](https://github.com/vercel/vercel/assets/66859389/c24452bb-5ac1-4c86-9ecd-3bd2bf985aa6)

**Comment by trek** [comment]
Hello @wissam6,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
