### ISSUE TITLE
Faults in content in blog Introducing the Vercel Platforms Starter Kit

### ISSUE THREAD

**Issue by bikrantlabs** [zeit/now#10974]
In the blog [Introducing the Vercel Platforms Starter Kit](https://vercel.com/blog/platforms-starter-kit), just below the **Multi-tenant apps in days, not months** section, we can see random lines of text:
_or undefined. Here's an example code snippet demonstrating how to use it within Next.js:
In the above example, we import the geolocation helper from @vercel/edge. We t_

Which seems to be included from guides [How can I use geolocation IP headers?](https://vercel.com/guides/geo-ip-headers-geolocation-vercel-functions).

**Comment by trek** [comment]
Hi @bikrantlabs,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
