### ISSUE TITLE
Show a nice page after getting access to GCP

### ISSUE THREAD

**Issue by matheuss** [zeit/now#11]
1. `now gcp login`
2. You'll see this:
<img width="45%" src="https://user-images.githubusercontent.com/4721750/28002443-96932f84-650b-11e7-9eac-77e4866c199c.png">
3. After clicking on `cancel` or `allow`, you'll see this:
<img src="https://user-images.githubusercontent.com/4721750/28002460-b798d724-650b-11e7-8672-492ea235564b.png">

We can show anything there, even redirect the user to zeit.co/sth

**Comment by leo** [comment]
This issue was moved to zeit/now-cli#772
