### ISSUE TITLE
Whole page breaks when an image is clicked

### ISSUE THREAD

**Issue by ericjypark** [zeit/now#11006]
https://vercel.com/docs/projects/environment-variables?utm_medium=docs&utm_source=next-site&utm_campaign=next-website

Clicking on **any image** in the Vercel website leads to an error. 

https://github.com/vercel/vercel/assets/80627536/6bb86c15-01fa-4779-833e-9b3db8d2d6e4

<img width="1157" alt="스크린샷 2024-01-02 오후 3 15 09" src="https://github.com/vercel/vercel/assets/80627536/c515e40a-e6a7-4fa1-9bad-b66f3a529b4b">

**Comment by sourabpramanik** [comment]
Hey @Bokdol11859 may I know which browser you were using? I tried in chrome but couldn't reproduce

**Comment by ericjypark** [comment]
The video was recorded in Chrome, but the bug seems to be fixed now.

Images were "clickable" back then, meaning some action was triggered when images were clicked, but they don't seem to be clickable anymore.
