### ISSUE TITLE
Vercel dashboard bug: Client-side exception when domain contains wildcard

### ISSUE THREAD

**Issue by MatLegat** [zeit/now#11020]
Reporting a bug here as the bug report link indicated on this GitHub is broken (`https://vercel.com/support/request` - 404)

When opening the Vercel dashboard on Firefox 121.0 (macOS 14.1), after logging in i cannot open my organization dashboard.
The application only displays a blank page with the message `Application error: a client-side exception has occurred (see the browser console for more information).`

Checking the console, I found that the relevant error is the following:
`Error message: URL constructor: https://*.xpert-develop.binamik.com.br/ is not a valid URL.`

Somewhere in the dashboard code, it is attempting to generate a link via a URL constructor with the domain, even though it is a valid wildcard domain ([relevant Vercel doc page](https://vercel.com/blog/wildcard-domains))

Print from screen with open console:
<img width="1727" alt="image" src="https://github.com/vercel/vercel/assets/11902693/e860f155-39e4-437e-8085-5dc18393cf57">

**Comment by Arthur-Barros** [comment]
+1 I have the same problem

**Comment by MatLegat** [comment]
Solved via Vercel support (case 00187550)
