### ISSUE TITLE
🐞 Links on domain configuration card have [param names] rather than values

### ISSUE THREAD

**Issue by rorhug** [zeit/now#11037]
Do you guys know how to use Next.js?

<img width="622" alt="Screenshot 2024-01-12 at 11 33 38" src="https://github.com/vercel/vercel/assets/544628/0827f891-7fa2-421f-8aaf-8de1f7c5b85a">

**Comment by trek** [comment]
Hi @rorhug,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)

**Comment by rorhug** [comment]
still not fixed
