### ISSUE TITLE
[BUG] Could not parse the patch version in go.mod file 

### ISSUE THREAD

**Issue by zyxkad** [zeit/now#11063]
In golang 1.21, the go version inside `go.mod` is updated to `major.minor.patch`, e.g. `go 1.21.1`

However, vercel only support `major.minor` pattern so far.

So when I deploying with go 1.21.1, it give my the following warn:
```
Warning: Unknown Go version in /vercel/path0/go.mod
```

---

PS: when I open <https://vercel.com/support/request> for report, it gave me 404

**Comment by EndangeredMassa** [comment]
Thanks for the report, @zyxkad! Can you point me to where you found the link to https://vercel.com/support/request so that I can track down that 404?

**Comment by zyxkad** [comment]
<img width="1512" alt="Screenshot 2024-01-18 at 10 02 26" src="https://github.com/vercel/vercel/assets/91082411/44be5a00-129f-4ac1-8adb-ea708e1fb0bd">

Yes, just the Bug Report button

**Comment by leafmoes** [comment]
I also encountered this problem. The go version parsing failed, and it seemed to be re-downloaded when building from the cache. The build cache also seemed to be invalid.
