### ISSUE TITLE
Unhandled Promise Rejection when using node-fetch, Shopify remix app with shopify api v9 deployed to vercel

### ISSUE THREAD

**Issue by anhdd-kuro** [zeit/now#11069]
I am currently working on a Shopify custom app built with the Remix template and deployed on Vercel. Initially, it ran smoothly with Remix version 2.5.1 and Shopify API version 8.1. However, upon updating to [Shopify API version 9](https://github.com/Shopify/shopify-api-js/blob/main/packages/shopify-api/docs/migrating-to-v9.md#migrating-to-v9), the application started crashing when making any API calls using the fetch API. Below is the detailed log:

```
Unhandled Promise Rejection 
{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: First parameter has member 'readable' that is not a ReadableStream.",
"reason":
{"errorType":"TypeError","errorMessage":
"First parameter has member 'readable' that is not a ReadableStream.",
"stack":["TypeError: First parameter has member 'readable' that is not a ReadableStream.","   
 at assertReadableStream (/var/task/node_modules/.pnpm/web-streams-polyfill@3.3.2/node_modules/web-streams-polyfill/dist/ponyfill.js:466:19)","    
at convertReadableWritablePair (/var/task/node_modules/.pnpm/web-streams-polyfill@3.3.2/node_modules/web-streams-polyfill/dist/ponyfill.js:4038:9)","    
at ReadableStream.pipeThrough (/var/task/node_modules/.pnpm/web-streams-polyfill@3.3.2/node_modules/web-streams-polyfill/dist/ponyfill.js:4122:29)","    
at fetchFinale (node:internal/deps/undici/undici:9584:56)","    
at mainFetch (node:internal/deps/undici/undici:9476:9)","    
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: First parameter has member 'readable' that is not a ReadableStream.","    
at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)","    
at process.emit (node:events:529:35)","    
at emit (node:internal/process/promises:149:20)","    
at processPromiseRejections (node:internal/process/promises:283:27)","    
at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
```

here is the dependencies

```json
  "dependencies": {
    "@prisma/client": "5.7.1",
    "@remix-run/css-bundle": "^2.5.0",
    "@remix-run/dev": "2.5.1",
    "@remix-run/node": "2.5.1",
    "@remix-run/react": "2.5.1",
    "@remix-run/serve": "2.5.1",
    "@shopify/app": "3.53.1",
    "@shopify/cli": "3.53.1",
    "@shopify/polaris": "12.10.0",
    "@shopify/polaris-icons": "^8.0.0",
    "@shopify/shopify-api": "9.0.2",
    "@shopify/shopify-app-remix": "2.2.0",
    "@shopify/shopify-app-session-storage-prisma": "2.0.3",
    "@vercel/remix": "2.5.1",
    "isbot": "4.4.0",
    "prisma": "5.7.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-phone-number-input": "3.3.9",
    "remix-utils": "7.5.0",
    "usehooks-ts": "2.9.5"
  },
```

Please assist in identifying and resolving this issue. Thank you.

**Comment by andyvanosdale** [comment]
Does this break locally or only when deployed to Vercel? I would recommend checking locally first, and I suspect that it will break locally. Then you can debug and see why the promise rejection is not being handled when using the updated Shopify module.

**Comment by anhdd-kuro** [comment]
@andyvanosdale unfortunately , this only break when deployed to Vercel 
The error only occur if and try to call api using fetch , the static page have no problem
I will try netify to see is this enviroment problem

**Comment by andyvanosdale** [comment]
Vercel works well with Node’s fetch. I would dig in deeper. Otherwise, practically all projects deployed to Vercel would be broken. Check that the update doesn’t require a specific Node version and you have that set accordingly for Vercel.
________________________________

**Comment by anhdd-kuro** [comment]
@andyvanosdale 
I have created [simple reproduction](https://github.com/anhdd-kuro/test-vercel-app)
It's work fine at route `/products_2` which directly use fetch , but failed at `/products`
Maybe this is [shopify-app-template-remix](https://github.com/Shopify/shopify-app-template-remix) 's problem but I can't explain why it's work normally at local
According to the logs , it passed authenticate

![スクリーンショット 2024-01-29 12 28 05](https://github.com/vercel/vercel/assets/13819766/1cc8a454-a533-4026-8bd7-ba9329d9335b)

**Comment by andyvanosdale** [comment]
I'm not sure why it may be working locally vs in Vercel. However, I do see that Shopify has called out that the v9 update changed how they use fetch moving forward.

See:
* [Migration Notes](https://github.com/Shopify/shopify-api-js/blob/main/packages/shopify-api/docs/migrating-to-v9.md#changes-to-runtime-adapters)
* [Docs](https://shopify.dev/docs/api/shopify-app-remix#shopify-app)

**Comment by anhdd-kuro** [comment]
I'm using their latest template and checked the docs, but I did not find any problems. 
I said it was working locally, but it is actually hosted on Cloudflare

**Comment by andyvanosdale** [comment]
The docs and what I posted about are clearly talking about using that template with Node and what you need to do to resolve it.
________________________________

**Comment by anhdd-kuro** [comment]
@andyvanosdale 
It appears that I am not the only person facing this issue! 
Please take a look at the problem reported in the Shopify Remix team mentioned above. 
Currently, they are addressing the issue by switching the deploy service to Heroku, but this could potentially prove that problems is in the Vercel environment. 
Remix team has already responded, stating that they will investigate. However, until then, we have no choice but to change the service or keep running in old version which have many deprecated thing

**Comment by andyvanosdale** [comment]
I would imagine you are not the only one experiencing this issue. I suspect Shopify did not test their product throughly (for example, in a Vercel hosted environment). I don’t work for Vercel. I would recommend pushing on the Shopify team to fix their issue.
________________________________

**Comment by anhdd-kuro** [comment]
My bad ! I thought you are on vercel team

**Comment by andyvanosdale** [comment]
No worries! I would remember that nothing on Vercel’s side has changed. This was Shopify’s own doing. The Shopify Remix code is open source, so the library could be further debugged by any software developer.
________________________________

**Comment by kenju** [comment]
@anhdd-kuro 

> it ran smoothly with Remix version 2.5.1 and Shopify API version 8.1. 

Can you share the `dependencies` from `package.json` that worked by having `shopify-api: 8.1` to see which versions you used for other peer dependencies

The error basically says that the parameters passed does not support [Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API). This is achieved by [this polyfill](https://github.com/MattiasBuelens/web-streams-polyfill/blob/master/src/lib/readable-stream.ts#L445-L455), which vercel/vercel installs [here](https://github.com/vercel/vercel/blob/main/pnpm-lock.yaml#L15189).

> The usage of Streams hinges on making responses available as streams. For example, the response body returned by a successful [fetch request](https://developer.mozilla.org/en-US/docs/Web/API/fetch) is a [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) that can be read by a reader created with [ReadableStream.getReader()](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/getReader).

**Comment by anhdd-kuro** [comment]
@kenju 
here's dependencies that working with `shopify-api: 8.1`

```json
"dependencies": {
    "@date-fns/utc": "1.1.1",
    "@dnd-kit/core": "6.1.0",
    "@dnd-kit/sortable": "8.0.0",
    "@formkit/auto-animate": "0.8.1",
    "@hookform/resolvers": "3.3.4",
    "@karabiner-inc/kbc-shared-components": "0.4.5",
    "@prisma/client": "5.8.1",
    "@remix-run/dev": "2.5.1",
    "@remix-run/node": "2.5.1",
    "@remix-run/react": "2.5.1",
    "@remix-run/serve": "2.5.1",
    "@shopify/app": "3.54.0",
    "@shopify/cli": "3.54.0",
    "@shopify/plugin-cloudflare": "3.54.0",
    "@shopify/polaris": "12.11.2",
    "@shopify/polaris-icons": "8.1.0",
    "@shopify/shopify-api": "8.1.1",  // Shopify
    "@shopify/shopify-app-remix": "2.2.0",  // Shopify remix
    "@shopify/shopify-app-session-storage-prisma": "2.0.3",
    "@tanstack/react-table": "8.11.7",
    "@vercel/remix": "2.5.1",
    "date-fns": "^3.3.1",
    "isbot": "4.4.0",
    "lodash": "4.17.21",
    "prisma": "5.8.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "7.49.3",
    "react-loading-skeleton": "3.3.1",
    "react-select": "5.8.0",
    "react-toastify": "10.0.4",
    "remix-hook-form": "4.0.1",
    "remix-utils": "^7.5.0",
    "zod": "3.22.4"
  },
```

**Comment by anhdd-kuro** [comment]
Solve by [this comment](https://github.com/Shopify/shopify-app-template-remix/issues/500#issuecomment-1957844634)
