### ISSUE TITLE
Getting the same list of projects again when i click load more

### ISSUE THREAD

**Issue by chocoscoding** [zeit/now#11074]
When I come to my dashboard, I see all my projects.
Then I click **load more**, and I get an additional list of the same projects.
So, I then have each project appear twice.

https://github.com/vercel/vercel/assets/66442194/31bb79d5-8725-40a2-86bb-dc168657fd51

**Comment by trek** [comment]
Hi @chocoscoding,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
