### ISSUE TITLE
Locked out of Pro account during signup - error: This user account is blocked

### ISSUE THREAD

**Issue by componentscience** [zeit/now#11075]
We signed up for a Vercel Pro account and it was instantly deactivated during signup - we've never used Vercel. 

Perhaps it's related to our domain name extension? For our accounts we use Proton email addresses with their custom domain name feature. Our domain name uses a newer '.xyz' extension because it best represents our work. We use this extension everywhere, and have never had any issues until now.

During signup we successfully completed an email verification, and Vercel even sent us follow up emails about various features. But when trying to login it says "This user account is blocked" without any explanation. There is no way to contact Vercel because the support form requires an email address, which is blocked.

**Comment by andyvanosdale** [comment]
From [How to Get Vercel Support](https://vercel.com/guides/how-to-get-vercel-support):

> Login — If you are unable to log in or experience difficulties during registration, please email [registration@vercel.com](mailto:registration@vercel.com) and include the details of the project you are looking to deploy with Vercel. To protect against platform abuse, Vercel employs multiple layers of security and verification during the account signup process.

**Comment by componentscience** [comment]
Been there done that. No response. Vercel needs to know they are blocking well-intended customers for no apparent reason, without any explanation.

**Comment by trek** [comment]
Hi @componentscience,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
