### ISSUE TITLE
my account was block

### ISSUE THREAD

**Issue by svipwing** [zeit/now#11085]
Hello, my account has been blocked due to traffic exceeding the limit. I have taken new protective measures to ensure that there will be no more traffic exceeding the limit. I hope you can lift the ban on my account: 3260130869@qq.com
I would be extremely grateful if the ban could be lifted

**Comment by andyvanosdale** [comment]
I would recommend reaching out to [Vercel Support](https://vercel.com/help). Use the form at the bottom to reach their customer service team.

**Comment by Fgaoxing** [comment]
@zeke

**Comment by EndangeredMassa** [comment]
@andyvanosdale is right. Please reach out to [Vercel Support](https://vercel.com/help).
