### ISSUE TITLE
cannot access any website hosted by vercel

### ISSUE THREAD

**Issue by Khalilsqu** [zeit/now#11084]
### Discussed in https://github.com/vercel/vercel/discussions/11083

<div type='discussions-op-text'>

<sup>Originally posted by **Khalilsqu** January 23, 2024</sup>
### Question

Dears

I cannot access any website hosted by Vercel. However, when I enable VPN, things work fine.

without VPN I get the error message

```
This site can’t be reached
vercel.com took too long to respond.

Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())
ERR_TIMED_OUT
```

I live in Oman

I tried visiting https://www.shadcn-svelte.com/ @huntabyte,
and 
https://nextui.org/

but nothing is working except if I use a VPN, but VPN makes my internet very slow
</div>

**Comment by andyvanosdale** [comment]
You'll need to trace the route to Vercel from your computer to see where the packets are getting dropped. There is likely some firewall in place along the route blocking it.

**Comment by trek** [comment]
Hi @Khalilsqu, 

We have a guide for addressing this very issue: https://vercel.community/t/resolving-ip-blocking-issues/171

**Comment by Khalilsqu** [comment]
thanks @trek
