### ISSUE TITLE
Build failed without any error messages

### ISSUE THREAD

**Issue by fernandoonextech** [zeit/now#11124]
<img width="1262" alt="Screenshot 2024-02-05 at 3 28 34 PM" src="https://github.com/vercel/vercel/assets/103987626/058cda6f-4b28-43ca-a8d4-c60bbf9ed072">

As shown on the screenshot, the deployment failed with no error messages being shown on the log.

**Comment by trek** [comment]
Hi @fernandoonextech,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
