### ISSUE TITLE
Speed Insights conflicting documentation re import - Nuxt

### ISSUE THREAD

**Issue by moshetanzer** [zeit/now#11132]
Hi,

On the Speed Insights page when selecting Nuxt the import you give is 

`import { SpeedInsights } from "@vercel/speed-insights/nuxt`

However, in the docs the import that you give for nuxt is 

`import { SpeedInsights } from "@vercel/speed-insights/vue`

Is there any diffrence between the two? This should surely be corrected!

**Comment by trek** [comment]
Hi @moshetanzer,

Hi <name>! We're in the process of migrating to our new community platform. If you're still seeing this issue, can head over to https://vercel.community and ask there? Thank you!
