### ISSUE TITLE
`vercel` cli has not option to update existing values

### ISSUE THREAD

**Issue by bombillazo** [zeit/now#11130]
Hello. We use the vercel cli in our CICD platform and we've noticed that using `vercel env add` command will fail one existing secrets. It would be ideal if the CLI had an `--update` flag to make the vercel CLI overwrite the existing env secret rather than failing with an error. This will ensure we set the most recent secrets and not keeping around any old values.

**Comment by hussamkhatib** [comment]
While not ideal, you could remove the env variable `vercel env rm` and then add the new value.

**Comment by bombillazo** [comment]
We've programmed some commands for that, but its not ideal and introduces more room for errors and intermediate states if something fails. A simple update flag would be the best way to handle it for our case.

**Comment by mountainash** [comment]
I also have the same problem... it would be great is there was a `--yes` argument (that is also used on `env pull` and `env rm` to skip the confirmation/warning that the variable already exists.

**Comment by mountainash** [comment]
I started looking into raising a PR to add this functionality and found that the [Vercel API endpoint for `create`](https://vercel.com/docs/rest-api/endpoints/projects#create-one-or-more-environment-variables) does allow for overriding if the KEY already exists with an `upsert` param.

There is also (for interest) [another endpoint for "editing" an existing env var when it exists](https://vercel.com/docs/rest-api/endpoints/projects#edit-an-environment-variable), but you need to know it's ID, not the envvar name/key (so you need to do a map first.

So it shouldn't be too much extra to change this in Vercel CLI.

**Comment by mountainash** [comment]
What's interesting/strange/confusing is that when you attempt to `vercel env add` with an existing key, the CLI error is:
> Error: Another Environment Variable with the same Name and Environment exists in your project. Remove it or choose a different Name or Environment.

Yet, I can't find this error message in the CLI codebase (this project), I thought maybe the API is returning this error, yet trying to create a new envar Key that already exists returns the following error from the API (https://api.vercel.com/v10/projects/${projectID}/env):
```json
{
  "error": {
    "code": "ENV_CONFLICT",
    "message": "A variable with the name `API_URL` and target `preview` already exists",
    "key": "key",
    "envVarKey": "API_URL"
  },
  "failed": [
    {
      "error": {
        "code": "ENV_CONFLICT",
        "message": "A variable with the name `API_URL` and target `preview` already exists",
        "key": "key",
        "envVarKey": "API_URL"
      }
    }
  ]
}
```

I'll keep digging to see where the CLI's error is coming from (could be using an older endpoint)...

### Update

Endpoint v9 is returning the error below when trying to set an existing env Key. v9 also doesn't allow the "upsert" para... so CLI will need updating to use v10 of this endpoint.

```json
{
  "error": {
    "code": "ENV_ALREADY_EXISTS",
    "message": "Another Environment Variable with the same Name and Environment exists in your project. Remove it or choose a different Name or Environment.",
    "key": "API_URL",
    "configurationId": null,
    "target": [
      "preview"
    ]
  }
}
```

### Update 2

CLI is using v8:
[const url = `/v8/projects/${projectId}/env`;](https://github.com/vercel/vercel/blob/8a16e8eb6531d354a4708a778345f3fb0262fc0e/packages/cli/src/util/env/add-env-record.ts#L29-L30)

**Comment by bombillazo** [comment]
Awesome work!
