### ISSUE TITLE
Typo in docs?

### ISSUE THREAD

**Issue by GeoBrodas** [zeit/now#11194]
![image](https://github.com/vercel/vercel/assets/68821192/2a9c44a5-28ae-4150-9941-cee094d4eddc)
 
Isn't it supposed to be `app/api/og/route.tsx`

**Comment by trek** [comment]
Hi @GeoBrodas,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
