### ISSUE TITLE
vercel@33.5.2 partial-prerendering server execution

### ISSUE THREAD

**Issue by zer0dt** [zeit/now#11196]
On 02/22 I noticed a spike in serverless execution on a vercel hosted project. It specifically started at 11:00am 02/22 which is when vercel@33.5.2 was released.

Can we get an explanation on what "/_next/postponed/resume/" is doing and how it can be optimized? 

<img width="660" alt="Screenshot 2024-02-23 220603" src="https://github.com/vercel/vercel/assets/85325800/3462e2f0-def3-489f-851d-4282724d7162">

**Comment by trek** [comment]
Hi @zer0dt,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
