### ISSUE TITLE
Incorrect semicolon on /home

### ISSUE THREAD

**Issue by schjndler** [zeit/now#11222]
https://vercel.com/home

Under the CTA, "Ready to deploy?", above the Footer on the Left is a semicolon to much.

<img width="438" alt="Screenshot 2024-03-04 at 12 29 03" src="https://github.com/vercel/vercel/assets/92883410/6a53f768-8ebd-4b59-8220-db0d8048992a">

**Comment by Possibly-coder** [comment]
@schjndler Does this issue still persist? Cuz its not visible on the attached url

**Comment by trek** [comment]
Hi @schjndler,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
