### ISSUE TITLE
Sharp.js v0.33 not working in combination with pnpm

### ISSUE THREAD

**Issue by ZoranRavic** [zeit/now#11220]
Starting with version `0.33.0` `sharp` made a [major overhaul of installation](https://github.com/lovell/sharp/issues/3750) where they changed how prebuilt binaries are installed.

This introduced an issue on Vercel where if you are using `pnpm` then the prebuilt binaries for `sharp 0.33.x` wont be included in the deployment build and you'll end up with this error message:

```
Error: Could not load the "sharp" module using the linux-x64 runtime
ERR_DLOPEN_FAILED: libvips-cpp.so.42: cannot open shared object file: No such file or directory
Possible solutions:
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
  or
    npm install --force @img/sharp-linux-x64
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/var/task/node_modules/.pnpm/sharp@0.33.0/node_modules/sharp/lib/sharp.js:85:9)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at exports.b (/opt/node-bridge/chunk-5UAC7W5H.js:1:1142)
    at /opt/node-bridge/bridge-server-BGIDXK2J.js:1:1443
    at Function.Re (/opt/node-bridge/bridge-server-BGIDXK2J.js:1:1809)
    at e.<computed>.L._load (/opt/node-bridge/bridge-server-BGIDXK2J.js:1:1413)
    at Module.require (node:internal/modules/cjs/loader:1225:19) {
  page: '/api/compress'
}
```

As a workaround you can downgrade `sharp` to `0.32.6`.

Alternatively you can use `npm` instead of `pnpm`, which will allow you to continue using the latest versions of `sharp`.

Hopefully someone from Vercel will see this and find a way to resolve the issue with using `pnpm`.

**Comment by jpwallace22** [comment]
I'm having the same problem with YarnV4 as well.

**Comment by renenielsendk** [comment]
I have the same error 😢

**Comment by mwawrusch** [comment]
Can't believe this is still an issue. Just ran into this with nextjs 15.0.0-rc1 - which is a fresh install of turbo monorepo.

**Comment by jpwallace22** [comment]
> Can't believe this is still an issue. Just ran into this with nextjs 15.0.0-rc1 - which is a fresh install of turbo monorepo.

@mwawrusch I was able to solve by ensuring that vercel was building with corepack enabled using `ENABLE_EXPERIMENTAL_COREPACK = 1` in my envs.

**Comment by mwawrusch** [comment]
@jpwallace22  will give it a try, thanks

**Comment by mwawrusch** [comment]
@rauchg This creeps up over and over again for the last few months for us and apparently others in different projects, with solutions sometimes stopping to work. It's the ONLY issue I had with vercel in the last year but it's one that's particularly bad because it does not stop a build process. I feel like this needs more love and attention from the vercel team. 


@jpwallace22 
Gave it a try, but still doesn't work. btw, using npm, and the next.config fix from the other thread. Do you mind posting your package.json with the version of sharp and your next.config? Thank you

**Comment by mwawrusch** [comment]
Another tip - if you use a monorepo AND you use storybook in it's latest version AND you use NPM , they lock sharp into ^0.33.3, which then happens to mess things up with your other installs. To solve this, include an override into your package,json like this:

```
,
  "overrides": {
    "sharp": "0.30.4"
  }
```

**Comment by trek** [comment]
Hey all,

Is anyone able to provide us a repo with a simple reproduction?

I've tried a matrix of a basic build script[1] invoking `sharp` manually with:

* `npm@latest`
* `pnpm@latest`

against

* `sharp@0.33.0`
* `sharp@0.32.6`
* 


and a basic use of `react/image` in a matrix of 
 
`next@14.2.6`
`next@15.0.0-rc.0` 

against 

* `sharp@0.33.0`
* `sharp@0.32.6`

all on `pnpm@latest`

And get no errors.

[1] the script:

```
const sharp = require("sharp");

async function resizeImage() {
  try {
    await sharp("sample.png")
      .resize({
        width: 150,
        height: 97
      })
      .toFormat("jpeg", { mozjpeg: true })
      .toFile("public/sample-resized-compressed.jpeg");
  } catch (error) {
    console.log(error);
  }
}

resizeImage();
```

**Comment by ZoranRavic** [comment]
Hi @trek, it seems to me that it is fixed with newer versions.

I can still reproduce it with my old branch, so I was able to find that the problem was in next.js.

Testing with `next@14.1.0` (which I used back then) I still get the error - confirmed with `pnpm@latest`, several versions of `sharp@0.33.x`, and both `node@18` (which I used on vercel back then) and `node@20`.

Now testing with `next@14.2.6` and different versions of other libs I couldn't reproduce the issue.

It appears that the issue was fixed in one of the next.js versions in between.

A few more tests reveal that `next@14.1.3` still had this error, while `next@14.1.4` was ok.  
Although nothing in the changelog for `v14.1.4` release seems relevant to this issue.

If no one else can reproduce this on newer versions of packages I'd close this issue.

**Comment by trek** [comment]
This appears to have been a specific interaction between next and sharp. https://github.com/vercel/nft/pull/387 should be the fix. Feel free to let us know at [vercel/next.js](https://github.com/vercel/next.js) if it doesn't!

**Comment by timbicker** [comment]
I am still running into this issue with next.js 15.3.3

**Comment by sohcfst** [comment]
Also still running into this with next@15.4.5 and sharp@latest and sharp@0.32.6

using npm@11.5.1

**Comment by OneAndOnlyFinbar** [comment]
I found switching to sharp version `0.30.4` works.

**Comment by dylanngph** [comment]
Issue still happening

**Comment by macrozone** [comment]
it is again broken on  "next": "^15.5.4", on vercel

**Comment by macrozone** [comment]
reopened, because it is broken again on vercel with latest sharp, vercel and nextjs

https://github.com/vercel/vercel/issues/14001

**Comment by mindaugasLukosiunas** [comment]
Can someone tell how to fix this? The build succeeded, but on functionality where sharp is used fails, not finding module for linux.

**Comment by hemant-investnama** [comment]
Override deployment commands on Vercel

Update the Build Command to remove `--turbopack` and use: `next build`
Update the Install Command to: `npm install`
