### ISSUE TITLE
Vercel wont render href on deployed version

### ISSUE THREAD

**Issue by Jonneal3** [zeit/now#11244]
Hi all- My app Runs swimmingly locally. However  when i publish to vercel the opening home .tsx page button (Start Chatting) will change the URL, but does not actually either render the page that it is linking to, or wont "hide" the page that it is currently on. 

Here is the code:

<img width="862" alt="Screenshot 2024-03-07 at 11 10 02 PM" src="https://github.com/vercel/vercel/assets/92951162/00cd13a0-9fdf-4051-910f-b727045b6074">

There are no errors in the console log. Its a really weird error as I don't know where to start being that it actually does send us to the login page but wont change the page visually.

Running mac m2, VSCODE, and my project is typescript.

**Comment by Nagaprasadvr** [comment]
do u have a logic page ?

**Comment by trek** [comment]
Hi @Jonneal3,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
