### ISSUE TITLE
dead link on project settings page

### ISSUE THREAD

**Issue by NicholasHoff** [zeit/now#11267]
In some vercel project, go to the settings tab. Click on Functions on the left menu. On this page, there's a box at the top called "Function Region" that gives information about the default region that serverless functions will be deployed to. At the bottom of this box, there's a link to more information. It says "Learn more about [Function Region](https://vercel.com/docs/serverless-functions/regions)". That link goes to `https://vercel.com/docs/serverless-functions/regions`, but that seems to be a dead link. Perhaps it should link to `https://vercel.com/docs/functions/configuring-functions/region`?

**Comment by cziem** [comment]
I'd like to pick this up if no one is working on it yet.

**Comment by trek** [comment]
Hi @NicholasHoff 

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
