### ISSUE TITLE
Deploying prebuilt app with GitHub actions causes `Error: ENOENT: no such file or directory, lstat '/tmp/151498a2/bootstrap'`

### ISSUE THREAD

**Issue by DiggidyDev** [zeit/now#11273]
**Summary**
I wanted to run tests against my API endpoint before deployments, so I moved the build+deployment process over to GitHub's CI.  The general idea was:
- Run tests for my API
- Build app
- Deploy app with the newly generated build artifacts

The history of GitHub workflow runs can be [found here](https://github.com/DiggidyDev/dockerignore-validator/actions/workflows/vercel-preview.yaml).  All of the failing runs (numbers 1-6) result in this error - I tried a couple of things to get around it, such as forcing no build cache, but it didn't seem to have any effect.

**Setup**
- Vercel CLI v33.5.5
- Next v14.1.3
- Go v1.18

**How I'm getting around the error for now**
For now, I'm not doing the build in GitHub Actions - I'm instead deploying directly to Vercel without using prebuilt files.

**Comment by trek** [comment]
Hi @DiggidyDev,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
