### ISSUE TITLE
help! vercel.com not rendering on any browser

### ISSUE THREAD

**Issue by priyankarpal** [zeit/now#11290]
I have been experiencing an issue with vercel.com for the past two days. The website is not rendering properly on Brave or any other browser on my system. I have tried several solutions to fix this issue including clearing cache and cookies, using a different browser, and changing the DNS settings, but the problem persists. 

Sometimes, the website works properly, but as soon as I close the browser, the issue appears again.

### info
- Brave, Firefox, Chrome (latest) 
- Kali Linux (latest)

**Comment by trek** [comment]
Hi @priyankarpal 

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
