### ISSUE TITLE
Vercel is not sending CRON_SECRET in Authorization header of cron request

### ISSUE THREAD

**Issue by GonzaloAszyn** [zeit/now#11303]
From one moment to another, with a deployment that did not touch anything near to cron requests or vercel.json, now cron requests are not receiving the CRON_SECRET variable and thus it resolves in 403. I could get rid of the security but I don´t want my crons to be publicly available. 

![image](https://github.com/vercel/vercel/assets/88556506/d920b6b8-ffa2-42a3-b5fb-b67355ea68b5)

this is how my code for checking the authorization header looks. It has worked perfectly for months, and it works locally. But suddenly now it does not work on production as authorization header is undefined.

Really need to know what is going on. I'm working with Node.Js express

**Comment by trek** [comment]
Hi GonzaloAszyn,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)

**Comment by xxxijustwei** [comment]
> From one moment to another, with a deployment that did not touch anything near to cron requests or vercel.json, now cron requests are not receiving the CRON_SECRET variable and thus it resolves in 403. I could get rid of the security but I don´t want my crons to be publicly available.
> 
> ![image](https://github.com/vercel/vercel/assets/88556506/d920b6b8-ffa2-42a3-b5fb-b67355ea68b5)
> 
> this is how my code for checking the authorization header looks. It has worked perfectly for months, and it works locally. But suddenly now it does not work on production as authorization header is undefined.
> 
> Really need to know what is going on. I'm working with Node.Js express

Did u solve?
