### ISSUE TITLE
X-Vercel-IP-Country header returning wrong country

### ISSUE THREAD

**Issue by vilihei** [zeit/now#11315]
I am using X-Vercel-IP-Country to identify if certain content on the website should be shown to user or not. After trying it from different key regions I noticed that it returns GB when accessing the website from Philippines. When using other IP based location services I get correct location, but Vercel for some reason thinks the address is in Great Britain.

**Comment by Vilchynskyi** [comment]
I have the same issue. In my case, the user is located in Canada, but the Vercel returns me `San Francisco, USA (sfo1)`

**Comment by C4T4** [comment]
I tried from Argentina and it is showing US, happened also with Colombia.

**Comment by 404rakshit** [comment]
Got multiple country like NL, SG, US for user from India, don't know whats doing on
![image](https://github.com/vercel/vercel/assets/128210165/cfa8ce43-2af1-47fb-92cd-98975e3ba6f0)
![image](https://github.com/vercel/vercel/assets/128210165/f2f8f5c7-5126-4f09-814b-b3da81558903)

Same user different browser

**Comment by trek** [comment]
Hi @vilihei,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
