### ISSUE TITLE
How to main same _rsc key for each link in all the pages

### ISSUE THREAD

**Issue by vinothweb** [zeit/now#11320]
I was wondering how to maintain same _rsc key for links across the pages. Below are example,

```
In page -  example.com/about - the _rsc key for that contact page will be "HYFGB", example link below
example.com/contact?_rsc=HYFGB

In Page - example.com/story -  the key for that story page will be "AKYGV", example link below
example.com/contact?_rsc=AKYGV
```

In the above example the _rsc key of contact page is different in about and story pages. This leads to fetch the rsc pages of same link multiple times in different pages when it is behind CDN.

I am expecting to use same **_rsc=XXXX** key across all the pages for the links.

I'm bringing up this problem because every page has a unique _rsc key, which means the requests cached on the CDN are not very effective. For websites with over 100,000 pages, each page has more than 300 links and when around 100 _rsc hits the server simultaneously the takes bit longer to responds approximately 2 to 5 seconds under high traffic conditions like 1k concurrent users. This delay makes the website seem unresponsive to users when they click on any link.

**Comment by trek** [comment]
Hi @vinothweb,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
