### ISSUE TITLE
Vercel docs recommend unmaintained library that breaks newer nextjs applications

### ISSUE THREAD

**Issue by jamesmillerburgess** [zeit/now#11359]
https://vercel.com/guides/sending-emails-from-an-application-on-vercel

The guide above recommends `mailing` to send emails from Vercel applications, but this package appears to be unmaintained since before app router was implemented. It breaks if imported into newer NextJS applications and throws errors about ugilfy-js, which is one of its dependencies.

Minimum reproduction: https://github.com/jamesmillerburgess/next-mailing-bug

https://github.com/sofn-xyz/mailing

![image](https://github.com/vercel/vercel/assets/15968012/7d557277-fa91-4ade-a6f9-8c2be36dacc3)

**Comment by trek** [comment]
Hi @jamesmillerburgess 

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)

**Comment by jamesmillerburgess** [comment]
Thanks. I've opened a topic at https://vercel.community/
