### ISSUE TITLE
Running firebase CLI commands on Vercel throws: "firebase: command not found" error

### ISSUE THREAD

**Issue by gdrose** [zeit/now#11386]
We are currently hosting our application on Vercel and encountering an issue when attempting to execute Firebase CLI commands. 

When trying to deploy Firestore rules using Firebase CLI within our Vercel environment, we receive the error message: "still stderr: /bin/sh: firebase: command not found". We managed to use the correct PATHs and ENVs:

```javascript
const firebaseDeploy = spawn(`firebase`, ['deploy', '--only', `firestore`], {
	env: firebaseEnv,
	shell: true,
	cwd: process.cwd()
});
```

Is it an import issue or something else? 

Maybe that simply cannot be done inside a Vercel deployment, who knows? Unfortunately the documentation is really poor and just redirects you to the Vercel CLI project when looking up any keyword regarding this bug, so I'm also opening this question as a repo issue.

_Originally posted by @gdrose in https://github.com/vercel/vercel/discussions/11385_

**Comment by trek** [comment]
Hi @gdrose,

Firebase is not a globally installed executable on Vercel. https://stackoverflow.com/questions/75012045/using-firebase-cli-when-not-installed-globally might be the solution you need.
