### ISSUE TITLE
Error "The `projectSettings` object is required for new projects, but is missing in the deployment payload"

### ISSUE THREAD

**Issue by lakminagamage** [zeit/now#11404]
I am trying to deploy a FastAPI app as a serverless function on vercel, using vercel CLI. Deployment successfully occurs. 

When I'm trying to promote depoyment to production a message pops up saying " The `projectSettings` object is required for new projects, but is missing in the deployment payload" .

No any documentation about such error is marked anywhere. Any workarounds?

<img width="515" alt="Screenshot 2024-04-10 at 01 10 13" src="https://github.com/vercel/vercel/assets/24446012/cf3347f4-9b6d-40c4-b01a-cfb3e8e6a182">

**Comment by TooTallNate** [comment]
Can you share a reproduction?

**Comment by lakminagamage** [comment]
Sure @TooTallNate, 

Steps to reproduce,

1. Create a simple FastAPI app 
2. create a main.py and define the entrypoint with Uvicorn.
3. Create vercel.json with contetnt {
    "devCommand": "uvicorn app:app --host 0.0.0.0 --port 8000",
    "builds": [
      {
        "src": "app.py",
        "use": "@vercel/python"
      }
    ],
    "routes": [
      {
        "src": "/(.*)",
        "dest": "app.py"
      }
    ]
  }
4. deploy this using Vercel CLI.
5. Go to project in vercel.com and open it.
6. Go to deployments tab. Click on the 3 dot menu button and tap "promote to deployment".

**Comment by lakminagamage** [comment]
This issue is now fixed on Vercel.
