### ISSUE TITLE
X-Vercel-IP-Country returning wrong country

### ISSUE THREAD

**Issue by C4T4** [zeit/now#11425]
X-Vercel-IP-Country is returning the wrong country. I tested it from Argentina and for Colombia, for both it's showing US as a country. If I set my VPN to Germany it shows the correct country. if I set my VPN to Colombia it shows US

**Comment by trek** [comment]
Hi @C4T4,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
