### ISSUE TITLE
create a support case is disabled

### ISSUE THREAD

**Issue by C4T4** [zeit/now#11426]
I tried to create a new support case and the button to click is disabled.

![bug](https://github.com/vercel/vercel/assets/12415654/d5f63790-5cb3-45ef-900e-fd7ee2b6f1f6)

**Comment by mcsdevv** [comment]
Hey @C4T4, thanks for flagging this and apologies for the poor experience. We shipped a fix yesterday to address this. Please let me know if you experience it again.
