### ISSUE TITLE
Issue Deploying Nuxt 2 App: Cannot find module 'vercel__launcher.launcher'

### ISSUE THREAD

**Issue by francescophra** [zeit/now#11443]
Hello,
I am attempting to deploy a Nuxt 2 application on Vercel and have encountered a persistent issue. Following my recent pushes, all my projects are consistently showing the following error:

```
This Serverless Function has crashed.
500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
```

In the logs, I found this error:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/vercel__launcher.launcher' imported from /opt/rust/nodejs.js
at finalizeResolution (node:internal/modules/esm/resolve:269:11)
at moduleResolve (node:internal/modules/esm/resolve:922:10)
at moduleResolveWithNodePath (node:internal/modules/esm/resolve:1135:12)
at defaultResolve (node:internal/modules/esm/resolve:1178:79)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
at importModuleDynamically (node:internal/modules/cjs/loader:1261:33)
at importModuleDynamicallyWrapper (node:internal/vm/module:431:21) {
code: 'ERR_MODULE_NOT_FOUND',
url: 'file:///var/task/vercel__launcher.launcher'
}
```

That's my config:

```
{
  "name": "prj",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "core-js": "^3.25.3",
    "nuxt": "^2.15.8",
    "vue": "^2.7.10",
    "vue-server-renderer": "^2.7.10",
    "vue-template-compiler": "^2.7.10"
  },
  "devDependencies": {}
}
```

And vercel.json

```
{
  "builds": [
    {
      "src": "nuxt.config.js",
      "use": "@nuxtjs/vercel-builder",
      "config": {}
    }
  ]
}

```

Could you please assist in resolving this error? Thank you.

**Comment by JhonSteven** [comment]
Hey, I started getting the same error today, @francescophra could you fix it?

**Comment by wrrnlim** [comment]
Not sure if this helps but I had the same error and noticed a warning in my build:

```
WARN! npm WARN deprecated @now/node@1.8.5: "@now/node" is deprecated and will stop receiving updates on December 31, 2020. Please use "@vercel/node" instead.
```

I changed my `vercel.json` to use `@vercel/node` and that fixed it for me.

```js
"builds": [
    {
      "src": "index.js",
      "use": "@vercel/node" // changed from @now/node
    }
  ],
```

I was still using `@now/node` yesterday and everything was working fine, but I guess something changed today

**Comment by francescophra** [comment]
> Hey, I started getting the same error today, @francescophra could you fix it?

@JhonSteven Not yet

---
> I changed my `vercel.json` to use `@vercel/node` and that fixed it for me.

@wrrnlim Thanks for your feedback. Unfortunately it's still broken for me

**Comment by devmarcelosantos** [comment]
I have the same problem, i've already tested changing the project to node 16, setting a version of vercel-builder in the vercel.json file, but so far nothing.

**Comment by francescophra** [comment]
If you have an ES6 import in your nuxt.config.js, try removing it. It worked for me. 
I also updated Nuxt 2 and ran it on Node 18.
@JhonSteven @wrrnlim @devmarcelosantos

**Comment by francescophra** [comment]
If you encounter other errors, try reading these issues.
[https://github.com/nuxt/vercel-builder/issues/513](https://github.com/nuxt/vercel-builder/issues/513)
[https://github.com/nuxt/vercel-builder/issues/589](https://github.com/nuxt/vercel-builder/issues/589)

**Comment by JhonSteven** [comment]
@francescophra Thanks, it worked for me as well!!
