### ISSUE TITLE
getInstalledPackageVersion is not a function

### ISSUE THREAD

**Issue by Herklos** [zeit/now#11464]
Hello,

I tried to build using `vercel build` 20 minutes ago using `vercel@latest` installed with `npm install -g vercel@latest` but I get this error : `Error: (0 , import_build_utils13.getInstalledPackageVersion) is not a function`.

My GitHub Actions builds keep failing because they encounter this error at the end.

How can I fix it?

**Comment by cmc7r** [comment]
This issue is also happening for me, on version 34.1.0, where as I did not have this issue on 34.0.0 (or any other previous version that I know of)

**Comment by TooTallNate** [comment]
Sorry about that folks. Should be fixed as of `vercel@34.1.1`.

**Comment by Herklos** [comment]
> Sorry about that folks. Should be fixed as of `vercel@34.1.1`.

Yes it is, thanks @TooTallNate.

**Comment by ljhskyso** [comment]
got this error again for 34.2.5 and 34.2.6 getInstalledPackageVersion. is it something a quick fix? @TooTallNate
