### ISSUE TITLE
vercel dev not working

### ISSUE THREAD

**Issue by kaushiksahu18** [zeit/now#11535]
I want to deploy my express app to vercel [todoappdb](https://github.com/kaushiksahu18/todoappDB)
i have watched many videos and docs, and come up with idea to add `vercel.json file` showing blow
```json
{
  "version": 2,
  "builds": [{ "src": "index.js", "use": "@vercel/node" }],
  "routes": [{ "src": "/(.*)", "dest": "/" }]
}
```
after this i did `vercel login` and then `vercel dev`, (source:vercel docs).
**BUT ITS NOT WORKING**
`console log`
```
$ vercel dev
(node:28702) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Vercel CLI 34.1.7
? Set up and develop “~/forvs/todoDBforkkta”? yes
? Which scope should contain your project? kaushiksahu18's projects
? Link to existing project? no
? What’s your project’s name? todoappdb1
? In which directory is your code located? ./
🔗  Linked to kaushiksahu18s-projects/todoappdb1 (created .vercel)
> Ready! Available at http://localhost:3000
Server running on port 5000
file:///home/kaushiksahu18/.local/share/pnpm/global/5/.pnpm/@vercel+node@3.0.28/node_modules/@vercel/node/dist/dev-server.mjs:1027
    return listener(req, res);
           ^

TypeError: listener is not a function
    at Server.<anonymous> (file:///home/kaushiksahu18/.local/share/pnpm/global/5/.pnpm/@vercel+node@3.0.28/node_modules/@vercel/node/dist/dev-server.mjs:1027:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.7.3
```

**NOW WHAT I SHOULD DO?**
**IS THERE ANY EASY WAY TO DEPLOY EXPRESS APP EITHER ON VERCEL OR .......**

**Comment by sidddev7** [comment]
I am also facing same issue
`TypeError: listener is not a function`

**Comment by kaushiksahu18** [comment]
> I am also facing same issue

i was trying to deploy my express.js server, but now i think i only have one option, using server less i.g. **cloudflare workers(provide free tiar)**, you can try too.

**Comment by dcumro** [comment]
Try adding the line    " module.exports = app;"  to the index.js file.

**Comment by sidddev7** [comment]
I got the resolution to this issue

I added this to vercel.json

`{
  "version": 2,
  "rewrites": [{ "source": "/(.*)", "destination": "/api" }]
}
`
the destination should contain the path of starting point of your server app, where we initialize the express app and expose the port

**Comment by trek** [comment]
@kaushiksahu18 please let us know if @sidddev7's solutions works for you!
