### ISSUE TITLE
[34.1.8] `vercel build` Error: Cannot read properties of null (reading 'trim')

### ISSUE THREAD

**Issue by hsuanxyz** [zeit/now#11547]
we're using the Vercel CLI in our CI, but we recently got the following error, and we haven't changed any codes, dependencies or configurations.

```shell
#  vercel build --token=${{ secrets.VERCEL_TOKEN }}

Vercel CLI 34.1.8
Detected `pnpm-lock.yaml` version 6 generated by pnpm 8
Running "install" command: `pnpm i`...
Scope: all 10 workspace projects
...
...: Done
Done in 6.6s
Error: Cannot read properties of null (reading 'trim')
Error: Process completed with exit code 1.
```

possible reason is that we are using `vercel@canary` and when I downgrade to `vercel@34.1.7` everything works fine. I tried to add the `--debug` flag, but there was no helpful information.

looking at the changelog, I suspect this commit has something to do with it.
https://github.com/vercel/vercel/commit/dc974b6797de0b6e90373c92e1f2bbdafcfc6687#diff-466c3ca84fb92d65cf8c3c9dfb99bd904425f3a527b86dd7f2b1d79096213318R592

**Comment by FredrikAugust** [comment]
Currently experiencing the same. Caused all CD pipelines to fail. Reverting to `vercel@34.1.7` worked as well for us, confirming `34.1.8` is the culprit.

**Comment by cedric25** [comment]
I can confirm I have the same behavior on my CI runs. Reverting to `vercel@34.1.7` for now.

**Comment by kr4chinin** [comment]
Same here, broke 3 days ago.

**Comment by TooTallNate** [comment]
Thanks for the report. Working on the fix now.

**Comment by TooTallNate** [comment]
Fix is in https://github.com/vercel/vercel/pull/11559.
