### ISSUE TITLE
Regression: `vercel build` fails with pnpm v9.1.x on latest Vercel CLI

### ISSUE THREAD

**Issue by AurelienGasser** [zeit/now#11607]
https://github.com/vercel/vercel/pull/11596 seems to have introduced a regression in https://github.com/vercel/vercel/releases/tag/vercel%4034.2.0 when building with pnpm v9.1.0

Preview build logs before (notice CLI v.34.1.10)

```
[14:55:14.413] Running build in Washington, D.C., USA (East) – iad1
[14:55:14.541] Cloning [redacted]
[14:55:15.238] Cloning completed: 696.768ms
[14:55:15.239] Running "[ $(git branch --show-current) == "main" ]"
[14:55:15.652] Found .vercelignore
[14:55:15.665] Removed 4 ignored files defined in .vercelignore
[14:55:27.118] Restored build cache
[14:55:27.242] Running "vercel build"
[14:55:28.196] Vercel CLI 34.1.10
[14:55:29.754] Detected `pnpm-lock.yaml` version 9 generated by pnpm 8
[14:55:29.803] Installing dependencies...
```

Preview build logs after (notice CLI v34.2.0)

```
[16:08:05.141] Running build in Washington, D.C., USA (East) – iad1
[16:08:05.270] Cloning [redacted]
[16:08:06.157] Cloning completed: 886.836ms
[16:08:06.157] Running "[ $(git branch --show-current) == "main" ]"
[16:08:06.707] Found .vercelignore
[16:08:06.718] Removed 4 ignored files defined in .vercelignore
[16:08:38.984] Restored build cache
[16:08:39.073] Running "vercel build"
[16:08:40.095] Vercel CLI 34.2.0
[16:08:40.668] Detected `pnpm-lock.yaml` version 9 generated by pnpm 9
[16:08:40.701] Installing dependencies...
[16:08:41.533]  ERR_PNPM_BAD_PM_VERSION  This project is configured to use v9.1.0 of pnpm. Your current pnpm is v9.0.4
[16:08:41.533] 
[16:08:41.534] If you want to bypass this version check, you can set the "package-manager-strict" configuration to "false" or set the "COREPACK_ENABLE_STRICT" environment variable to "0"
[16:08:41.550] Error: Command "pnpm install" exited with 1
[16:08:42.394] 
```

package.json has

```json
  "packageManager": "pnpm@9.1.0",
```

and pnpm-lock.json has

```
lockfileVersion: '9.0'
```

**Comment by Jarrku** [comment]
Also running into this issue, our builds started failing somewhere today, as it's not detecting the pnpm override anymore it seems.

Logs from a build ~8h ago:
```
--
16:55:52.394 | Restored build cache
16:55:52.481 | Running "vercel build"
16:55:52.944 | Vercel CLI 34.1.10
16:55:53.120 | > Detected Turbo. Adjusting default settings...
16:55:54.739 | > Detected ENABLE_EXPERIMENTAL_COREPACK=1 and "pnpm@9.1.1" in package.json
16:55:55.008 | Running "install" command: `pnpm install`...
16:55:55.703 | Scope: all 18 workspace projects
16:55:59.584 |  
16:55:59.701 | ../../../.. prepare$ husky
16:55:59.784 | ../../../.. prepare: Done
16:56:00.103 | Done in 4.9s
```

Logs I'm getting now:
```
Restored build cache
01:09:24.816 | Running "vercel build"
01:09:25.254 | Vercel CLI 34.2.0
01:09:25.403 | > Detected Turbo. Adjusting default settings...
01:09:25.845 | > Detected ENABLE_EXPERIMENTAL_COREPACK=1 and "pnpm@9.1.1" in package.json
01:09:26.107 | Detected `pnpm-lock.yaml` version 9 generated by pnpm 9
01:09:26.107 | Running "install" command: `pnpm install`...
01:09:26.660 | WARN  This project is configured to use v9.1.1 of pnpm. Your current pnpm is v9.0.4
01:09:26.662 | ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)
01:09:26.663 |  
01:09:26.663 | Your pnpm version is incompatible with "/vercel/path0".
01:09:26.663 |  
01:09:26.663 | Expected version: ^9.1.1
01:09:26.663 | Got: 9.0.4
01:09:26.663 |  
01:09:26.663 | This is happening because the package's manifest has an engines.pnpm field specified.
01:09:26.663 | To fix this issue, install the required pnpm version globally.
01:09:26.663 |  
01:09:26.663 | To install the latest version of pnpm, run "pnpm i -g pnpm".
01:09:26.663 | To check your pnpm version, run "pnpm -v".
01:09:26.676 | Error: Command "pnpm install" exited with 1
```

**Comment by wweaver** [comment]
Is this something that would likely get fixed today? My team needs to deploy something. Just wondering if I have to remove corepack, or pin the version to 9.0.4 for now instead of a newer version.

**Comment by EndangeredMassa** [comment]
There are two different errors here, but they look very similar. Please take note of the exact error message for mitigation options below.

Note that Vercel uses specific versions of major versions of `pnpm` by default. These can change, but right now, we support these versions of `pnpm`:

* `pnpm@6.35.1`
* `pnpm@7.33.5`
* `pnpm@8.15.8`
* `pnpm@9.0.4`

The proper matching major version is used based on the lockfile version and the `package.json#packageManager` version (if it exists).

If you want the exact version specified in `package.json#packageManager`, you need to [enable corepack on Vercel](https://vercel.com/docs/deployments/configure-a-build#corepack).

We're working on improving this developer experience in general, as well.

# pnpm error `ERR_PNPM_UNSUPPORTED_ENGINE`

For anyone seeing the `ERR_PNPM_UNSUPPORTED_ENGINE` error from `pnpm`, you can work around this problem by doing any of the following:

* enable corepack ([vercel docs](https://vercel.com/docs/deployments/configure-a-build#corepack))
    * set env var `ENABLE_EXPERIMENTAL_COREPACK` to `1`
    * make sure you have a matching `package.json#packageManager` value
* remove your `package.json#engines.pnpm` value ([pnpm docs](https://pnpm.io/package_json#engines))

cc @Jarrku

# pnpm error `ERR_PNPM_BAD_PM_VERSION`

For anyone seeing the `ERR_PNPM_BAD_PM_VERSION` error from `pnpm`, you can work around this problem by doing any of the following:

* enable corepack ([vercel docs](https://vercel.com/docs/deployments/configure-a-build#corepack))
    * set env var `ENABLE_EXPERIMENTAL_COREPACK` to `1`
* disable corepack strictness ([pnpm docs](https://pnpm.io/npmrc#package-manager-strict)) ([corepack docs](https://github.com/nodejs/corepack/blob/09528a8ea8f2a953b67c9079615eae3394531862/README.md#L263-L269))
    * set env var `COREPACK_ENABLE_STRICT` to `0`
    * this is necessary even if you aren't using corepack because `pnpm` checks this value
* disable package manager strictness ([pnpm docs](https://pnpm.io/npmrc#package-manager-strict))
    * set `package-manager-strict` to `false` in `.npmrc`

cc @AurelienGasser

**Comment by Jarrku** [comment]
@EndangeredMassa

We have corepack enabled & have packageManager set to 9.1.1

If I understand correctly, we should not set the engines field, because this overrules the other settings?

**Comment by EndangeredMassa** [comment]
@Jarrku you should be able to have it working like that. I didn't notice in your logs that corepack was already enabled. That's a separate issue.

# Corepack enabled, but still getting `ERR_PNPM_UNSUPPORTED_ENGINE`

If you see both these items in your logs:
- `Detected ENABLE_EXPERIMENTAL_COREPACK=1 ...`
- `ERR_PNPM_UNSUPPORTED_ENGINE`

Then you have a special case of this error. We're diagnosing this problem now. If you can share your project, a specific deployment, even source code, that'd be awesome. Feel free to email me a zip even, if that's possible, at sean.massa@vercel.com.

**Comment by wweaver** [comment]
> @Jarrku you should be able to have it working like that. I didn't notice in your logs that corepack was already enabled. That's a separate issue.
> 
> # Corepack enabled, but still getting `ERR_PNPM_UNSUPPORTED_ENGINE`
> If you see both these items in your logs:
> 
> * `Detected ENABLE_EXPERIMENTAL_COREPACK=1 ...`
> * `ERR_PNPM_UNSUPPORTED_ENGINE`
> 
> Then you have a special case of this error. We're diagnosing this problem know. If you can share your project, a specific deployment, even source code, that'd be awesome. Feel free to email me a zip even, if that's possible, at [sean.massa@vercel.com](mailto:sean.massa@vercel.com).

It started this morning with no changes on our end. If @Jarrku doesn't get more info for you I can try to look into it on Monday. We ended up pinning our version of pnpm to 9.0.4 to match vercel for now.

![cruisecritic-com_–_Deployment_Overview](https://github.com/vercel/vercel/assets/1482976/a683d038-dc5a-4609-b0a7-7ad996fa8665)

**Comment by Jarrku** [comment]
@EndangeredMassa

On my phone currently, but here's a deployment link
https://vercel.com/pexip-engage/booking-plugin/FMxsmUohJXkv8rByEV3ZaE9PrjRY

Most of our projects under pexip engage are failing.

I can share the root package json if that's helpful?

**Comment by wweaver** [comment]
Could this be a next issue? Or the fact of having a global pnpm installed along with the corepack one and next is using the global one? The reason I say that is because we have a vercel build for storybook that's not using next and it doesn't have an issue. It uses corepack and it's not failing with the same error labeled here. For now I turned off strictness of the package manager in the vercel setting for our nextjs builds.

**Comment by wweaver** [comment]
Actually, did this get resolved? I'm not getting the warning any longer. I just tried to disable laxness of pnpm version and it seems like it's working again.

**Comment by markoftw** [comment]
Doesn't seem to be solved yet, tried with the latest PNPM 9.1.3 and the issue persists.

**Comment by FleetAdmiralJakob** [comment]
> Doesn't seem to be solved yet, tried with the latest PNPM 9.1.3 and the issue persists.

This isnt about a problem from pnpm. pnpm made a design decision that was challenged now by vercel and until the poll on Twitter is over I think there will be no fix on the vercel side.

**Comment by EndangeredMassa** [comment]
# pnpm error `ERR_PNPM_BAD_PM_VERSION`

We've rolled out a change that disables `pnpm@9`'s strictness when checking the `package.json#packageManager` value. You can still enable this strictness in your project by setting `package-manager-strict` to `true` in your `.npmrc`.

You will still see pnpm's warning when these versions don't match, but it will not error and break the build on Vercel.

That issue should be resolved for everyone now. If you still encounter it, let me know in this thread. 

# Corepack enabled, but still getting `ERR_PNPM_UNSUPPORTED_ENGINE`

We're still digging into this. I've not been able to reproduce it a single time.

If you are still seeing this, let me know!

If you have a reproduction, let me know!

You can respond here and/or send a tarball of a project that reproduces the problem to sean.massa@vercel.com. Thanks!

**Comment by nerdo** [comment]
> # pnpm error `ERR_PNPM_BAD_PM_VERSION`
> 
> We've rolled out a change that disables `pnpm@9`'s strictness when checking the `package.json#packageManager` value. You can still enable this strictness in your project by setting `package-manager-strict` to `true` in your `.npmrc`.
> 
> You will still see pnpm's warning when these versions don't match, but it will not error and break the build on Vercel.
> 
> That issue should be resolved for everyone now. If you still encounter it, let me know in this thread.
> # Corepack enabled, but still getting `ERR_PNPM_UNSUPPORTED_ENGINE`
> 
> We're still digging into this. I've not been able to reproduce it a single time.
> 
> If you are still seeing this, let me know!
> 
> If you have a reproduction, let me know!
> 
> You can respond here and/or send a tarball of a project that reproduces the problem to [sean.massa@vercel.com](mailto:sean.massa@vercel.com). Thanks!

Hi,

I think I've managed to reproduce it... I don't think it's reproducible by a codebase alone, but I *think* it may have something to do with turborepo - it would be great if others can others confirm that they are also using turborepo.

I started out by creating a project https://github.com/nerdo/vercel-corepack-test and kept it dead simple. Just a project with a `package.json`, and I deployed it to Vercel with corepack enabled via the `ENABLE_EXPERIMENTAL_COREPACK=1` environment variable. After the initial deployment, I also added the variable `VERCEL_FORCE_NO_BUILD_CACHE=1` because in our project where this issue occurs, we also had that set, but it turned out it doesn't seem to matter.

I tried a few things that you can trace in the git history, but none of them produced the error.

Finally, I decided to introduce turborepo. I deleted my project and created a new one pointing to the `app/something` project in the monorepo. The inital deployment then failed with the following:

```
[14:53:34.031] Running build in Washington, D.C., USA (East) – iad1
[14:53:34.157] Cloning github.com/nerdo/vercel-corepack-test (Branch: main, Commit: 8cab6fa)
[14:53:34.441] Cloning completed: 284.192ms
[14:53:34.520] Previous build cache not available
[14:53:34.752] Running "vercel build"
[14:53:35.627] Vercel CLI 34.2.4
[14:53:35.767] > Detected Turbo. Adjusting default settings...
[14:53:36.214] > Detected ENABLE_EXPERIMENTAL_COREPACK=1 and "pnpm@9.0.4" in package.json
[14:53:36.321] Warning: Detected "engines": { "node": ">=16.0.0" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[14:53:36.324] Detected `pnpm-lock.yaml` version 9 generated by pnpm 9
[14:53:36.324] Running "install" command: `pnpm install`...
[14:53:36.818]  WARN  This project is configured to use v9.0.4 of pnpm. Your current pnpm is v9.1.4
[14:53:36.820]  ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)
[14:53:36.820] 
[14:53:36.820] Your pnpm version is incompatible with "/vercel/path0".
[14:53:36.821] 
[14:53:36.821] Expected version: 9.0.4
[14:53:36.821] Got: 9.1.4
[14:53:36.821] 
[14:53:36.821] This is happening because the package's manifest has an engines.pnpm field specified.
[14:53:36.821] To fix this issue, install the required pnpm version globally.
[14:53:36.821] 
[14:53:36.821] To install the latest version of pnpm, run "pnpm i -g pnpm".
[14:53:36.821] To check your pnpm version, run "pnpm -v".
[14:53:36.835] Error: Command "pnpm install" exited with 1
[14:53:37.091] 
```

@EndangeredMassa  are you able to reproduce these steps, too?

**Comment by wweaver** [comment]
> I think I've managed to reproduce it... I don't think it's reproducible by a codebase alone, but I _think_ it may have something to do with turborepo - it would be great if others can others confirm that they are also using turborepo.

@nerdo, yes we are using turborepo as well. And my feeling was that it had to do with some tool. I was thinking next but turborepo would make sense as well.

**Comment by wweaver** [comment]
> Actually, did this get resolved? I'm not getting the warning any longer. I just tried to disable laxness of pnpm version and it seems like it's working again.

By the way, I was wrong about this being fixed.

**Comment by nerdo** [comment]
@EndangeredMassa do you have any update on whether or not you were able to reproduce the issue with turborepo in the mix as I documented above?

**Comment by mcmxcdev** [comment]
Still a problem, but the version that Vercel picks now is 9.2.0 instead of 9.1.4 as mentioned further above, not respecting the `packageManager` field at all.

**Comment by grmkris** [comment]
issue still present, using `package-manager-strict=false ` for now

**Comment by grmkris** [comment]
> issue still present, using `package-manager-strict=false ` for now

this doesn't seem to work..

**Comment by EndangeredMassa** [comment]
We've been rolling out fixes and better error messages for the various cases around `pnpm` usage. If you are still seeing an issue, can you mention all of the following?

- error code: `ERR_PNPM_BAD_PM_VERSION`, `ERR_PNPM_UNSUPPORTED_ENGINE`, or whatever else it is
- is [corepack](https://vercel.com/docs/deployments/configure-a-build#corepack) enabled? (you have `ENABLE_EXPERIMENTAL_COREPACK` set to `1`)
- is this in a monorepo?

Source code is appreciated, when possible.

**Comment by mcmxcdev** [comment]
Just verified that it still happens. I wanted to make our `engines.pnpm` version stricter (modified from 9.0.0 to 9.10.0), but then we run into this:

```
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)
Your pnpm version is incompatible with "/vercel/path0".
Expected version: ^9.10.0
Got: 9.4.0
```

`ENABLE_EXPERIMENTAL_COREPACK` is set to `1`

Its a monorepo, based on https://vercel.com/templates/svelte/turborepo-sveltekit-starter

**Comment by tobiastornros** [comment]
Looks like it's not enough to set `ENABLE_EXPERIMENTAL_COREPACK` to `1.` You need to remove pnpm from engines in package.json which is weird because you want it for errors in version mismatch for local development.

**Comment by tobiastornros** [comment]
And it doesn't look like corepack works or how should I interpret this?

```
> Detected ENABLE_EXPERIMENTAL_COREPACK=1 and "pnpm@9.10.0" in package.json
Detected `pnpm-lock.yaml` version 9 generated by pnpm@9.x
Running "install" command: `pnpm install`...
../.. |  WARN  Unsupported engine: wanted: {"node":"20.12.2"} (current: {"node":"v20.17.0","pnpm":"9.4.0"})
```

**Comment by FleetAdmiralJakob** [comment]
I have the same problem with a monorepo. To solve it I had to set the engines and packageManager in every package because Vercel does not look at the engines and packageManager in the root package.json. Additionally I had to set this environment variable for all builds: `ENABLE_EXPERIMENTAL_COREPACK=1`
![image](https://github.com/user-attachments/assets/3ab62835-338b-4b93-8fe2-a35f07cb79ae)

**Comment by onsclom** [comment]
We rolled out a fix that detects `packageManager` in the root package.json! It is no longer necessary to define `packageManager` in every package of a monorepo.

Turborepo projects using corepack may see corepack getting disabled. To solve this, **either**:
- Upgrade `turbo` to `2.1.3` or higher **OR**
- Add `COREPACK_HOME` to [`turbo.json#globalPassThroughEnv`](https://turbo.build/repo/docs/reference/configuration#globalpassthroughenv)

**Comment by trek** [comment]
Closing for now since we haven't heard back after our fixes deployed. Feel free to open a new issue if something else crops up!
