### ISSUE TITLE
Console Logs Merging into a Single Message in Dashboard when Using ESModules

### ISSUE THREAD

**Issue by maguroid** [zeit/now#11619]
## Issue Summary
When specifying type: module in package.json (using ESModules), all standard output in the dashboard is consolidated into a single message. This causes the logs to exceed the size limit quickly, leading to some log entries being truncated. I am using native ESModule as its dependency so I can't migrate the project to common.js.

<img width="1173" alt="image" src="https://github.com/vercel/vercel/assets/78241354/6439cd0d-d381-4035-933a-c8598a9cc433">

## Expected Behavior
Each console.log should be displayed independently in the dashboard to ensure that log entries do not exceed the size limit and are displayed in full. like below.
<img width="1174" alt="image" src="https://github.com/vercel/vercel/assets/78241354/18607b6f-82e3-4b3a-a4cf-82334dc038fd">

## Minimal Reproduction
Here is the reproduction code:
https://github.com/maguroid/vercel-esm-logs

**Comment by trek** [comment]
Hi @maguroid,

I've let our logs team know. We're in the process of migrating to our [new community platform](https://github.com/orgs/vercel/discussions/7413). If you're still seeing this issue, can head over to https://vercel.community/ and ask there? Thank you!
