### ISSUE TITLE
Not able to apply custom timeline for my project logs

### ISSUE THREAD

**Issue by DeepaPrasanna** [zeit/now#11679]
I am trying to access my app's logs within a certain timeline. On the click of this button (outlined in red here), a calendar shows but its not responsive making it difficult to set the start and end time. Initially, that gave me the impression that there is no start date at all. (Attached the screenshot below)

<img width="242" alt="image" src="https://github.com/vercel/vercel/assets/54895192/56fb6eff-2f93-4bf1-9f1e-fda865c976e5">

![image](https://github.com/vercel/vercel/assets/54895192/ca2c2a35-c8b1-4df8-a292-08855b3650b2)

Even if I set start and end times in mobile view, the timeline is not getting updated.

_Expected behaviour_ :  The Calendar widget to be responsive and the start and end dates to get updated.

_How to reproduce_: Select any project in the dashboard. Navigate to logs tab and select the custom option in timeline.  Click the button  mentioning the time frame.

**Comment by clifflee365** [comment]
The same issue,  when selecting "Custom" in the Selector and setting the desired start and end times. When the Popover disappears, the custom time should take effect, or there should be a confirmation button below. However, after selecting the start and end times, there is no effect.

As a result, I can only see the logs from the last hour or live logs, very confusing.

**Comment by saltbiscuit** [comment]
Same issue here. Any fixes?

**Comment by trek** [comment]
Hi @DeepaPrasanna  

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help please open a new discussion at https://vercel.community.
