### ISSUE TITLE
I am tryping to deploy my web project on vercel 

### ISSUE THREAD

**Issue by vasuxd3v** [zeit/now#11678]
![Screenshot 2024-05-31 214347](https://github.com/vercel/vercel/assets/118809473/ca66c199-9747-455f-8242-1540634ef322)
![Screenshot 2024-05-31 214400](https://github.com/vercel/vercel/assets/118809473/96112efa-ebb8-43e0-b250-54c4d8ae9e44)
in terminal it is correct like in vs code terminal but the building never ends it about more than 15 mins and building go on 
help me to fix it

**Comment by victoryosiobe** [comment]
I guess you're trying you app to start on a build command, usually the default by Vercel. So you app is listening instead of building.

**Comment by trek** [comment]
Hi @VasuDev8110,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
