### ISSUE TITLE
[BUG] Router.back() does not work when history contains query parameters

### ISSUE THREAD

**Issue by austin011** [zeit/now#11715]
Summary:
router.back() does not navigate to the former URL if that url contains search parameters. Next Router handles the url change but the app does not reflect it (page does not change).

Steps to reproduce:
1. Navigate from URL with search params (http://localhost:3000/canvas-maps?states=1000)
2. toggle router.back() from new url (http://localhost:3000/canvas-maps/42)

Using:
"next": "^14.2.1"
"react": "18.2.0",
"react-dom": "18.2.0",

**Comment by trek** [comment]
Hi @austin011 

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help please open a new discussion at https://vercel.community. For issues related to Next.js, please post to https://github.com/vercel/next.js
