### ISSUE TITLE
[Bug]: Text goes hidden when selected

### ISSUE THREAD

**Issue by alieldeba** [zeit/now#11778]
In the tour guide page at the last section which is "Live in production" when I try to select the text it disappears.

![Uploading image.png…]()

![Uploading image.png…]()

Link: https://vercel.com/product-tour?thankyou=&i=10

**Comment by trek** [comment]
Hi @alieldeba 

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
