### ISSUE TITLE
[BUG]: Flask Server will not update domain

### ISSUE THREAD

**Issue by loganvxr** [zeit/now#11785]
I'm sorry if the title was not clear, but here is the problem I am facing. Currently, when I try to visit my subdomain [loganpaxton.foo.ng](https://loganpaxton.foo.ng), I get one of the previous styles, that aren't in use for the development URLs. Is there a way I can fix this? I used a community made template instead of one made by Vercel. I'll link my repo [here](https://github.com/LoganPaxton/loganpaxton-flask).

**Comment by trek** [comment]
Hi @LoganPaxton,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
