### ISSUE TITLE
Several examples expose some internal files via static assets

### ISSUE THREAD

**Issue by telcy** [zeit/now#11799]
I have found several examples that expose some internal files via static assets. I think this should be fixed to avoid having users build on these templates and unknowingly expose sensitive files.

template: https://vercel.com/templates/hono/hono-on-vercel
https://hono-starter.vercel.sh/package-lock.json
https://hono-starter.vercel.sh/README.md
https://hono-starter.vercel.sh/tsconfig.json

template: https://vercel.com/templates/python/python-hello-world
https://python-hello-world.vercel.app/README.md

template: https://vercel.com/templates/other/nodejs-serverless-function-express
https://nodejs-api-example.vercel.app/README.md

template: https://vercel.com/templates/other/fastify-serverless-function
https://fastify-example.vercel.app/pnpm-lock.yaml

<img width="1223" alt="Screenshot 2024-07-04 at 21 55 31" src="https://github.com/vercel/vercel/assets/3081527/164545e4-cf01-47a8-bb4f-63c9c808dfb6">

**Comment by trek** [comment]
Hi @telcy! We're in the process of migrating to our [new community platform](https://github.com/orgs/vercel/discussions/7413). If you're still seeing this issue, can head over to https://vercel.community/ and ask there? Thank you!
