### ISSUE TITLE
[Bug] Categories button not working on mobile devices in blog section

### ISSUE THREAD

**Issue by nsgpriyanshu** [zeit/now#11815]
## Description
The categories button in the blog section is not responsive on mobile devices. When tapping the button, nothing opens.

## Steps to Reproduce
1. Open the Vercel app on a mobile device.
2. Navigate to the blog section.
3. Tap the categories button.

## Expected Behavior
The categories dropdown should open when the button is tapped.

## Actual Behavior
The categories dropdown does not open when the button is tapped.

## Screenshots
![Screenshot_20240709-105152~3](https://github.com/vercel/vercel/assets/166146782/828f231e-1b2d-43f9-bde3-adff0741f885)

## Environment
- **Device:** OnePlus Nord ce 2 lite 5g
- **OS:** Android 14
- **Browser:** Chrome

**Comment by trek** [comment]
Hi @nsgpriyanshu,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
