### ISSUE TITLE
Node engine not using latest minor version

### ISSUE THREAD

**Issue by ohararyan** [zeit/now#11814]
I have a Next.js site that is failing on deployment. 

My original issue stems from the latest `lru-cache` module that I believe Vercel's using under the hood. This has had a number of engines updated, with node 20 being forced to use `>= node@18.20` see https://github.com/isaacs/node-lru-cache/issues/340

![CleanShot 2024-07-09 at 12 09 21](https://github.com/vercel/vercel/assets/1509309/a47b5acb-fe33-4164-9c4a-5c154651137e)

I have tried removing the `engines` from the `package.json` but this still throws the same error as above.
If I fix the version to the latest node version I get the below error.

```
  "engines": {
    "node": "18.20.4"
  }
```

![CleanShot 2024-07-09 at 12 05 57](https://github.com/vercel/vercel/assets/1509309/ed13ddf1-c1ab-4110-b6ae-6240d28f8783)

Is Vercel locked to version 18.19.1? 

My understanding is that the `18.x` runtime should be using the latest minor/patch version as per https://vercel.com/docs/functions/runtimes/node-js#default-and-available-versions

**Comment by trek** [comment]
Hi @ohararyan,

We trail slightly as we test but current `18.x` for node is `18.20.4` as of 24 July.
