### ISSUE TITLE
need update : some of the packages nextjs use has been deprecated

### ISSUE THREAD

**Issue by Shresthaprakash75** [zeit/now#11854]
Hello NextJS Team,

Today I was looking into updating npm packages of my project built with nextjs.
And found out some of the package nextjs are using has been deprecated.
I've attached the screenshot of it. 

<img width="1440" alt="Screenshot 2024-07-15 at 21 11 52" src="https://github.com/user-attachments/assets/e1b88a8e-0861-41b0-a12e-9298058f9413">

when can we expect it to be updated?
or has there been any contribution from the community on it? yet
else i can help on it as well

cheers

**Comment by trek** [comment]
Hi @Shresthaprakash75 

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
