### ISSUE TITLE
ERROR: Could not resolve "assert", "stream", "url" when deploy app to Vercel

### ISSUE THREAD

**Issue by juniorforlife** [zeit/now#11902]
#### Environment details
  - Vercel Node.js version: 18x
  - Package manager: Bun 1.1.7
  - `@google-cloud/firestore` version: ^7.9.0

#### Steps to reproduce

  1. Install and use @google-cloud/firestore
  2. Deploy my SvelteKit app to Vercel
  3. Deployment will fail with this error. Note I'm not using edge functions 
  ```
error during build:
Error: Build failed with 78 errors:
node_modules/@google-cloud/firestore/build/src/aggregate.js:20:23: ERROR: Could not resolve "assert"
node_modules/@google-cloud/firestore/build/src/bulk-writer.js:4:23: ERROR: Could not resolve "assert"
node_modules/@google-cloud/firestore/build/src/document.js:20:23: ERROR: Could not resolve "assert"
node_modules/@google-cloud/firestore/build/src/index.js:19:25: ERROR: Could not resolve "stream"
node_modules/@google-cloud/firestore/build/src/index.js:20:22: ERROR: Could not resolve "url"
```

**Comment by trek** [comment]
Hi @juniorforlife, We're in the process of migrating to our new community platform. If you're still seeing this issue, can head over to https://vercel.community and ask there? Thank you!
