### ISSUE TITLE
[WARNING:CLI] The `punycode` module is deprecated

### ISSUE THREAD

**Issue by mar-js** [zeit/now#11905]
The problem is when running vercel from the terminal:

![Captura de pantalla 2024-07-26 a la(s) 5 07 54 p  m](https://github.com/user-attachments/assets/f10d1680-1bdf-4a78-8525-34307fd15d93)

Looking at the [Node.js documentation](https://nodejs.org/api/punycode.html), it is already documented that said dependency (Punycode) is deprecated.

This **warning** was also reported when running the [serve command](https://github.com/vercel/serve/issues/802).

My versions:
`Node v22.5.1`
`Vercel v35.2.1`

**Comment by orangejx** [comment]
the same...

**Comment by pcgeek86** [comment]
I'm getting the same error. Updated the Vercel CLI to the latest version, and it's still showing up.

- Windows 11
- Node v22.5.1
- vercel@35.2.4

Previously had `vercel@32.3.1` before updating.

```
vercel --version
(node:29608) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:29608) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
Vercel CLI 35.2.4
35.2.4
```

**Comment by trek** [comment]
Hi @mar-js,

We currently [support Node.js 20.x, 18.x, and 16.x ](https://vercel.com/docs/functions/runtimes/node-js/node-js-versions) and suggest matching your local development in a project to whichever of those is used for your deployments. We'll remove this dependency as part of our upgrade to Node 22.

If the deprecations warnings are bothersome you can hide them with `NODE_NO_WARNINGS=1`. The specifics of how to to do this as a configuration option will vary depending on how you manage your node installs locally.

**Comment by mar-js** [comment]
Hello @trek. Thank you bro! 🇦🇷
