### ISSUE TITLE
[Bug] Vercel failed to build go serverless functions with go >= 1.21

### ISSUE THREAD

**Issue by xjasonlyu** [zeit/now#11976]
Currently, vercel fails to build any golang serverless functions when using go1.21 or later, it outputs:

```
go: module . listed in go.work file requires go >= 1.21, but go.work lists go 1.18; to update it:
        go work use
go: module ../../../.. listed in go.work file requires go >= 1.21, but go.work lists go 1.18; to update it:
        go work use
Error: Command failed: go build -ldflags -s -w -o ./vercel-dev-server-go ./...
go: module . listed in go.work file requires go >= 1.21, but go.work lists go 1.18; to update it:
        go work use
go: module ../../../.. listed in go.work file requires go >= 1.21, but go.work lists go 1.18; to update it:
        go work use
Error: Command failed: go build -ldflags -s -w -o ./vercel-dev-server-go ./...
```

I believe it's caused by vercel's `go.work` generation here:

https://github.com/vercel/vercel/blob/4052e9b8c61df1bd3d716bfa7a10417834992f46/packages/go/src/index.ts#L785-L790

where it should include the go directive (e.g. `go 1.21.0`) at the top of the generated `go.work` file.

**Comment by xjasonlyu** [comment]
Similar discussions:
- https://github.com/vercel/vercel/discussions/10941
- https://github.com/orgs/vercel/discussions/5858
- https://github.com/orgs/vercel/discussions/5166

**Comment by xjasonlyu** [comment]
cc @TooTallNate, @StefMa

Although vercel supports go1.21/go1.22, it actually never builds if go.mod uses go.21 or higher.

I believe that only a small change in the logic of go work generation, by explicitly including the go version in the `go.work` file, should be able to fix this issue.

**Comment by StefMa** [comment]
If I get it right it only fails locally with `vercel dev`, correct?

**Comment by xjasonlyu** [comment]
oh yep, it looks like a local issue with `vercel dev`👀

**Comment by RusseII** [comment]
SAME ISSUE

**Comment by StefMa** [comment]
Might be because of this change https://tip.golang.org/doc/go1.21#tools

Can someone test the behavior if you add `toolchain go1.21.0` to your go.mod file? 🤔

Might temporarily fix the problem...

**Comment by alexflint** [comment]
> Can someone test the behavior if you add `toolchain go1.21.0` to your go.mod file? 🤔

Nope, doesn't help

**Comment by RusseII** [comment]
Any updates?

**Comment by StefMa** [comment]
No updates. 😔 

But meanwhile I found [this](https://github.com/vercel/vercel/discussions/10941#discussioncomment-9256422comment) by @michael-freling and the solution he posted there should be correct. 

The "problem" is that go uses language versions until 1.21 and semver version starting with 1.21. So we might have to wait until #11064 is merged. 🤔

**Comment by jeffreywescott** [comment]
Looks like that PR got merged, and I'm on the latest version, but still getting this error when using `vercel dev` locally.

**Comment by StefMa** [comment]
Hmm.. sad.

I guess the best solution is what initially requested [here](https://github.com/vercel/vercel/discussions/10941#discussioncomment-9256422). Copy the go (and/or toolchain) thing to the `go.work` file.
He even posted a bit code that looks quite good: https://github.com/vercel/vercel/commit/68741d49acb06eafb886fda38f79727d2988415d

**Comment by DavidChouinard** [comment]
Eagerly awaiting for #12574 - thanks for addressing @eprosimon

**Comment by StefMa** [comment]
#12574 was just merged 🤘
Someone can test the latest release and then close this issue if it works 🚀

**Comment by eprosimon** [comment]
vercel@39.0.3 does not yet does not yet contain the fix, so it would need to be the next release after that number. 
@DavidChouinard please keep an eye out for that.
@jeffreywescott Could you also attempt the next release on your workload. 
@StefMa I would Ideally prefer 2 independent tests before we close, If there are any specific issues that anyone has I would like to add additional test cases.

**Comment by jeffreywescott** [comment]
Yes -- I'll keep an eye out for a new release [here](https://github.com/vercel/vercel/releases) and then give it a whirl!

**Comment by eprosimon** [comment]
@jeffreywescott @DavidChouinard @alexflint @RusseII 
The fix is present in the latest version of the CLI, are you able to test and report back, whether it is working or if there are still any issues you face that appear to be related to the go version.

**Comment by StefMa** [comment]
I can report back that `vercel dev` works again.
I tested it with [this project](https://github.com/StefMa/AppVersions) and [this branch](https://github.com/StefMa/AppVersions/pull/85). 

vercel cli version used: `39.1.0`
go version: `1.23.3`

**Comment by jeffreywescott** [comment]
I can also confirm that it works for me now. Thank you for this!

**Comment by eprosimon** [comment]
Perfect, thanks for the testing @StefMa and @jeffreywescott.
With 2 independent reports of it working I will close this issue out for now 🤠
