### ISSUE TITLE
vercel.com can’t be reached. vercel.com took too long to respond.

### ISSUE THREAD

**Issue by Praskand** [zeit/now#11973]

**Comment by dev1abhi** [comment]
By any chance ,is your ISP Vodafone?

**Comment by ugurcoskn** [comment]
My ISP is turktelekom, and i cant reach it neither

**Comment by trek** [comment]
Hello @Praskand Thanks for bringing this to our attention! Our community site has some resources for this issue: https://vercel.community/t/resolving-ip-blocking-issues/171

I've also let our internal customer service team know and they're looking into it. If this issue persists after a few days, please open a new discussion on https://vercel.community and we can help further.

**Comment by trek** [comment]
@Praskand if you're able, could run this curl request and share the `vercel-debug.txt` output file with us on a new post on [vercel.community](https://vercel.community/) so we can see where it fails? 

When complete, it will create a vercel-debug.txt file in the current working directory where the curl was run, which you then can attach to the community post:

# Mac/Linux (Bash/ZSH):
```
curl -s https://raw.githubusercontent.com/vercel-support/vercel-connect-debug/main/vercel-debug.sh | bash | tee vercel-debug.txt
```

Windows 10/11 (Powershell):

```
Invoke-RestMethod -Uri https://raw.githubusercontent.com/vercel-support/vercel-connect-debug/main/vercel-debug.ps1 | Invoke-Expression | tee vercel-debug.txt
```
