### ISSUE TITLE
Navbar alignment issue in Vercel Templates Marketplace Submission Form

### ISSUE THREAD

**Issue by Arindam200** [zeit/now#12014]
## Description:
There is an alignment problem in the navbar of the "Vercel Templates Marketplace Submission Form" page. Specifically, the elements in the top right corner (Contact, Dashboard, and Profile image) are not aligned correctly.

## Steps to reproduce:
1. Navigate to https://vercel.com/templates/submit
2. Observe the navbar at the top of the page

## Current behavior:
The Contact link, Dashboard link, and Profile image in the top right corner of the navbar are misaligned.
![image](https://github.com/user-attachments/assets/87c4edb9-a9fc-44a9-b14c-65b20956fa4d)

## Expected behavior:
These elements should be properly aligned horizontally in the top right corner of the navbar.
![image](https://github.com/user-attachments/assets/dbf27db5-eb3b-4b71-b4ae-1d21532bb71d)

## Visual reference:
![image](https://github.com/user-attachments/assets/e480915b-eea3-48b5-a562-cfb82ce2d4c3)

## Additional information:
- Browser: Chrome
- Operating System: Windows

## Note to Maintainers:

I would like to work on this issue.

**Comment by trek** [comment]
Hi @Arindam200,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.

**Comment by Arindam200** [comment]
Oh Okay, Thanks a lot
