### ISSUE TITLE
vercel remove --safe no longer preserving rollback deployment

### ISSUE THREAD

**Issue by cosn** [zeit/now#12022]
When running `vercel rm -s`, in addition to the active deployment, the previous deployment was also be kept, such that rollbacks could still work. That was very convenient for cleaning up old deployments while not also nuking the ability to rollback.

With some of the recent refactoring (#11931 #11394), only the active deployment is now kept.

Happy to submit a PR that brings back that behavior, assuming that's deemed desirable (cc @erikareads).

**Comment by trek** [comment]
Hey @cosn,

If you have a fix already identified that would be great, otherwise we can dig in.

**Comment by cosn** [comment]
Happy to do it, just wanted to check that's the desired behavior. Alternatively could do this via a `-S` flag to differentiate, but I cant imagine people would prefer to not have a rollback. 

I'll file a PR on this and tag you, thanks!

**Comment by trek** [comment]
@cosn could you try going back to a last known good (from your perspective) cli version? It's also possible this was an API change.

**Comment by trek** [comment]
@cosn do you recall the last know good (for your use) cli version? I've gone back a month and can't get see any differences in the call we make to the vercel API. Could you try going back to that previous version and seeing if still has the issue?

It's possible there was a regression at the API and I want to be sure to direct this to the correct team.

**Comment by cosn** [comment]
You're right that it might have been the API. That said, it's also pretty simple to fix in the cli if you guys prefer, here's the PR for that. Up to you ofc :)

**Comment by trek** [comment]
@cosn that is true, but not everyone can update to latest cli and not everyone uses the cli. Were you able to reproduce this with a last known-good cli version?

**Comment by cosn** [comment]
No, I went all the way down to [33.7.0](https://github.com/vercel/vercel/releases/tag/vercel%4033.7.0) and the behavior is the same, so I suspect you're right there was an API change. I'd probably suggest both, since the cli can help mitigate future regressions, and fixing the API helps older clients.

**Comment by TooTallNate** [comment]
Our of curiosity, what are your motivations for using the `--safe` flag? I find it difficult to understand the use-case.

**Comment by cosn** [comment]
Clean up stale deployments. It's probably my OCD more than anything else, but after a few days/weeks I just like to get rid of the clutter

**Comment by cosn** [comment]
Any updates on this?

**Comment by trek** [comment]
@cosn we're trying to track down an API change that would have caused this and can't identify an issue. This may be a bit more of a feature request and we'd need to discuss this with the team. It's probably best to re-raise this issue as a new discussion at https://vercel.community.
