### ISSUE TITLE
Vercel Build Fails to Locate Next.js Version and Routes Manifest in Custom `distDir`

### ISSUE THREAD

**Issue by KernelPanic92** [zeit/now#12031]
**Description:**
I'm working on a Next.js project within a monorepo, and I've set `distDir` to "dist" instead of the default ".next". The Next.js project resides in a subdirectory of the monorepo, not in the root. Here's the configuration I'm using for the Vercel build:

- **Command:** `vercel build --prod --local-config applications/backoffice --token="$VERCEL_TOKEN"`
- **Project Structure:** The Next.js app is located in `applications/backoffice`.
- **Vercel Configuration (vercel.json):**

```json
{
    "version": 2,
    "regions": ["cdg1"],
    "framework": "nextjs",
    "buildCommand": "pnpm nx run backoffice:build",
    "outputDirectory": "applications/backoffice/dist",
    "name": "backoffice"
}
```

With this configuration, Vercel fails to detect the Next.js version. Why is this happening? Am I missing something in the setup?

---

**Attempted Solution:**

I tried updating the `vercel.json` as follows to specify the Next.js build setup:

```json
{
    "version": 2,
    "regions": ["cdg1"],
    "framework": "nextjs",
    "buildCommand": "pnpm nx run backoffice:build",
    "outputDirectory": "applications/backoffice/dist",
    "name": "backoffice",
    "builds": [
      {
        "src": "applications/backoffice/package.json",
        "use": "@vercel/next",
        "config": {
            "distDir": "applications/backoffice/dist"
        }
      }
    ]
}
```

With this change, Vercel successfully identifies the Next.js version. However, I encounter the following error during deployment:

```
Error: The file "/builds/***/***/applications/backoffice/.next/routes-manifest.json" couldn't be found. This is often caused by a misconfiguration in your project.
```

It seems Vercel is still looking for the `routes-manifest.json` in the default `.next` folder, even though I've specified the `distDir` correctly. Why is this happening, and how can I resolve this misconfiguration?

Any guidance or suggestions on how to resolve this would be much appreciated!

**Comment by trek** [comment]
Hi @KernelPanic92,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
