### ISSUE TITLE
How to have auto-deploy of specific branches only?

### ISSUE THREAD

**Issue by Husain010** [zeit/now#12043]
I want auto-deploy enabled for specific branches only, so how can this be enabled?

How am I supposed to understand this gobblygoop
https://vercel.com/knowledge/how-do-i-use-the-ignored-build-step-field-on-vercel
I just need build branch A, B and C, no previews.
How to do.
Thanks

_Originally posted by @GaddMaster in https://github.com/vercel/vercel/discussions/4419#discussioncomment-2803892_

**Comment by trek** [comment]
Hi @Husain010,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
