### ISSUE TITLE
Cronjobs are too limited

### ISSUE THREAD

**Issue by janwilmake** [zeit/now#12058]
I'm on the hobby plan and have some feedback about cron-jobs on vercel.

- If you put a cronjob of anything else than a day, you get a 'deployment failed' without any further info in GitHub, and the deployment doesn't show up in Vercel. See https://github.com/vercel/vercel/issues/10894
- If you have a cronjob that returns a readable stream with `headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-cache", Connection: "keep-alive" }` (NB: any cronjob that takes more than 1 minute needs this). It doesn't finish. It just seems to wait until the response comes back, but doesn't wait for the stream to finish. The docs on this are misleading.
- I can't find anything about CRON jobs in the hobby plan being this limited in the docs. On https://vercel.com/docs/cron-jobs it states "Cron Jobs are available on [all plans](https://vercel.com/docs/accounts/plans)" and there is no further information. This is not nice as if I had known these limitations, I would've gone for another solution.

I hope you will improve your transparency and maybe fix the streaming problem. For now I'll move my jobs to https://www.inngest.com

**Comment by trek** [comment]
Hi @CodeFromAnywhere,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
