### ISSUE TITLE
NextJS Memory Leak Issue: npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory.

### ISSUE THREAD

**Issue by amardiyab** [zeit/now#12060]
I encountered a problem while setting up a new Next.js project using the latest version (`14.2.7`) of `create-next-app` via the following command:

```bash
npx create-next-app@latest
```

During the installation process, several warnings were displayed regarding deprecated dependencies. These deprecated dependencies seem to cause significant issues, including memory leaks and severely degraded performance of the development server. As a result, the local server runs noticeably slower than expected.

This is particularly impacting the development experience, as the slow performance hinders productivity and the memory leaks pose a potential risk to stability over extended usage.

# Steps to Reproduce:

Run npx create-next-app@latest.
Observe the deprecated dependency warnings during the installation process.
Start the development server and notice the slow performance and increased memory usage over time.
Expected Behavior:

The installation process should complete without warnings related to deprecated dependencies. Additionally, the development server should run smoothly without causing memory leaks or performance degradation.

# Actual Behavior:

Deprecated dependency warnings are shown during installation.
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

The development server is noticeably slow and experiences memory leaks.

# Additional Information:

It would be great if these deprecated dependencies could be updated or replaced to ensure optimal performance and stability. Thank you for your attention to this issue.

**Comment by MohamedDanis** [comment]
i had the same issue while development, with memory leakage

**Comment by trek** [comment]
Hi @AmarDiyab,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
