### ISSUE TITLE
Error: The Edge Function "api/chat" size is 2.65 MB. gettting this issue in ts file but on converting to js it works

### ISSUE THREAD

**Issue by auspy** [zeit/now#12097]
for some reason i get this issue only in typescript routes. when converting to javascript they start working

**Comment by trek** [comment]
Hi @auspy,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
