### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by raunakbaliyan101** [zeit/now#12106]
![bug1](https://github.com/user-attachments/assets/0c756c44-f626-4512-9ea6-28be7907a28e)

UI issue please fix this, else hire😊😊😊😊

**Comment by trek** [comment]
Hi @raunakbaliyan101,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
