### ISSUE TITLE
Can't access Vercel hosted website

### ISSUE THREAD

**Issue by ggukggukee** [zeit/now#12118]
Can't access Vercel hosted website in KZ.
ISP told me they don't block 76.76.21.21

**Comment by developerjhp** [comment]
It sounds like you might be facing a DNS issue.
 I’ve worked on an open-source project called `Vercel DNS ISP Block Watch Dog` that could help you diagnose this.

The tool monitors whether domains deployed via Vercel are accessible through multiple ISPs by checking DNS resolution. While your ISP claims they’re not blocking the IP (76.76.21.21), DNS issues can still cause problems. My tool could help you verify whether DNS is the culprit by regularly testing your domain’s accessibility.

You can check out the project here: [Vercel DNS ISP Block Watch Dog](https://github.com/developerjhp/vercel-dns-isp-block-watch-dog). It also sends alerts via Slack if any issues arise, so you can stay updated.

Feel free to try it out and see if it helps pinpoint the issue in Kazakhstan. Let me know if you need any assistance with setting it up!

**Comment by trek** [comment]
Hi @ggukggukee,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.

**Comment by ggukggukee** [comment]
> Hi @ggukggukee,
> 
> Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.

I already opened a discussion about it two days ago but no one responded. Also I contacted with Vercel Customer Support and still waiting for a respond. I mean my website is already down 4 days and my clients can't access it without VPN and there is no help around.

**Comment by Liz-Lovelace** [comment]
Yep, most websites deployed with vercel are inaccessible to me in Kazakhstan, can't even access vercel.com 

Tried it through two different ISPs, neither works. Using a VPN works.

**Comment by amaechichisom** [comment]
Does anyone have a viable solution to this issue or must one use cloudflare

**Comment by githero20** [comment]
Same for me in Nigeria. I complained about this same issue in a GitHub discussion 3 years ago. Sad to see that the same issue still persists.

**Comment by Jeon316upzx** [comment]
I am currently having the same issue on a website deployed on Vercel? Some ISPs can open it, but most can't

**Comment by klever34** [comment]
Currently facing this same issue, any help on this?

**Comment by Jeon316upzx** [comment]
Just deploy on Netlify, Vercel <<<

**Comment by amaechichisom** [comment]
How I solved this is to use cloud flare as a proxy. Or any other similar service if you want to use vercel for production

**Comment by CourageBobby1110** [comment]
i am having the same issue as well. @Jeon316upzx, i have a question. By deploying on Netlify, will this issue be resolved, thank you.

**Comment by githero20** [comment]
@CourageBobby1110 Yes, with Netlify this issue does not persist. If you can, consider using cloudflare with your Vercel site. This also resolves the issue.
