### ISSUE TITLE
NextJs Discord Bot not working for no reason.

### ISSUE THREAD

**Issue by 0ni-x4** [zeit/now#12113]
I'm making a NextJs discord bot AI script generator.
My code: https://gist.github.com/Xoni30/cd5146b9a1917a41c878bc75a872f9a6/
Following this guide: https://github.com/jzxhuang/nextjs-discord-bot/

There's no errors/error logs on vercel whatsoever and I'm on vercel pro so it shouldn't timeout the request and it didn't say it timed out the request I'm just so confused.

(I set up a webhook for logging so i can see the logs on discord) 

![image](https://github.com/user-attachments/assets/49af7a4d-de2e-4bb9-a8c4-f9f42fe1eac5)

After this nothing shows up. And i have no idea what to do, I've been stuck trying to fix this in days.

**Comment by trek** [comment]
Hi @Xoni30,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
