### ISSUE TITLE
Github repo `about` does not get updated when the prod URL gets updated 

### ISSUE THREAD

**Issue by Ebrahim-Ramadan** [zeit/now#12197]
just updated the domain of my website, imported from github repo, then the `about` of my repo gets changed to the domain URL, I manually changed the domain URL, but the about is still the old URL. I kinda hope this would be auto

**Comment by trek** [comment]
Hi @Ebrahim-Ramadan,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
