### ISSUE TITLE
Site only takes business emails, can't reach out about the 1000 scams we receive on our discord servers using VERCEL as platform.

### ISSUE THREAD

**Issue by Offline-R503B** [zeit/now#12192]
As title. 

Additionally : Content moderation is a thing,

**Comment by trek** [comment]
Hi @Offline-R503B,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
