### ISSUE TITLE
Issue with PostMessage Communication Between Host App and Embedded Iframe

### ISSUE THREAD

**Issue by AhmedMalekX** [zeit/now#12469]
## Summary:
I am experiencing difficulties with postMessage communication between my host application and an embedded iframe in my Vercel project.

## Introduction:
I have the following setup in my Vercel project:

The host application is running at random-host-url.com.
Another application deployed at random-iframe-url.com is embedded inside an iframe in the host application, configured as follows:

```html
<iframe
  ref={iframeRef}
  name=""
  src="https://random-iframe-url.com"
  width="100%"
  height="100%"
  className="w-full h-full"
></iframe>
```

## The Problem:
Messages sent from the host application to the iframe are not being received as expected. The message sending code is implemented as follows:

```js
try {
  iframeRef.current.contentWindow.postMessage(message, 'https://random-iframe-url.com');
} catch (error) {
  console.error('Failed to send message to iframe:', error);
}
```

While this functionality works perfectly during local testing, it fails to operate correctly when deployed on Vercel. I have checked the console for errors but did not find any relevant information. As a result, no response is received in the iframe from the host app.

I would greatly appreciate any assistance in debugging and resolving this issue. Thank you for your help!

**Comment by trek** [comment]
Hi @AhmedMalekX,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and its related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
