### ISSUE TITLE
typo in Slack integration popup/modal

### ISSUE THREAD

**Issue by htelsiz** [zeit/now#12534]
get's instead of gets -- see attached:

<img width="468" alt="Screenshot 2024-11-06 at 6 27 46 PM" src="https://github.com/user-attachments/assets/69c8029b-765c-4bd3-84f0-658d2d24a52a">

If this isn't the right place for this, let me know :)

**Comment by trek** [comment]
Hi @htelsiz 

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and its related libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
