### ISSUE TITLE
Vercel application installed to GitHub, but cant see/import any repos

### ISSUE THREAD

**Issue by clementfranz** [zeit/now#12561]
### Discussed in https://github.com/vercel/vercel/discussions/5755

<div type='discussions-op-text'>

<sup>Originally posted by **code-press** January 27, 2021</sup>
I have my app hosted at GitHub, and am trying to import it (into my team account).  I select the "Add GitHub org or account" option.  pops the auth window and I got through auth, window closes.  but the page never adds my account or lets be browse the repos so I can add them.  Tried both safari and chrome, and multiple GitHub accounts to no avail. 

Any ideas?</div>

Previous forum is already locked. But I found a solution on my side. The github account linked to my vercel account should be the same github account to which you get link an specific repo. I hope this helps

**Comment by trek** [comment]
Hi @clementfranz,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
