### ISSUE TITLE
Prebuilt deployments fail to deploy with `39.0.3`

### ISSUE THREAD

**Issue by juancampa** [zeit/now#12607]
We just noticed our CI was failing the only difference was the version of vercel CLI.

Compare 39.0.2 vs 39.0.3:
```
Vercel CLI 39.0.3
Retrieving project…
Deploying [redacted]
Inspect: [redacted] [975ms]
Production: [redacted] [975ms]
Queued
Building
Error: The specified Root Directory "site" does not exist. Please update your Project Settings.
```

```
Vercel CLI 39.0.2
Retrieving project…
Deploying [redacted]
Uploading [--------------------] (0.0B/7.3MB)
Uploading [=====---------------] (1.8MB/7.3MB)
Uploading [==========----------] (3.7MB/7.3MB)
Uploading [===============-----] (5.5MB/7.3MB)
Uploading [====================] (7.3MB/7.3MB)
Inspect: [redacted] [8s]
Preview: [redacted] [8s]
Queued
Building
Completing
To deploy to production (www.membrane.io), run `vercel --prod`
```

We pinned our CLI to 39.0.2 as a work-around.

This change seems like it could be related as it specifically mentions `--prebuilt` deploys #12598

Cheers!

**Comment by Roman-Ka** [comment]
Same issue here

**Comment by juankysoriano** [comment]
Same, pinning to 39.0.2 works as a workaround...

**Comment by TooTallNate** [comment]
Try 39.0.4 please

**Comment by juankysoriano** [comment]
ty! I was just about to ask that.

https://github.com/vercel/vercel/releases/tag/vercel%4039.0.4

This seems to be fixing it according to release notes

**Comment by juankysoriano** [comment]
39.0.4 is working correctly

**Comment by trek** [comment]
@juancampa  / @juankysoriano glad to hear it! We'll close this issue out. Thank for for the reporting _and_ pointing us directly to the offending commit ❤️
