### ISSUE TITLE
Very slow requests - preflight (OPTIONS) issue with CORS

### ISSUE THREAD

**Issue by bennyschmidt** [zeit/now#12670]
All my Vercel apps that make HTTP requests with payloads to other domains take 5+ seconds on the first invocation. 

When looking in the Network tab there is a preflight (HTTP OPTIONS) request that hangs at *pending* for several seconds - only on CORS requests with a JSON payload.

In situations I control the other server, I can add this high up the Express request handler chain:

```
      if (req.method === 'OPTIONS') {
        return res.send(200);
      }
```

^^^ This "solves" the problem because the app is very snappy now, though it reports that the OPTIONS just didn't work in the front-end (though, it does).

![Screenshot from 2024-11-27 08-03-51](https://github.com/user-attachments/assets/2000954f-24f5-477f-8dea-939a0840bcbc)

However, I don't always have this level of control over 3rd party resources.

In any case, none of this occurs when the React app is deployed anywhere else, only on Vercel. That long of a load time isn't acceptable for my customer.

**Comment by trek** [comment]
Hello @bennyschmidt,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.

**Comment by bennyschmidt** [comment]
@trek This is an issue with Vercel CLI - particularly building and deploying. 

Your CTO told me "the Vercel repo is not monitored" - maybe consider removing the Issues from this repo settings? Seems a lot of people open issues here. 

Though most developers will probably prefer GH to that subreddit/forum type community because moderators are so terrible.
