### ISSUE TITLE
Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {   digest: 'DYNAMIC_SERVER_USAGE',

### ISSUE THREAD

**Issue by ghost** [zeit/now#12691]
I do not understand why always 500 internal server error
dynamic route does not work

![error2](https://github.com/user-attachments/assets/9b176e73-e627-4e7f-8195-6689da47344b)
![error](https://github.com/user-attachments/assets/54f28453-864a-415b-80de-cac91c9a8637)

**Comment by trek** [comment]
Hi @jayrick-gacayan ,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
