### ISSUE TITLE
Vercel Deployment Serves .js File Instead of Running Node.js Server

### ISSUE THREAD

**Issue by TobaSenju** [zeit/now#12715]
Description:
Deployed a Node.js/TypeScript/Express server to Vercel. While it works with vercel dev, the production URL serves the raw .js file instead of running the server.

Expected Behavior:
The server should execute and handle HTTP requests in production.

Steps to Reproduce:

Deploy the server to Vercel.
Access the production URL.
Environment:

Node.js
TypeScript
Express
Vercel Production

**Comment by trek** [comment]
Hi @TobaSenju,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
