### ISSUE TITLE
Minor typo on Production environment settings

### ISSUE THREAD

**Issue by seshxn** [zeit/now#12790]
Just noting a minor typo in the Production environment settings :)

![image](https://github.com/user-attachments/assets/d2c84625-c670-43ca-a33c-15db971652b6)

Probs low-hanging fruit for someone new to take on?

**Comment by trek** [comment]
Hi @seshanpillay25,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and its related libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
