### ISSUE TITLE
Error! An unexpected error occurred in deploy

### ISSUE THREAD

**Issue by lonelydatum** [zeit/now#1514]
When I run "now" I get this error. Does anyone know what this means and how to resolve it?

> Upload [======--------------] 30% 0.7s (94.99MB) [1869 files]> Error! Upload failed
> Error! An unexpected error occurred in deploy: Error: Rate limit exceeded (429)
    at responseError (/snapshot/repo/dist/now.js:2564:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by timothyis** [comment]
Great @lonelydatum! I'll go ahead and close this issue now.

If anyone is still experiencing this, please leave a comment.

**Comment by timothyis** [comment]
@grangerjs @colinmeinke are you both on [Now 2.0](https://zeit.co/docs/v2/platform/overview/#versioning)?
