### ISSUE TITLE
Getting a 'storage.objects.create' access error on GCP deployment

### ISSUE THREAD

**Issue by eoinmurray** [zeit/now#16]
Yo!,

Tried to deploy the example microservice to our GCP account and got 

```
Error! Caller does not have storage.objects.create access to bucket now-deployments.
```

When I check the bucket 'now-deployments' doesn't exist, so not sure what I'm supposed to do with permissions.

Do I need to set special permissions on the account I logged in with?

**Comment by eoinmurray** [comment]
So 'now-deployments' is actually a Zeit bucket - so it appears that some permission issue that I cannot fix myself.

**Comment by nkzawa** [comment]
@rauchg @matheuss It looks bucket names must be globally unique, so just `now-deployments` wouldn't work 😂 
I'm not sure how the bucket names should be generated since there are some restrictions https://cloud.google.com/storage/docs/naming#requirements
