### ISSUE TITLE
now@8.0.0-beta.1 [subcommand] fails

### ISSUE THREAD

**Issue by remy** [zeit/now#17]
I've run `now aws login` and created new credentials, these are successfully saved in `~/.now/auth.json`.

I've deployed successful (in theory) with `now` to aws (though it [returns a 500](https://atse1q3lw1.execute-api.us-west-1.amazonaws.com/now) - I'll follow up separately). However, any other command fails:

<img width="1280" alt="screen shot 2017-07-13 at 16 30 01" src="https://user-images.githubusercontent.com/13700/28174145-8b17a9ca-67e8-11e7-8c41-9236430b0cda.png">

I've then tried to switch back to now.sh, using `now sh login` - which was successful, but running `now` in a directory deploys using the AWS target.

**Comment by jdan** [comment]
(fwiw same issue on the 500 - looking forward to your issue so I can 👍 it too!)

**Comment by nkzawa** [comment]
Unfortunately, these subcommands are not implemented yet. We're working on it!

**Comment by remy** [comment]
Should I even be able to deploy to aws using now? Only because that failed
too with a 500 with a simple hello world.

**Comment by nkzawa** [comment]
@remy Umm, that should work. Let us know error messages and how your files look like if possible.
I just confirmed putting `server.js` to a dir and `now .` work fine for me.

```js
// server.js
require('http').createServer((req, res) => {
  res.end('Hello World!');
}).listen(process.env.PORT);
```

**Comment by darknoon** [comment]
@nkzawa I filed this issue since I'm having the same issue https://github.com/zeit/now/issues/57

**Comment by leo** [comment]
This issue was moved to zeit/now-cli#778
