### ISSUE TITLE
Autocomplete login acts funny.

### ISSUE THREAD

**Issue by bryanhelmig** [zeit/now#23]
When I type `bryan@zapier.com` as my email, it autocompletes `@zeit.co`, but then adds the `eit.co` to the end of the address after I complete finishing our domain.

```
➜  ~ now login
> Enter your email: bryan@zapier.comeit.co
```

If the `^` carrot is me pushing enter, it visually parses to something like this `bryan@zapier.com^eit.co`.

**Comment by rauchg** [comment]
Sounds like an issue in https://github.com/zeit/email-prompt, for whoever wants to take a look!

**Comment by leo** [comment]
This issue was moved to zeit/now-cli#779
