### ISSUE TITLE
Extrange error in server  (internal/streams/legacy.js:59)

### ISSUE THREAD

**Issue by tomyo** [zeit/now#28]
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: write EPROTO 140217767479104:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:769:

    at exports._errnoException (util.js:1018:11)
    at WriteWrap.afterWrite (net.js:800:14)

**Comment by leo** [comment]
This issue was moved to zeit/now-cli#780
