### ISSUE TITLE
Add kubernetes backend

### ISSUE THREAD

**Issue by rauchg** [zeit/now#3]

**Comment by rosskukulinski** [comment]
@rauchg let me know if you have questions regarding the Kubernetes ecosystem and/or APIs.  I'm loving the progress you're making with the Now Universal announcement today.

**Comment by raphaelkross** [comment]
@rauchg any specific place where Kubernetes support is being planned? Would love to contribute w/ that, in fact, I was working in something like that - but would love put my effort on this project instead.

**Comment by leo** [comment]
This issue was moved to zeit/now-cli#767
