### ISSUE TITLE
Building source / npm install fails.

### ISSUE THREAD

**Issue by e-beach** [zeit/now#34]
A host of errors comes with running `npm install`.

`yarn run test` still errors-out on legacy code despite e061c9b.  Adding a` .eslintignore` file for legacy files fixes it.

After this change, eslint still produes a bunch of errors:
```
$ yarn run test
yarn run v0.27.5
$ eslint . && flow

src/now.js:36
 36: const main = async argv_ => {
                                ^ undefined. This type is incompatible with the expected param type of
397: main(process.argv).then((code: number) => exit(code)).catch(handleUnexpected)
                                    ^^^^^^ number

src/now.js:54
 54:       return 0
                  ^ number. This type is incompatible with
 36: const main = async argv_ => {
                                ^ undefined

src/now.js:70
 70:     return 1
                ^ number. This type is incompatible with
 36: const main = async argv_ => {
                                ^ undefined

src/now.js:99

... etc.
```
You probably know why this is but I don't.

**Comment by e-beach** [comment]
Disabling tests and executing `./now.js` gives this error:
```
$ ./now.js 
> Error! An unexpected error occurred!
  TypeError: Cannot read property 'forwardNpm' of undefined
    at Object.main (/home/elliott/me/projects/now/out/providers/sh/deploy.js:248:28)
    at main (/home/elliott/me/projects/now/out/now.js:265:32)
    at <anonymous> TypeError: Cannot read property 'forwardNpm' of undefined
    at Object.main (/home/elliott/me/projects/now/out/providers/sh/deploy.js:248:28)
    at main (/home/elliott/me/projects/now/out/now.js:265:32)
    at <anonymous>
```

**Comment by nkzawa** [comment]
About eslint, I think only `out` dir is the issue ? https://github.com/zeit/now/pull/35 should fix.

**Comment by e-beach** [comment]
@nkzawa Pulled and it still doesn't work for me. The `src` directory is the problem. I know the `eslintignore` in `package.json` covers it but the `eslint` script seems to ignore it.

**Comment by nkzawa** [comment]
Fix flow errors https://github.com/zeit/now/pull/36

**Comment by e-beach** [comment]
Nevermind, `eslint` works on fresh clone.

**Comment by nkzawa** [comment]
@e-beach hmm I can't reproduce `TypeError: Cannot read property 'forwardNpm' of undefined` error. Let me know how to do that if possible.

**Comment by matheuss** [comment]
@e-beach what's the output of `cat ~/.now/config.json`?

**Comment by e-beach** [comment]
```
{
  "_": "This is your now credentials file. DONT SHARE! More: https://git.io/now-global-config"
}
```

**Comment by e-beach** [comment]
I removed the file and the same error occured.

**Comment by matheuss** [comment]
Hmmm interesting – we're populating `sh` there upon `now sh login` Did you edit it manually after?

**Comment by e-beach** [comment]
@matheuss Checked my bash history, and I deleted the file once but did not edit it.

**Comment by matheuss** [comment]
Right, then that's it 👍 Waiting on #37 to fix the behavior of the config file. Thanks for reporting! 🙌
