### ISSUE TITLE
Add caching logic similar to now-cli's

### ISSUE THREAD

**Issue by matheuss** [zeit/now#37]
In the current `now-cli` we have a logic to store the user details (username, email etc) with a TTL of 8h.

I didn't copy it over when copying the login/deployment code over because I want to improve it. I'd want `~/.now/cache.json`, that'd be used specifically to store stuff like that. Specially because username, for example, is not a configuration option – it depends on the API token.

@rauchg @nkzawa `~/.now/cache.json` sounds great? Also cc @leo, since we would share such file with Now Desktop 👌 

Assigning myself since I'd like to implement it and I implemented the current logic on `now-cli`, so it'll be trivial to do it here.

**Comment by leo** [comment]
This issue was moved to zeit/now-cli#783
