### ISSUE TITLE
AccessDenied when trying to deploy to AWS Lambda

### ISSUE THREAD

**Issue by callumlocke** [zeit/now#40]
I get this error when I do `now aws` (user details censored):

```
AccessDenied: User: arn:aws:iam::***********:user/********** is not authorized to perform: iam:GetRole on resource: role now-default-role
```

I'm not able to give total "AdministratorAccess" on my company's AWS account. I have to request a minimal set of permissions and wait to get it approved. From the above it looks like I need a policy that allows the `iam:GetRole` action. Can you tell me what other actions I need to allow? A minimal sample policy would be useful.

**Comment by babakness** [comment]
I had this error, I had to grant the right permissions for this work. What I did is create a new custom policy assigned to an API user then added permissions to that policy until it work. The one tricky thing for me was the API Gateway permissions, for which you might need to reference the exact resource, ie, `arn:aws:apigateway...`

**Comment by leo** [comment]
This issue was moved to zeit/now-cli#786
