### ISSUE TITLE
Use `pkg`

### ISSUE THREAD

**Issue by matheuss** [zeit/now#43]
We should use [zeit/pkg](https://github.com/zeit/pkg) in the same way we use it on [zeit/now-cli](https://github.com/zeit/now-cli)

**Comment by leo** [comment]
✅ 7e37d8825cd91fb8cc02afb57e7b207e0ce6a7f5 and d2617270bb5997a01cc092ba6e25eb8eca676d62 - WIP

**Comment by igorklopov** [comment]
There is a good PR pending. I think it would be great to merge it here https://github.com/zeit/now-cli/pull/727

**Comment by leo** [comment]
@igorklopov You said that:

> I am not sure that it helps.

If you do think that it helps, please open the PR here, if possible... 😊

**Comment by igorklopov** [comment]
Yes, it is definitely useful, as far as i understand how yarn cache works
https://github.com/zeit/now/pull/51
