### ISSUE TITLE
Add a system to notify the user about updates

### ISSUE THREAD

**Issue by matheuss** [zeit/now#44]
Even tho we'd like to have everyone running Now Desktop, we can't rely on it. We should have a system that notifies the user about updates. Not sure if any of the existent solutions will work for now, since we're at `8.0.0.beta-N`. I wonder if semver will consider `8.0.0.beta-2` bigger than `8.0.0.beta-1`, and then `8.0.0` bigger than any beta 🤔 

I think a simple `lastCheckedForUpdates` once we have #37 would be enough: we could fire a child process to do the check (and `unref()` it) if the last check was too long ago (e.g. 24h). If there's an update, the `unref`ed process would store something on #37's file that would then be displayed next time `now` is run.

**Comment by leo** [comment]
✅ 06f5ebf111b68bf084d7d835c7abca3a52bbdb38

We had it working on zeit/now-cli already, so I moved it over.
