### ISSUE TITLE
Secret being set incorrectly

### ISSUE THREAD

**Issue by captDaylight** [zeit/now#45]
setting a secret with:

`now secrets add email_pass "u5wV@#om$cLwAZC&mmlB3*2ly&Mm8bkv@54JOZ4N"`

is getting the secret passed to my app as:

`u5wV@#om&mmlB3*2ly&Mm8bkv@54JOZ4N`

I'll put them one on top of each other to inspect them easier, first the original and then the output.

```
u5wV@#om$cLwAZC&mmlB3*2ly&Mm8bkv@54JOZ4N
u5wV@#om&mmlB3*2ly&Mm8bkv@54JOZ4N
```

I fixed this by changing the value to only numbers and letters, but I imagine this is unexpected behavior.

**Comment by leo** [comment]
This issue was moved to zeit/now-cli#765
