### ISSUE TITLE
request: support deploying "stacks" via docker compose

### ISSUE THREAD

**Issue by jeffreywescott** [zeit/now#50]
Loving now (and Next.js, too). Thanks for all of the hard work.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Context

It's awesome that Now lets you deploy a Dockerfile. However, it would be amazing if you supported deploying a whole "stack" for an app via a set of `docker-compose.yml` (and similar) files.

Any plans to support such a scenario? It would be pretty amazing to have all of the load balancing and DNS handled by the standard Now stuff without having to resort to something like DigitalOcean and `docker-machine.

**Comment by gandulio** [comment]
Please add this!

**Comment by leo** [comment]
This issue was moved to zeit/now-cli#763
