### ISSUE TITLE
Deployment on AWS Lambda gives Code 500 Internal Server Error

### ISSUE THREAD

**Issue by darknoon** [zeit/now#57]
I tried deploying a really basic app just to make sure it wasn't my server misbehaving:

```
$ cat server.js
require('http')
	.createServer((req, res) => {
		res.end('Hello World!');
	})
	.listen(process.env.PORT);
```

I ran this command (my now beta is installed locally)

```
$ ../node_modules/.bin/now aws
> Deploying "~/Code/Lobe/lobe/src/frontend/test-deploy" (aws) (us-west-1)
✔ Build generated a 1.69kB zip [148ms]
✔ API resources created (id: "now-test-deploy-4eCnyDRqXH") [2s]
> Success! https://k4atst0laf.execute-api.us-west-1.amazonaws.com/now (in clipboard) [2s]

```

shows:

```{"message": "Internal server error"}```

**Comment by darknoon** [comment]
My now version is `8.0.0-beta.8`

I'm not sure how to check the logs from AWS; it doesn't seem to be showing up in cloudwatch.

**Comment by leo** [comment]
This issue was moved to zeit/now-cli#761
