### ISSUE TITLE
Can I define time-to-sleep?

### ISSUE THREAD

**Issue by gunar** [zeit/now#63]
Is there any setting I can configure how long to wait for requests before shutting down an instance?
Would love to be able to set it to as low as zero.

**Comment by TooTallNate** [comment]
Check out `now scale --help`. In short, you can specify a _minimum of 1 instance_ which will never put the deployment to sleep.

**Comment by gunar** [comment]
@TooTallNate That is the opposite of what I want. I want my instances to shut down faster.

**Comment by TooTallNate** [comment]
@gunar Oh sorry, I misread. So no, it's possible at this time to control the sleep scheduling algorithm for deployments.
