### ISSUE TITLE
Server Side Rendering not working for Angular Universal Project

### ISSUE THREAD

**Issue by elopez89** [zeit/now#6755]
### Discussed in https://github.com/vercel/vercel/discussions/6751

<div type='discussions-op-text'>

<sup>Originally posted by **elopez89** September 21, 2021</sup>
Is it possible to deploy an angular universal application onto vercel? I was able to successful deploy the application but it isn't being server-side rendered. You can tell by viewing the page source here: https://painter-quoting-cg3amwvqi-ppg-services-engineering.vercel.app/.  Is there a specific way i need to configure vercel in order to get this wired up correctly?

Project Settings:

![Screen Shot 2021-09-22 at 4 45 21 PM](https://user-images.githubusercontent.com/19472648/134419261-3691439f-94d5-4f2f-915b-c608ea08e717.png)

</div>

**Comment by jdgamble555** [comment]
I was able to accomplish this.  Hopefully Vercel will add it as an official template: https://dev.to/jdgamble555/how-to-deploy-angular-universal-to-vercel-31d0

**Comment by leerob** [comment]
Let's move the conversation to the Discussion - thank you!
