### ISSUE TITLE
Vercel CLI: NO_RESPONSE_FROM_FUNCTION

### ISSUE THREAD

**Issue by LuigiImVector** [zeit/now#6760]
### Solution in https://github.com/vercel/vercel/discussions/6723

<div type='discussions-op-text'>

<sup>Originally posted by **LuigiImVector** September 15, 2021</sup>
I have installed Vercel CLI to test a serverless function locally.
The repository is this: https://github.com/LuigiImVector/github-badge/tree/eda8e1954fc81d69142c461b89f32e9f7635f6f2

With `vercel dev` I started the localhost server but there is a problem. The homepage (`index.html`) is loaded correctly but when I go to `http://localhost:3000/api` or `http://localhost:3000/api/index.js` an error appears.

![image](https://user-images.githubusercontent.com/59611597/133448317-0beac729-c3ff-42d2-ac82-d98567ab6d5e.png)

The entire error message that appears in the console is this:
```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:782:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at Loader.import (internal/modules/esm/loader.js:176:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1011:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at getListener (C:\Users\luigi\AppData\Roaming\npm\node_modules\vercel\node_modules\@vercel\node\dist\launcher.js:66:24)
    at C:\Users\luigi\AppData\Roaming\npm\node_modules\vercel\node_modules\@vercel\node\dist\launcher.js:77:5
    at main (C:\Users\luigi\AppData\Roaming\npm\node_modules\vercel\node_modules\@vercel\node\dist\dev-server.js:103:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
Error! Failed to complete request to /api/index.js: Error: read ECONNRESET
```

In the site on Vercel everything works perfectly (https://github-badge-three.vercel.app/api?years=9) but in localhost does not.</div>

**Comment by gg2001** [comment]
Getting the same issue

**Comment by LuigiImVector** [comment]
I contacted Vercel support but they couldn't (yet) help me, if I hear from them I will post it here.

**Comment by ianjanicki** [comment]
Experiencing this as well. Functions work fine when deployed.

Reverting to @23.0.1 fixed the issue

**Comment by gg2001** [comment]
Yup exact same thing. On my local machine I always get this error:

```
An error occurred with this application.

NO_RESPONSE_FROM_FUNCTION
```

However when I deploy it on vercel it works perfectly. Reverting to @23.0.1 didnt fix it for me.

This is a screenshot of what I see when I do `vercel dev` on my local machine:

<img width="696" alt="Screen Shot 2021-10-30 at 10 42 21 am" src="https://user-images.githubusercontent.com/16451579/139511867-eefe35f9-b0de-4a8f-942d-91d47cb19efc.png">

**Comment by qyl27** [comment]
Same problem. I tried to move backword to @23.0.1. But it did not make things better.
When deployed, it works correctly. 
The only different thing is my error showed "connect ECONNREFUSED".
Strange problem.

**Comment by LuigiImVector** [comment]
Vercel support told me to use this `npm install -g vercel@canary` to fix and it works for me.

**Comment by Kapelianovych** [comment]
For me installing canary version of the `vercel` doesn't work.

**Comment by LuigiImVector** [comment]
> 
> 
> For me installing canary version of the `vercel` doesn't work.

Strange, did you contact support?

**Comment by dnnaji** [comment]
Getting the same issue. Somehow vercel dev no longer works.  Also npm install -g vercel@canary did not work...

fyi, @leerob.

**Comment by mrmartineau** [comment]
FYI this is working for me using `v23.1.3-canary.51`

**Comment by ringowang** [comment]
Thank you so much, npm install -g vercel@canary works for me.
