### ISSUE TITLE
Is vercel service is not operational?

### ISSUE THREAD

**Issue by jorgemndoza** [zeit/now#6794]
### Discussed in https://github.com/vercel/vercel/discussions/6793

<div type='discussions-op-text'>

<sup>Originally posted by **jinan159** October  1, 2021</sup>
Vercel github login is not working now.. 
Is this just on me?
And my project's production build is pending 15min.

![Screenshot 2021-10-01 23 33 07](https://user-images.githubusercontent.com/45728407/135637903-a7b588da-3f47-41c1-a27a-c9e34ee87631.png)
</div>

**Comment by amitsingh-007** [comment]
Facing a similar issue. Deployments are stuck and unable to open Vercel Dashboard.

**Comment by qnxdev** [comment]
One of apps were down yesterday

**Comment by leerob** [comment]
Discussed here https://github.com/vercel/vercel/discussions/6793
