### ISSUE TITLE
Removal of next build output on deploy

### ISSUE THREAD

**Issue by andyrichardson** [zeit/now#6808]
# About

I spent a decent amount of time trying to work out why a Vercel deployment with no build step (because assets are built pre-deploy) was resulting in no build output.

Turns out, Vercel removes the build output (`.next` folder in this case) at deploy time [(source)](https://vercel.com/docs/concepts/deployments/build-step#ignored-files-and-folders).

Can we get some kind of fix for this - imho, it would make more sense to **notify and prompt** users to take action rather than silently removing files.

For reference, the workaround I have is:
 - Build off site
 - Rename `.next` folder to `something-else`
 - Update build output folder in Vercel config with the new folder name

That being said - I'm still getting a 404 by doing this so... :shrug: 

Edit: 

It looks like there's an extra build step following the `next build` step which prepares the next build output. This looks to be disabled unless users build on-platform.

**Comment by TooTallNate** [comment]
Hi @andyrichardson. It sounds like you would be interested in the `vercel build` (to build locally) followed by the `vercel deploy --prebuilt` command (to deploy the locally built assets). Both comands are currently Beta, and on the `canary` release branch (`npm i -g vercel@canary`). Give it a try and let us know how it goes!

**Comment by phil-lgr** [comment]
~@TooTallNate just tried now and `--prebuilt` is not a valid flag, can you update us on that topic?~

EDIT: it looks like vercel canary is aliased to `vc` so `vc deploy --prebuilt` is the command

There is a page on vercel that says it's unsupported https://vercel.com/support/articles/deploying-locally-built-nextjs

For me this is a big limitation as our build on Github Actions is very complex, at the end, we use vercel to deploy what has been built, it doesn't make sense to rebuild again on Vercel

Edit: It looks like `vercel build` is still a draft PR on your branch here: https://github.com/vercel/vercel/blob/add/cli-build2/packages/cli/src/index.ts

**Comment by andyrichardson** [comment]
While I haven't tried it, it sounds like this would be exactly what I'm looking for. Thanks for adding this in!
