### ISSUE TITLE
Vercel crash in some docker environement

### ISSUE THREAD

**Issue by abarisain** [zeit/now#6811]
Hi,

Running the Vercel CLI in some docker environments will crash with the following:

```
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at new SystemError (node:internal/errors:233:5)
    at new NodeError (node:internal/errors:336:7)
    at Object.userInfo (node:os:347:11)
    at Object.metrics (/usr/local/lib/node_modules/vercel/dist/index.js:239808:23)
    at Object.86137 (/usr/local/lib/node_modules/vercel/dist/index.js:240111:26)
```

This is because the docker image might not have /etc/passwd mounted or referencing the current user, which crashes node.

The culprit seems to be this line: https://github.com/vercel/vercel/blob/bf3a1fc832f0d131772f1728950c20c9ce2b6275/packages/cli/src/util/metrics.ts#L20

A potential fix would be try/catching this and using a default value

**Comment by styfle** [comment]
Thanks, this will be fixed in #7034

**Comment by pladaria** [comment]
Meanwhile, is there any way to workaround this?

I tried to set the `VERCEL_CLI_COLLECT_METRICS` env var to "0" without luck

**Comment by styfle** [comment]
You can try the fix on the canary channel. 

  npm i -g vercel@canary
