### ISSUE TITLE
Gitlab Vercel Error: Project not found 404 when trying to import repository

### ISSUE THREAD

**Issue by giancarlosisasi** [zeit/now#6840]
### Discussed in https://github.com/vercel/vercel/discussions/6839

<div type='discussions-op-text'>

<sup>Originally posted by **GiancarlosIO** October 13, 2021</sup>
Hi,
We are trying to deploy a new frontend app using vercel. We have created a vercel team and now we want to deploy an existing GitLab repository. When we try to import the GitLab repo the UI keeps loading/blocked:
(I have hidden the project and team names for privacy reasons)
![bug-vercel-import-project](https://user-images.githubusercontent.com/17274950/137203990-1b42f3c1-5b4c-47cb-b68a-e0783e2968e4.png)

In the devtools I can see 2 requests with 4xx errors:
1. https://vercel.com/api/v1/integrations/integration/oac_xxxxxxxxxxxx/configuration?teamId=xxxxxxx
```
code: "not_found"
message: "Not Found"
```
2. https://vercel.com/api/v2/projects/my-project?teamId=xxxxxxxx
```
code: "not_found"
message: "Project not found"
```

I this a bug in the web or maybe we need to configure the vercel team with a specific option? 🤔 

Thanks in advance.
</div>

**Comment by andershopkins** [comment]
Ditto, we cannot import any projects from any Git provider when attempting to use a Team. It just hangs at the configuration screen.

```
Ignored request error Error: Project not found
    at m (_app-3bbe997905ac2c94.js:1)
    
_app-3bbe997905ac2c94.js:1 GET https://vercel.com/api/v1/integrations/integration/oac_rcH0UPsCZCO6wfDruR2PbXe8/configuration 404

(anonymous) @ _app-3bbe997905ac2c94.js:1
m @ _app-3bbe997905ac2c94.js:1
i @ 972-596a979ecfac2ea0.js:1
(anonymous) @ 8802-7ec9f5482fd38d14.js:1
l @ main-a28a7679d1f7d0fe.js:1
(anonymous) @ main-a28a7679d1f7d0fe.js:1
(anonymous) @ main-a28a7679d1f7d0fe.js:1
T @ 8802-7ec9f5482fd38d14.js:1
a @ 8802-7ec9f5482fd38d14.js:1
(anonymous) @ 8802-7ec9f5482fd38d14.js:1
(anonymous) @ 8802-7ec9f5482fd38d14.js:1
(anonymous) @ 8802-7ec9f5482fd38d14.js:1
l @ main-a28a7679d1f7d0fe.js:1
(anonymous) @ main-a28a7679d1f7d0fe.js:1
(anonymous) @ main-a28a7679d1f7d0fe.js:1
T @ 8802-7ec9f5482fd38d14.js:1
a @ 8802-7ec9f5482fd38d14.js:1
(anonymous) @ 8802-7ec9f5482fd38d14.js:1
(anonymous) @ 8802-7ec9f5482fd38d14.js:1
(anonymous) @ 3515-ec132ca931c72af3.js:1
(anonymous) @ 3515-ec132ca931c72af3.js:1
(anonymous) @ 3515-ec132ca931c72af3.js:1
(anonymous) @ 3515-ec132ca931c72af3.js:1
o @ 3515-ec132ca931c72af3.js:1
(anonymous) @ 3515-ec132ca931c72af3.js:1
r @ _app-3bbe997905ac2c94.js:1
requestAnimationFrame (async)
(anonymous) @ _app-3bbe997905ac2c94.js:1
E @ 3515-ec132ca931c72af3.js:1
(anonymous) @ 3515-ec132ca931c72af3.js:1
bu @ framework-de34ef62081ef90f.js:1
zu @ framework-de34ef62081ef90f.js:1
Nu @ framework-de34ef62081ef90f.js:1
Ru @ framework-de34ef62081ef90f.js:1
(anonymous) @ framework-de34ef62081ef90f.js:1
Fi @ framework-de34ef62081ef90f.js:1
gi @ framework-de34ef62081ef90f.js:1
Ua @ framework-de34ef62081ef90f.js:1
_app-3bbe997905ac2c94.js:1 #291 -> GET https://vercel.com/api/v1/integrations/integration/oac_rcH0UPsCZCO6wfDruR2PbXe8/configuration cle1:cle1:sfo1::hkmjx-1634156603648-f42eb4b61e2f (404, ERROR: Not Found) [149ms] | 1634156603720
```

![image](https://user-images.githubusercontent.com/4251713/137207670-521683a1-47f4-4ad3-9b2b-35a8173cee2f.png)

We've tried using existing teams and creating a net new team just to test. No dice.

However, everything works as expected when importing into personal.

**Comment by yamijuan** [comment]
Same issue here!!! with github

**Comment by giancarlosisasi** [comment]
The vercel team has released a hot-fix for this, now it's working as expected.
