### ISSUE TITLE
Increase amount of memory available for serverless functions

### ISSUE THREAD

**Issue by abriginets** [zeit/now#6959]
### Describe the feature you'd like to request

It's been almost 1 year since [AWS increased amount of memory](https://aws.amazon.com/ru/about-aws/whats-new/2020/12/aws-lambda-supports-10gb-memory-6-vcpu-cores-lambda-functions/) that is possible to allocate for lambdas. Now it's 10GB. Will Vercel increase the limits too? 

### Describe the solution you'd like

Able to get 10GB of ram for lambda

### Describe alternatives you've considered

-

**Comment by timneutkens** [comment]
Moved this to vercel/vercel as it was created in Next.js

**Comment by styfle** [comment]
Hi @abriginets 

What's the use case for this?

The linked article mentions "machine learning, modelling, genomics" but these are generally not a good fit for Vercel because they will timeout after a few seconds.

`Serverless Function Execution Timeout`: https://vercel.com/docs/concepts/limits/overview#general-limits

**Comment by abriginets** [comment]
@styfle AWS gives you more CPU power proportionally to allocated RAM so I believe some of my endpoints would perform much faster with >3008. For example, I'm working with an API that can only return response in XML and only all data at once so I can't request only what I need. That means I have to parse xml on my side, split it into chunks, map them and save to Redis list. I only need to do this task once per day and I hate the idea to put it into separate microservice then create a repo with mutual typings then deploy and maintain it. And when my functions execute faster Vercel gets lighter bills :)

**Comment by styfle** [comment]
> And when my functions execute faster Vercel gets lighter bills

[Serverless Function Execution is billed in GB Hours](https://vercel.com/docs/concepts/limits/overview#typical-monthly-usage-guidelines) meaning that increasing memory will increase usage for the same duration. So this might cost more depending on how much faster it executes. For example, when doubling memory it would need to reduce duration by half to cost the same.

That being said, I'll pass this feature request along to our team, thanks!

**Comment by mircosa** [comment]
@styfle Any updates on this? 

I am also interested in the 10gb memory for serverless due to the increase in CPU power. 

I understand that it will probably cost more and I am totally fine with that. Even if ends up being 2 to 4x more in cost.

**Comment by clarkey** [comment]
I also have a use case for having more memory available in my function. I need to handle compressing up to 2GB TIF images. It isn't far off at 3008MB but I would prefer a 10GB option also. At the moment I need a service outside of Vercel to perform this function.

**Comment by ben-katz** [comment]
I also have a use case that involves processing large PDF files. I would love to migrate my functions to Vercel.

**Comment by trek** [comment]
Hi @abriginets,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
