### ISSUE TITLE
`vc build` is mutating `.next` .nft.json files in Next.js > 12

### ISSUE THREAD

**Issue by jaredpalmer** [zeit/now#6975]
`vc build` is mutating the `*.nft.json` files in `.next` in place when moving files to `.output`. This seems like an observability issue and possibly a caching issue

### Running `next build`

![CleanShot 2021-11-10 at 08 21 15@2x](https://user-images.githubusercontent.com/4060187/141120623-dcc8567e-f960-4ecf-bb36-6465d193a1aa.png)

### Running `vc build`
![CleanShot 2021-11-10 at 08 17 13@2x](https://user-images.githubusercontent.com/4060187/141120555-02f803da-c3d0-475a-bc7a-199c0fbe8aae.png)

**Comment by AndyBitz** [comment]
I guess this happens because we don't really copy the files, we just link them?
In that case we should probably copy all files that we modify in this process instead of linking them, which should be all `nft.json` files and `middleware-manifest.json`.

**Comment by jaredpalmer** [comment]
but why are we writing the changes back to `.next/`? These changes should only be in the .output

**Comment by styfle** [comment]
@jaredpalmer Probably because of the hardlinking?

**Comment by jaredpalmer** [comment]
@styfle ahh duhhhh! my b. @AndyBitz you are correct. We should do exactly that

**Comment by giancarlosisasi** [comment]
hi @jaredpalmer, could be this related to the fact that we need to redeploy (without the 'Include Build Cache' option) our apps to see the changes in our CSS files? 🤔 
The javascript files are updated in each deploy but our CSS files are only updated when we re-deploy the app 😢 The content of the CSS file built locally is different from the content that is built and deployed in vercel. We just noticed this today 🤔

**Comment by jaredpalmer** [comment]
@GiancarlosIO yes that would make a lot of sense
