### ISSUE TITLE
Vercel deploy fails, reason: socket hang up

### ISSUE THREAD

**Issue by vinisaveg** [zeit/now#6979]
Vercel CLI failed while trying to deploy the app. 

Even though the app continue to build and deploy on vercel, with a sequence of staging deploys queue.

Command:

```
npx vercel
```

Output:

```
Vercel CLI 23.1.2
Error! request to https://api.vercel.com/v13/now/deployments?teamId=team_***  failed, reason: socket hang up
```

Result:

![screenshot](https://user-images.githubusercontent.com/55714745/141299031-55164960-1a02-44d2-9d5a-d2b457444c30.png)

Expected:
no errors, 1 deploy.

Platform: Linux
Vercel CLI version: 23.1.2

**Comment by TooTallNate** [comment]
Hi @vinisaveg, is this still an issue for you? Likely it was related to your local internet connection. For future reference, you can check on the status of Vercel here: https://www.vercel-status.com/

**Comment by giancarlosisasi** [comment]
hi @vinisaveg @TooTallNate, How did u solve that error? I'm getting the same error
For some reason the command `vercel -t my-token` fails with a `failed, reason: socket hang up`. This error happens in our GitLab ci (and also in local). The other thing is that I don't get why 6-7 deployments are created when we run `vercel -t my-token` only one time.

**Comment by vinisaveg** [comment]
Hi @GiancarlosIO @TooTallNate. I did not do anything, It just simply started working as it should after a few days... 😅

**Comment by orioletech** [comment]
I'm having the exact same issue, it hangs for a while and then errors out with failed, reason: socket hang up. Anyone found a fix?

**Comment by gitnasr** [comment]
Issue still presist

**Comment by niklasravnsborg** [comment]
I'm also experiencing this issue with Vercel CLI 25.1.0.

**Comment by jpall12** [comment]
Experiencing this issue too! Vercel CLI 18.0.0
![image](https://user-images.githubusercontent.com/50560291/184465046-bda95a7d-26c9-4990-a053-24dd3898796f.png)

**Comment by agustinl** [comment]
Same issue here:
```
Vercel CLI 28.1.0
Error! request to https://api.vercel.com/v13/deployments failed, reason: socket hang up
```
😢

**Comment by Moe03** [comment]
Same issure here...

```
Vercel CLI 28.1.0
Error! request to https://api.vercel.com/v13/deployments failed, reason: socket hang up
```

**Comment by davidkolesom** [comment]
Same issue here :(

**Comment by davidkolesom** [comment]
Anyone? 😢

**Comment by jpall12** [comment]
I have opened a ticket with Vercel and referenced this issue. Hopefully they can resolve this issue soon.

**Comment by mrkstwrt** [comment]
I've encountered this issue too with `28.2.2`

**Comment by zioForas** [comment]
i'm having this issue too, my partber @ziadidi has no issues on the same network

**Comment by willkuerlich** [comment]
Same here..
Also Vercel is not reflecting current commit to my github repo for at least 30minutes now

**Comment by ivstiv** [comment]
We are also experiencing it on our self-hosted Gitlab runners since yesterday.
```
Vercel CLI 28.4.10
Retrieving project…
Deploying **edited**
Uploading [--------------------] (0.0B/4.6MB)
Uploading [=====---------------] (1.2MB/4.6MB)
Uploading [==========----------] (2.3MB/4.6MB)
Uploading [===============-----] (3.5MB/4.6MB)
Uploading [====================] (4.6MB/4.6MB)
Error: request to https://api.vercel.com/v13/deployments?teamId=**edited** failed, reason: socket hang up
```

It looks like the upload doesn't get acknowledged from the server. It broke on its own without any changes from our side. Moving it to a vercel integrated repository is not an option as it is behind a firewall. It also doesn't seem to be a blocked/limited IP as the deployment job was ran on multiple runners with different IPs.

**Comment by giancarlosisasi** [comment]
@ivstiv I was getting the same error. To fix that I switched to `vercel deploy --prebuilt --archive=tgz`
Now, we run the following commands in our gitlab runner to deploy our nextjs apps:
- `vercel pull`
- `vercel build`
- `vercel deploy --prebuilt --archive=tgz`

Related discussion: https://github.com/vercel/vercel/discussions/8643

**Comment by ivstiv** [comment]
Here is part of the response I got from Vercel regarding the aforementioned error:

> Socket hang up can happen when too many files are being pushed to Vercel, hitting the API limit threshold or the internet connection itself is poor and the connection is dropped. Typically when we've seen it, it's been caused by the nodes_modules and the .git folders being uploaded to Vercel, which aren't required for the build.

I was not able to identify any such large folders or internet issues, so I tried what @GiancarlosIO [proposed by adding --archive=tgz](https://github.com/vercel/vercel/issues/6979#issuecomment-1277806376) and it worked! Here is what our uploading script looks like:

```
vercel pull --yes --environment=production --token=$VERCEL_TOKEN
vercel build --prod --token=$VERCEL_TOKEN
vercel deploy --prebuilt --prod --archive=tgz --token=$VERCEL_TOKEN
```

**Comment by caweidmann** [comment]
Experiencing the same issue. Deploy step hangs in Github Actions even though on Vercel UI it triggers multiple deploys which all complete successfully. Adding 
```
vercel deploy --prebuilt --archive=tgz
```
also worked for me.

**Comment by elviocb** [comment]
Why the option `--archive=tgz` option is not on Vercel's CLI help? 🤔

**Comment by alfeatingcats** [comment]
I turned on the VPN and everything worked

**Comment by aleehamza25** [comment]
Getting same issue

Vercel CLI 48.1.6
Error: request to https://api.vercel.com/v13/deployments?teamId=team_xxxxxxxxxxx failed, reason: socket hang up
