### ISSUE TITLE
Local environment serverless functions conflicts with Blitz API routes

### ISSUE THREAD

**Issue by edmbn** [zeit/now#6983]
I have project created on Blitz. As I need to develop some of the serverless functions with python I put them on api/ folder on root of the directory, as specified by Vercel documentation.

I am using "vercel dev" normally to create the same environment as Vercel (or kind of)
but had to change the settings on my Vercel dashboard, to make sure that when I call "vercel dev" it executes blitz dev
Doing this blitz loads perfect but vercel never takes de api/ folder on the root of the blitz project, so I get 404 on the python functions.

Then  I configured Vercel to use this command when "vercel dev" is called: "blitz dev --port $PORT". Now, on my terminal I use "vercel dev --listen 3100" and now, localhost:3100/api/pythonFunction is detected BUT everything else is broken: "http://localhost:3100/api/rpc/getProfile 404 (Not Found)" and cannot render anything.
After some research I was able to solve it using a vercel.json file, inside the project, with the following configuration: 
```
{
  "name": "my-app",
  "version": 2,
  "builds": [
    {
      "src": "api/pythonFunction.py",
      "use": "@vercel/python"
    }
  ],
  "routes": [
    {
      "src": "/api/pythonFunction",
      "dest": "/api/pythonFunction.py"
    }
  ]
}
```

**Comment by andymckay** [comment]
Thanks for the feedback here @edmbn I'm not sure if there's anything actionable here, but we've taken the feedback and we'll see if we can improve things here in the future.
