### ISSUE TITLE
Support for Node.js 16.x (LTS)

### ISSUE THREAD

**Issue by kaleabmelkie** [zeit/now#7004]
### Discussed in https://github.com/vercel/vercel/discussions/7003

<div type='discussions-op-text'>

<sup>Originally posted by **kaleabmelkie** November 15, 2021</sup>
Currently, it seems that only Node.js 12.x and 14.x are supported.

Is there a temporary workaround (or a timeline) for shipping apps that need the 16.x LTS version on Vercel?
</div>

**Comment by styfle** [comment]
Closing in favor of #7003

**Comment by Doomd** [comment]
That link is dead.

**Comment by styfle** [comment]
Looks like that discussion was moved to https://github.com/vercel/community/discussions/37

**Comment by kvetoslavnovak** [comment]
:+1: 
To replace all my usage of the String.prototype.replaceAll() string method in my backend code only because of Vercel Node.js 14.x limit is very frustrating TBH  :-P

**Comment by styfle** [comment]
Node.js 16 is available today https://vercel.com/changelog/node-js-16-lts-is-now-available
