### ISSUE TITLE
yarn run build failed due to Syntax Error in my sass file during deployment, which runs without any error locally

### ISSUE THREAD

**Issue by sourabpramanik** [zeit/now#7039]
### Discussed in https://github.com/vercel/vercel/discussions/7038

<div type='discussions-op-text'>

<sup>Originally posted by **sourabpramanik** November 20, 2021</sup>
![image](https://user-images.githubusercontent.com/61370770/142725874-6baa5715-de43-415d-ae9a-67928b2299ce.png)
</div>

**Comment by floyedxman** [comment]
can this issue be solved ?
