### ISSUE TITLE
How to scan directories on production on Vercel (with Next.js)?

### ISSUE THREAD

**Issue by alexandrepaiva-dev** [zeit/now#7090]
### Discussed in https://github.com/vercel/vercel/discussions/7073

<div type='discussions-op-text'>

<sup>Originally posted by **alexandrepaivaa** November 28, 2021</sup>
Hi,

I've tried to ask for help on Stackoverflow already but no answers after 10 days, also tried to contact Vercel but no reply. Hopefully I will find someone to help me here.

I'm developing a sitemap generator sript for my website, it works well on dev (yarn dev) and production (yarn build & yarn start) on my own PC but when uploading to Vercel I get an error and I can't find the solution. My website has the following structure:

https://xxxxx.com/
https://xxxxx.com/projects
https://xxxxx.com/projects/one
https://xxxxx.com/projects/two
https://xxxxx.com/projects/three
https://xxxxx.com/contact
etc

The way I access the sitemap is https://xxxxx.com/sitemap.xml (which the file is placed under "/pages" as "sitemap.xml.js"), again, it works when I access on my own PC either on dev or build/start.

But on Vercel I get the error:

`ERROR   Error: ENOENT: no such file or directory, scandir '/var/task/.next/server/pages/projects'`

More details on Stackoverflow:
https://stackoverflow.com/questions/70027742/how-to-scan-directories-on-production-on-vercel-with-next-js

It seems like it cannot find the directory "projects" under "/.next/server/pages". 

Does anyone know how to properly scan files/directories when in production on Vercel?

Thank you!</div>

**Comment by trek** [comment]
Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
