### ISSUE TITLE
I'm not able to get my vercel commands to work on Vercel with Visual Studio Code

### ISSUE THREAD

**Issue by caretakerx** [zeit/now#7136]
### Discussed in https://github.com/vercel/vercel/discussions/6999

<div type='discussions-op-text'>

<sup>Originally posted by **caretakerx** November 14, 2021</sup>
I'm not able to get my vercel commands to work on Vercel with Visual Studio Code

My vercel command shows an error in terminal.

I'm using Mac what would be the commands to host my vercel site.</div>

I'm not able to get the base vercel commands to work.

**Comment by leerob** [comment]
https://github.com/vercel/vercel/discussions/6999#discussioncomment-1705785
