### ISSUE TITLE
vc dev failed to proxy requests to /pages/api/* when there are other serverless functions at /api/*

### ISSUE THREAD

**Issue by wiiiimm** [zeit/now#7166]
Vercel CLI version: 23.1.2

Reproduction: Using the Next.js template (with a hello API at /pages/api/hello), add a python API at /api/date.py) and try to access https://localhost:3000/api/hello using `vc dev`.

Repo: https://github.com/vercel-support/62263-nextjs-with-python-api
Vercel Project: https://vercel.com/vercel-support/62263-nextjs-with-python-api

**Comment by britt** [comment]
I have had the same issue with Go functions. Is there any way to run serverless functions alongside next.js API routes?

**Comment by leerob** [comment]
@britt https://github.com/vercel/vercel/discussions/4023#discussioncomment-3657

**Comment by andymckay** [comment]
There's a good comment there ☝🏾 I also gave an example of how to use Flask here: https://github.com/andymckay/test-vercel-flask. Hope that helps, thank you for asking 🙇🏾
