### ISSUE TITLE
Build error: found pages without a React Component

### ISSUE THREAD

**Issue by Nfinished** [zeit/now#7191]
### Discussed in https://github.com/vercel/vercel/discussions/7185

<div type='discussions-op-text'>

<sup>Originally posted by **Nfinished** December 13, 2021</sup>

Hi, my builds on Vercel are failing with the following error:
```
> Build error occurred
--
12:31:24.978 | Error: Build optimization failed: found pages without a React Component as default export in
12:31:24.978 | pages/projects/[id]
12:31:24.978 | pages/projects
12:31:24.978 |  
12:31:24.978 | See https://nextjs.org/docs/messages/page-without-valid-component for more info.
12:31:24.980 |  
12:31:24.980 | at /vercel/path0/node_modules/next/dist/build/index.js:604:19
12:31:24.981 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
12:31:25.060 | error Command failed with exit code 1.


```

I'm a little stumped because
1. These pages absolutely do have default exported React components
2. My app runs and builds locally

What could be causing this? the only files in each folder are the `index.tsx` page component.

Node v14.17.6
Next v11.1.0

</div>

/projects/index.tsx below in full. It definitely exports a react component.
```jsx
// app/pages/projects/index.tsx

import Head from 'next/head'
import React, { Suspense } from 'react'

import AppLayout from 'app/core/layouts/AppLayout'
import ProjectTable from 'app/Projects/components/ProjectTable'

const ProjectsPage = () => {
  return (
    <>
      <Head>
        <title>Projects</title>
      </Head>

      <ProjectTable />
    </>
  )
}

ProjectsPage.auth= true
ProjectsPage.getLayout = (page) => <AppLayout>{page}</AppLayout>

export default ProjectsPage
```

**Comment by stanleychh** [comment]
Hi @Nfinished , I faced this issue as well. Would you please share how did you solve it? Thanks

**Comment by Nfinished** [comment]
Hi, oddly enough it turned out to be an issue with [array-shuffle](https://github.com/sindresorhus/array-shuffle). My project built locally but something about Vercel's build process spat it back out. Removing the dependency solved my problem.

**Comment by stanleychh** [comment]
Thanks for your answer. That's tricky since the error messages were sort of misleading. It was not related to `without a React Component as default export`.

**Comment by braxtondiggs** [comment]
not to bump, but I got the same issue with nanoid. Works locally but once deployed, I get the same error. Some packages just break I guess

**Comment by JustinClarke** [comment]
here you go, https://stackoverflow.com/questions/65598753/cant-build-react-next-project-found-page-without-a-react-component-as-default
