### ISSUE TITLE
why i can't sign in to vercell with my github?

### ISSUE THREAD

**Issue by Talith4** [zeit/now#7200]
### Discussed in https://github.com/vercel/vercel/discussions/7199

<div type='discussions-op-text'>

<sup>Originally posted by **Talith4** December 17, 2021</sup>
I want to join with vercel but I cannot join or sign in or log in to vercel with my account github. It's like my account github is blocked. Do you have any answer with my problem?</div>

**Comment by leerob** [comment]
https://github.com/vercel/community/discussions/140#discussioncomment-1969237
