### ISSUE TITLE
Vercel can authenticate a Gitpod session ONLY through email

### ISSUE THREAD

**Issue by jarmos-san** [zeit/now#7234]
### Discussed in https://github.com/vercel/vercel/discussions/7142

<div type='discussions-op-text'>

<sup>Originally posted by **Jarmos-san** December  7, 2021</sup>
I've been using Gitpod lately & tried using the Vercel CLI there. I couldn't authenticate in that environment by running `vercel link`. So, I'm wondering is it at all possible to use Vercel CLI in Gitpod? If so, how should I use it correctly?</div>

Authenticating a Gitpod session through Vercel CLI doesn't work as intended. I've tried authenticating with GitHub first which fails & I assume trying with GitLab/Bitbucket would result the same. The work around it, is to use your email to authenticate instead.

It would be nice if Vercel CLI could authenticate through third-party solutions like GitHub, GitLab and/or Bitbucket "properly".

**Comment by emadzz** [comment]
Out-of-band mode is all I needed: https://vercel.com/docs/cli/login#out-of-band-mode

**Comment by mmailaender** [comment]
@Jarmos-san Even easier: 
`vercel link --yes --token $VERCEL_TOKEN --scope $YOUR_SCOPE`

With that one it's running on autopilot - no need anymore to copy paste 5 times a day a login code :)

https://vercel.com/docs/cli/link#yes
https://vercel.com/docs/cli/global-options#token
https://vercel.com/docs/cli/global-options#scope
