### ISSUE TITLE
Custom env variable for custom domains

### ISSUE THREAD

**Issue by akinwol** [zeit/now#7249]
### Discussed in https://github.com/vercel/vercel/discussions/7248

<div type='discussions-op-text'>

<sup>Originally posted by **akinwol** December 30, 2021</sup>
Hi everyone, newbie here so bare with me. 

I am working with a couple customers as part of a beta for an idea and need help. I am looking to build a Saas based solution/platform. Launched a beta for 1 customer but it is not scalable AT ALL.

**What I need**

1. Custom/sub domain for each customer (which I found a solution for [here](https://github.com/vercel/vercel/discussions/4840))
2. Custom env variables for each customer (unique env variables per custom domain). 
   - Each customer in some cases will need their own env variables for third party integrations. For e.g. something like a custom Shopify store each customer would have their own keys/secrets to connect to their store. Same goes for any available integrations we might have.
3. Is there a way to add new env like variables dynamically post build? For eg. if I have a production build running but a customer wants to add a new API Key for an integration they want to use. Does Vercel have any integrations to dynamically store secrets for each custom domain? Or is there a recommended solution to solve for something like this?
4. Configs per customer/custom domain - What is the best way with Vercel to load up custom configs such as themes, available features, meta tags etc for each customer. Can this be done dynamically or can it only be done for each build. 

I have considered creating a separate branch for each customer but I would think this could get messy as the app grows. If I have 1000+ customers, I don't know if I would want to maintain 1000+ branches. But if this is the best way the so be it.

Any advice or help would be greatly appreciated</div>

**Comment by ManuLpz4** [comment]
Same here

**Comment by The-Code-Monkey** [comment]
Yeah i think domain level env vars are the next thing needed, I have just come across this need.

obviously it should still work in a cascade format e.g.

- env vars that arent specific.
- branch specific.
- domain specific.

This would be really useful as our ecommerce project doesnt need a different branch for each site, as we control everything via env vars and apis, so the ability to change based on domain is a real need.

**Comment by trek** [comment]
Hi @akinwol,

We're getting close to releasing a feature that may help here. https://x.com/leeerob/status/1669830877759635457
