### ISSUE TITLE
[CLI] When "vercel dev" proxies a request to a framework, its queries are not original ones and will result in errors for Vite.

### ISSUE THREAD

**Issue by UnluckyNinja** [zeit/now#7283]
When Vite plugins processing a Vue Single File Component(SFC) file, it will transform its style tag into a js file with a url like 
`/foo/bar/AComponent.vue?vue&type=style&index=0&lang.css`. Then it was used as a js module in the page.

However when Vercel CLI dev server proxying it to frontend dev server, the cli doesn't use original url but generates a new one.
Generated one is like: `/foo/bar/AComponent.vue?vue=&type=style&index=0&lang.css=`, which is not a valid css url that can be recognized by Vite. Its content is not processed by css plugins of Vite, but it's still used as a js module.

Because of that, when running "vercel dev", if you write some css rules in the style tag of a Vue SFC file, the page will become blank and throw errors in browser console. It's very inconvenient for Vue developers if we can't use style tag in SFC.

Cause is at: 
https://github.com/vercel/vercel/blob/bae26cc0178ff49c3050ceaf5db00969e510cc6b/packages/cli/src/util/dev/server.ts#L1703-L1707

Here it deletes original querystring (`origUrl.search`), and generates a new one together with pathname (`url.format(origUrl)`), which is the one with additional "=". (`url.format()` internally uses `querystring.stringify()` that will add "=" for empty fields in the object).

In my local repo, I deleted L1704 & L1706 then it worked as expected. `url.format()` now uses original search string, so additional "="s are gone. But I don't know if it will impact other frameworks.

**Comment by micahlt** [comment]
Yep, same issue here.  This is very annoying, and a (permanent) fix would be amazing

**Comment by micahlt** [comment]
@leo can we at least get confirmation that this issue is known?

**Comment by Idered** [comment]
> When Vite plugins processing a Vue Single File Component(SFC) file, it will transform its style tag into a js file with a url like `/foo/bar/AComponent.vue?vue&type=style&index=0&lang.css`. Then it was used as a js module in the page.
> 
> However when Vercel CLI dev server proxying it to frontend dev server, the cli doesn't use original url but generates a new one. Generated one is like: `/foo/bar/AComponent.vue?vue=&type=style&index=0&lang.css=`, which is not a valid css url that can be recognized by Vite. Its content is not processed by css plugins of Vite, but it's still used as a js module.

Vite [uses `str.endsWith('.XXX')`](https://github.com/vitejs/vite/search?q=endsWith) to check for module type. Switching to something like ```RegExp(`${lang}=?$`).test(url)``` would fix this issue.

**Comment by Idered** [comment]
Or it could be fixed with one line on vercel side:

https://github.com/vercel/vercel/blob/983946650e9170b4d3e6f861fce83113148008dc/packages/cli/src/util/dev/server.ts#L1683

```js
req.url = url.format(origUrl).replace(/=$/, '');
```

**Comment by micahlt** [comment]
Bump... this makes using Vercel and Vite together nearly impossible.

**Comment by styfle** [comment]
I created a PR here https://github.com/vercel/vercel/pull/8183

Ideally, Vite would fix their URL parsing to handle this case since both `/?vue` and `/?vue=` are equivalent.

**Comment by micahlt** [comment]
What moved the PR's status to a draft @styfle?

**Comment by stkevintan** [comment]
Same issue here
