### ISSUE TITLE
[CLI] get rid of `beta` in vercel dev

### ISSUE THREAD

**Issue by ernestd** [zeit/now#7297]
It's been in beta for years. Time to get rid of it
![image](https://user-images.githubusercontent.com/933375/148801375-09d752be-ef72-4a30-9428-eede53827b16.png)

**Comment by pacocoursey** [comment]
> Also dev has been in (beta) since we introduced it years ago – why is vercel dev in beta?

https://vercel.slack.com/archives/C02B5JY39DY/p1641591476003300?thread_ts=1641591373.002700&cid=C02B5JY39DY
