### ISSUE TITLE
I have deployed my application on vercel using githubActions all the dependency installations and build are successfully done but when i hit an api that communicates with my postgres db the deployment logs throw this error **Error: Please install pg package manually**

### ISSUE THREAD

**Issue by DaniyalKukda** [zeit/now#7342]
I have deployed my application on vercel using githubActions all the dependency installations and build are successfully done but when i hit an api that communicates with my postgres db the deployment logs throw this error **Error: Please install pg package manually**

I have a pg package in my dependencies in package.json its working fine locally on my machine but after deployment i got this error

_Originally posted by @DaniyalKukda in https://github.com/vercel/vercel/discussions/7341_

**Comment by SoozaV** [comment]
You posted this since January and still no answer? I'm facing the same issue. 

I'm using sequelize / pg / pg-hstore, and I can't run my app: https://github.com/orgs/vercel/discussions/1140

I've tried installing pg locally and globally in my local repo, but I got the same error.

**Comment by trek** [comment]
Hi @DaniyalKukda,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
