### ISSUE TITLE
vercel certs issue "Error! ACME request was malformed and responded with an error"

### ISSUE THREAD

**Issue by adnaz** [zeit/now#7380]
I added the TXT record in my registrar to be able to  solve the DNS challenge (vercel certs issue  blog.ispapp.co --challenge-only)
but when i run  "vercel certs issue blog.ispapp.co" i get this error  "Error! ACME request was malformed and responded with an error"
and when i run it for the 2nd time i get this "Error! We could not solve the dns-01 challenge for cns blog.ispapp.co".

Any help would be appreciated 🍻

**Comment by trek** [comment]
Hi @adnaz,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
