### ISSUE TITLE
Manual deployment from Github

### ISSUE THREAD

**Issue by JonCognioDigital** [zeit/now#7404]
For the second time tonight we've been unable to deploy an important update to our website because GitHub Webhooks is down.

It seems crazy that there is nowhere on the Vercel dashboard to initiate a deployment from Github manually in these situations.

This is an absolutely vital addition for us if we're to continue using Vercel for new projects.

**Comment by darylcecile** [comment]
Ive come across similar issues recently. It might not be convenient, but i found deploy hooks have helped me workaround the situation - https://vercel.com/docs/concepts/git/deploy-hooks

**Comment by TooTallNate** [comment]
You could use the CLI to deploy manually in those cases (`vercel deploy --prod`).

**Comment by FelipeBattistottiAvant** [comment]
@jon64digital 
I have the same problem

**Comment by trek** [comment]
Hi @JonCognioDigital,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.

**Comment by JonCognioDigital** [comment]
Thanks. But this was 3 years ago. 😂😂🫤
