### ISSUE TITLE
vercel dev ignores named index or [segment] for /api routes

### ISSUE THREAD

**Issue by samcx** [zeit/now#7412]
#### Current Behavior
When using `vercel dev` (version 23.1.2), `/api/[bar].ts` and `index.ts` do not work while `foo.ts` does. All `/api` paths work in Production.

#### Expected Behavior
It is expected for `vercel dev` behavior to work identically to Production.

#### Reproduction Repository
- https://github.com/vercel-support/vite-vercel

**Comment by styfle** [comment]
@samsisle I tried this on the latest canary (`vercel@23.1.3-canary.75`) and it works for all routes.

Perhaps it was already fixed?

<img width="944" alt="image" src="https://user-images.githubusercontent.com/229881/153512841-50b7836c-0234-4df5-a741-75b883be86c8.png">

<img width="697" alt="image" src="https://user-images.githubusercontent.com/229881/153512885-5eda19f8-e5be-4359-b459-b83d90b87159.png">

<img width="697" alt="image" src="https://user-images.githubusercontent.com/229881/153512909-b1554ca6-355f-420c-ad8b-c3b68ed3613d.png">

**Comment by JuanM04** [comment]
I'm on v24.2.3 and it persists
