### ISSUE TITLE
React Router in Vercel?

### ISSUE THREAD

**Issue by Montana** [zeit/now#7475]
Hey Vercel users, 

I am trying to publish a serverless app to Vercel. I want to use `react-router` and this works locally, but when I deploy it from Vercel I get a `404 Not Found.` 

I've added a  `vercel.json` file at the root directory of my  project, and use "rewrites" to rewrite all incoming paths to refer to your index path, so right now it looks something like:

```json
{
  "rewrites":  [
    {"source": "/(.*)", "destination": "/"}
  ]
}
```

**Comment by grinsteindavid** [comment]
im stuck too

```
{
  "routes": [{ "src": "/[^.]+", "dest": "/", "status": 200 }]
}
```

its in the root directory and it doesnt work

**Comment by Montana** [comment]
Hey @grinsteindavid,

I think I found a fix, 

Add a `vercel.json` file at the root of your project, and use the Vercel "rewrites" to rewrite all incoming paths to refer to your index path, so for example take this JSON code I wrote out:

```json
{
  "rewrites":  [
    {"source": "/(.*)", "destination": "/"}
  ]
}
```
See if that works, after doing this - my build worked.

**Comment by MakCUkr** [comment]
@Montana I have the exact same code for vercel.json but it isn't working. Moreover, I think you had mentioned In your very first comment that this file was there. What exactly did you change ?

**Comment by revskill10** [comment]
Any news on this ?

**Comment by mj026** [comment]
Ok I had the same issue that suddenly all my pages gave a 404.

Solution: The `vercel.json` was in my project root directory, but this isn't the directory that is being published to vercel. After building, the contents of the`public` directory is transferred to vercel, so I had to put the file there. 

It did work before when keeping the `vercel.json` file in the project root directory, but this has been changed somehow.

**Comment by astears** [comment]
If you are not building in vercel and rather just setting the root directory from where to serve files from (like the build directory), make sure the vercel.json is placed in the same location that you are serving files from. 

In my case, I fixed it by using the below vercel.json file and moving it from the project root directory to the build directory since I am not building the app in vercel.

`{
  "rewrites":  [
    {"source": "/(.*)", "destination": "/"}
  ]
}`

**Comment by DavidForDev** [comment]
I build the react file myself, so I use webpack, etc. I'm deploying my react app on vercel, everything is fine, but I can't switch to other routes, for example, I want to switch from '/' to '/auth/registration' ,I do everything nicely, I have vercel.json and there I wrote " { "rewrites": [ {"source": "/(.*)", "destination": "/"} ] } " I have this file (vercel.json) in the public file because after "npm run build" it will be with other files but still not working please help me

**Comment by astears** [comment]
Have you tried placing the vercel.json in the build folder? I believe that's where it needs to be.

**Comment by astears** [comment]
> I build the react file myself, so I use webpack, etc. I'm deploying my react app on vercel, everything is fine, but I can't switch to other routes, for example, I want to switch from '/' to '/auth/registration' ,I do everything nicely, I have vercel.json and there I wrote " { "rewrites": [ {"source": "/(.*)", "destination": "/"} ] } " I have this file (vercel.json) in the public file because after "npm run build" it will be with other files but still not working please help me

Have you tried placing the vercel.json in the build folder? I believe that's where it needs to be in your case.

**Comment by DavidForDev** [comment]
yes, so I tried placing the vercel.json in the dist file ( the same as the build ), but not working and I don't know why, I spent all day trying to solve this problem

**Comment by DavidForDev** [comment]
may be I should add some plugins to the webpack? what do you think about it?

**Comment by DavidForDev** [comment]
> > I build the react file myself, so I use webpack, etc. I'm deploying my react app on vercel, everything is fine, but I can't switch to other routes, for example, I want to switch from '/' to '/auth/registration' ,I do everything nicely, I have vercel.json and there I wrote " { "rewrites": [ {"source": "/(.*)", "destination": "/"} ] } " I have this file (vercel.json) in the public file because after "npm run build" it will be with other files but still not working please help me
> 
> Have you tried placing the vercel.json in the build folder? I believe that's where it needs to be in your case.

hey, I was checking the dist file and found that I don't place the vercel.json in the dist file, can you look at my webpack code?
```

const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path')

module.exports = {
    entry: './src/index.js',
    output: {
        filename: 'bundle.[hash].js',
        path: path.resolve(__dirname, 'dist'),
        publicPath: '/'
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: './public/index.html'
        })
    ],
    module: {
        rules: [
            {
                test: /\.js$/,
                use: 'babel-loader'
            },
            {
                test: /\.scss$/,
                use: ['style-loader', 'css-loader', 'sass-loader']
            },
            {
                test: /\.svg|jpg|png|gif$/,
                use: 'file-loader'
            }
        ]
    },
    devServer: {
        historyApiFallback: true,
        historyApiFallback: {
            disableDotRule: true
        }
    }
} 

```

how I can place the vercal.json file in the dist file? please consider the vercal.json file I have in the public folder where I have only index.html

**Comment by af-arturoramirez** [comment]
Any news on this?, I placed the vercel.json everywhere in the app and it does not work :(

**Comment by DavidForDev** [comment]
> Any news on this, I placed the vercel.json everywhere in the app and it does not work :(

finally, I replace it (webpack) with create-react-app, I mean make a folder where you can make react file (create-react-app), and then will work it

**Comment by DavidForDev** [comment]
> Any news on this, I placed the vercel.json everywhere in the app and it does not work :(

also, in my case can't deploy react file which made by me with webpack, I don't know why, but i will find solution

**Comment by user72356** [comment]
Please note that if you use Vercel serverless functions, you must not use rewrites for the api folder. So your vercel.json should look like this:

```
{
    "rewrites": [
        { "source": "/((?!api/.*).*)", "destination": "/" }
    ]
}
```

**Comment by user72356** [comment]
The problem with rewrites is that now I can't run my website locally with `vercel dev`. Has anyone found a fix for this?

**Comment by seantai** [comment]
the rewrite rule worked for me, only after I started pushing my updates thru github, instead of directly via vercel cli

**Comment by chandrahmani** [comment]
Is there any update on it ?

**Comment by dx-luna** [comment]
Replace `index.html` to `404.html`

**Comment by adilmxx** [comment]
worked like magic !!
whats the logic behind this ?

**Comment by trunkey2003** [comment]
I just found out that it only crashes in my Vite app but not in Create React App. Any suggestions on how they differ?

**Comment by trunkey2003** [comment]
I just found out that it only crashes in my Vite app but not in Create React App. Don't know why they differ?

**Comment by eRuaro** [comment]
> I just found out that it only crashes in my Vite app but not in Create React App. Don't know why they differ?

Hey man! Have you found a fix for this? Experiencing the same issue. I've put my vercel.json file everywhere but same thing.

**Comment by trunkey2003** [comment]
> > I just found out that it only crashes in my Vite app but not in Create React App. Don't know why they differ?
> 
> Hey man! Have you found a fix for this? Experiencing the same issue. I've put my vercel.json file everywhere but same thing.

I have fixed by adding vercel.json in the root directory

```
{
  "rewrites": [{ "source": "/(.*)", "destination": "/" }]
}
```

**Comment by ghost** [comment]
> > > I just found out that it only crashes in my Vite app but not in Create React App. Don't know why they differ?
> > 
> > 
> > Hey man! Have you found a fix for this? Experiencing the same issue. I've put my vercel.json file everywhere but same thing.
> 
> I have fixed by adding vercel.json in the root directory
> 
> ```
> {
>   "rewrites": [{ "source": "/(.*)", "destination": "/" }]
> }
> ```

This has worked for me

**Comment by smohadjer** [comment]
Adding a rewrite rule like mentioned in above posts to vercel.json crashes Vite app on localhost with following errors:

````
 GET http://localhost:3000/@vite/client 404 (Not Found)
 GET http://localhost:3000/src/main.tsx net::ERR_ABORTED 404 (Not Found)
 GET http://localhost:3000/@react-refresh net::ERR_ABORTED 404 (Not Found)
````

**Comment by muohannedxd** [comment]
`{
  "rewrites": [
      { "source": "/((?!api/.*).*)", "destination": "/" }
  ]
}`

this worked for me. A React app with Vite.

**Comment by iamdipankarpaul** [comment]
I am stuck with a problem. In vercel only my rootlayout component is showing all other pages are not found. why?

this is my index.js file in pages folder
```js
export { default as Home } from "./home/Home";
export { default as Definition } from "./definition/Definition";
export { default as Bookmarks } from "./bookmark/Bookmarks";
export { default as History } from "./history/History";
export { default as Error } from "./Error";
export { default as NotFound } from "./NotFound";
```

this is my App.jsx file
```jsx
import { createBrowserRouter, RouterProvider } from "react-router-dom";
// import layout
import { RootLayout } from "./components";
// import pages
import { Bookmarks, Definition, Error, History, Home, NotFound } from "./pages";

const router = createBrowserRouter([
  {
    path: "/",
    element: <RootLayout />,
    children: [
      {
        index: true,
        element: <Home />,
        errorElement: <Error />,
      },
      {
        path: "search/:searchWord",
        element: <Definition />,
        errorElement: <Error />,
      },
      {
        path: "bookmarks",
        element: <Bookmarks />,
        errorElement: <Error />,
      },
      {
        path: "history",
        element: <History />,
        errorElement: <Error />,
      },
    ],
  },
  {
    path: "*",
    element: <NotFound />,
  },
]);

function App() {
  return (
    <>
      <RouterProvider router={router} />
    </>
  );
}

export default App;
```

It is working perfectly fine on my device or if i forward port with my friend, but in vercel only rootlayout is showing, all other pages are not found.


In my local env
![IMG-20240426-WA0016.jpg](https://github.com/vercel/vercel/assets/136841290/06c1b0fc-b2b7-4a6a-affa-a7ee82d20d3c)

In vercel
![IMG-20240426-WA0017.jpg](https://github.com/vercel/vercel/assets/136841290/147c19e1-b828-4dbe-acf5-5fd6c3f3aaa2)

![IMG-20240426-WA0015.jpg](https://github.com/vercel/vercel/assets/136841290/5e5f3c59-1bdb-4c9e-b477-58f3c59aef9c)

this is my RootLayout.jsx file
```jsx
import { Container } from "@mantine/core";
import React from "react";
import { Outlet } from "react-router-dom";
import Navbar from "./Navbar";

function RootLayout() {
  return (
    <>
      <Container size="md" pos="sticky" top={0} style={{ zIndex: 5 }}
      bg={"var(--mantine-color-body)"}>
        <nav>
          <Navbar />
        </nav>
      </Container>
      <Container size="sm">
        <main>
          <Outlet />
        </main>
      </Container>
    </>
  );
}

export default RootLayout;
```

**Comment by malt03** [comment]
> Adding a rewrite rule like mentioned in above posts to vercel.json crashes Vite app on localhost with following errors:
> 
> ```
>  GET http://localhost:3000/@vite/client 404 (Not Found)
>  GET http://localhost:3000/src/main.tsx net::ERR_ABORTED 404 (Not Found)
>  GET http://localhost:3000/@react-refresh net::ERR_ABORTED 404 (Not Found)
> ```

I am facing exactly this same problem.
Is there any update on it ?

**Comment by malt03** [comment]
I have found that adding the following settings to vercel.json works fine locally.
```
"devCommand": "vite --port 3000"
```

Strangely, the following settings do not work.
```
"devCommand": "vite --port $PORT"
```

**Comment by ValeraKaktotak** [comment]
> I am stuck with a problem. In vercel only my rootlayout component is showing all other pages are not found. why?
> 
> this is my index.js file in pages folder
> 
> ```js
> export { default as Home } from "./home/Home";
> export { default as Definition } from "./definition/Definition";
> export { default as Bookmarks } from "./bookmark/Bookmarks";
> export { default as History } from "./history/History";
> export { default as Error } from "./Error";
> export { default as NotFound } from "./NotFound";
> ```
> 
> this is my App.jsx file
> 
> ```js
> import { createBrowserRouter, RouterProvider } from "react-router-dom";
> // import layout
> import { RootLayout } from "./components";
> // import pages
> import { Bookmarks, Definition, Error, History, Home, NotFound } from "./pages";
> 
> const router = createBrowserRouter([
>   {
>     path: "/",
>     element: <RootLayout />,
>     children: [
>       {
>         index: true,
>         element: <Home />,
>         errorElement: <Error />,
>       },
>       {
>         path: "search/:searchWord",
>         element: <Definition />,
>         errorElement: <Error />,
>       },
>       {
>         path: "bookmarks",
>         element: <Bookmarks />,
>         errorElement: <Error />,
>       },
>       {
>         path: "history",
>         element: <History />,
>         errorElement: <Error />,
>       },
>     ],
>   },
>   {
>     path: "*",
>     element: <NotFound />,
>   },
> ]);
> 
> function App() {
>   return (
>     <>
>       <RouterProvider router={router} />
>     </>
>   );
> }
> 
> export default App;
> ```
> 
> It is working perfectly fine on my device or if i forward port with my friend, but in vercel only rootlayout is showing, all other pages are not found.
> 
> In my local env ![IMG-20240426-WA0016.jpg](https://private-user-images.githubusercontent.com/136841290/325908984-06c1b0fc-b2b7-4a6a-affa-a7ee82d20d3c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzIxMTYsIm5iZiI6MTcxNjM3MTgxNiwicGF0aCI6Ii8xMzY4NDEyOTAvMzI1OTA4OTg0LTA2YzFiMGZjLWIyYjctNGE2YS1hZmZhLWE3ZWU4MmQyMGQzYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwOTU2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Mjk4Y2M0NGExZWU3MjZlN2UxZjYwYjY4MzNmZGQ3ZTkzYzRmYWRhNzMwYmQ1ZmE0OWM5NDgzZjYyYjFkZTYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fJyRSAlEr6HhsM0n-CXJf5mA9o0dYBgPLzb0S1gk10A)
> 
> In vercel ![IMG-20240426-WA0017.jpg](https://private-user-images.githubusercontent.com/136841290/325909113-147c19e1-b828-4dbe-acf5-5fd6c3f3aaa2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzIxMTYsIm5iZiI6MTcxNjM3MTgxNiwicGF0aCI6Ii8xMzY4NDEyOTAvMzI1OTA5MTEzLTE0N2MxOWUxLWI4MjgtNGRiZS1hY2Y1LTVmZDZjM2YzYWFhMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwOTU2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTg3NDU0NDgxZjkwYWM4ZWExNTA0NGRjYWJmNTBhNzFiNDgyOTYzMzJjNDRhYjFhOGYwMDVmZDg1MjNiNjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TgzItUspxceNJfJHzYOXkcAkw4aWEPJFQR3PmHsCZls)
> 
> ![IMG-20240426-WA0015.jpg](https://private-user-images.githubusercontent.com/136841290/325909142-5e5f3c59-1bdb-4c9e-b477-58f3c59aef9c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzIxMTYsIm5iZiI6MTcxNjM3MTgxNiwicGF0aCI6Ii8xMzY4NDEyOTAvMzI1OTA5MTQyLTVlNWYzYzU5LTFiZGItNGM5ZS1iNDc3LTU4ZjNjNTlhZWY5Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwOTU2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWYwYjllNWY3NGIxYmY3NDQwYTUyMzYyNzVkODA5Y2ZlOWRlZGNlYzNiMzI5ZGJlNWM3ZTY2NDAyOWQ5ZDY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E52tamhyaSm0T3LenYFSXEixyrRdwrFr4IBk4oEygBU)
> 
> this is my RootLayout.jsx file
> 
> ```js
> import { Container } from "@mantine/core";
> import React from "react";
> import { Outlet } from "react-router-dom";
> import Navbar from "./Navbar";
> 
> function RootLayout() {
>   return (
>     <>
>       <Container size="md" pos="sticky" top={0} style={{ zIndex: 5 }}
>       bg={"var(--mantine-color-body)"}>
>         <nav>
>           <Navbar />
>         </nav>
>       </Container>
>       <Container size="sm">
>         <main>
>           <Outlet />
>         </main>
>       </Container>
>     </>
>   );
> }
> 
> export default RootLayout;
> ```

Hi, did you solve this problem?

**Comment by trek** [comment]
Hi @Montana,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.

**Comment by leerob** [comment]
Following up, React Router v7 is now supported on Vercel: https://x.com/vercel_changes/status/1890104465862332725
