### ISSUE TITLE
Documentation for `vercel pull` is missing

### ISSUE THREAD

**Issue by dcastil** [zeit/now#7477]
Hi Vercel people! 👋

I upgraded to the Vercel CLI v24 and got a deprecation warning for my `vercel env pull` command saying "WARN! `vercel env pull` is deprecated and will be removed in future releases. Run `vercel pull` instead." (added in https://github.com/vercel/vercel/pull/6822).

The documentation at https://vercel.com/docs/cli still shows the `vercel env pull` command everywhere and there is no info about the new `vercel pull` command. Would be nice to update the docs website!

For anyone who is searching for some documentation on `vercel pull`, `vercel pull --help` might help.

**Comment by verbose117** [comment]
`vercel env pull` command is deprecated as of PR https://github.com/vercel/vercel/pull/6822.

But running the command still outputs the deprecated message:
https://github.com/vercel/vercel/blob/f84d43e3af8a8408de3a3990b2ac2e9c482949dd/packages/cli/src/commands/env/index.ts#L139-L147

**Comment by MaedahBatool** [comment]
PR Done: https://github.com/vercel/front/pull/12963

**Comment by PaulRBerg** [comment]
`vercel pull` accepts a `--token` flag, but this is not documented in `vercel pull --help`:

```text
Vercel CLI 28.8.0

  ▲ vercel pull [project-path]

 Options:

    -h, --help                     Output usage information
    -A FILE, --local-config=FILE   Path to the local `vercel.json` file
    -Q DIR, --global-config=DIR    Path to the global `.vercel` directory
    -d, --debug                    Debug mode [off]
    --environment [environment]    Deployment environment [development]
    -y, --yes                      Skip questions when setting up new project using default scope and settings

  Examples:

  – Pull the latest Environment Variables and Project Settings from the cloud
    and stores them in `.vercel/.env.${target}.local` and `.vercel/project.json` respectively.

    $ vercel pull
    $ vercel pull ./path-to-project

  – Pull for a specific environment

    $ vercel pull --environment=<production | preview | development>

  If you want to download environment variables to a specific file, use `vercel env pull` instead.
```
