### ISSUE TITLE
[BUG] cannot remove certs from CLI, `certs rm` caused `length of undefined` error.

### ISSUE THREAD

**Issue by wiiiimm** [zeit/now#7493]
cannot remove certs from CLI, `certs rm` caused `length of undefined` error.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/179761/155923894-cf2b5a42-5546-4bfe-b7ed-4440b3bfed86.png">

**Comment by mglagola** [comment]
@williamli can you repro on latest - should be fixed on `24.x.x`
