### ISSUE TITLE
"Github: silent" does not remove deployment bot comments

### ISSUE THREAD

**Issue by HaraldNordgren** [zeit/now#7524]
We have vercel.json files in root, and in each sub-package, based on https://vercel.com/support/articles/how-to-prevent-vercel-github-comments:

```
{
    "github": {
        "silent": true
    }
}
```

It removes the post made by the bot, but does not remove the deployment comments:

![Screenshot 2022-03-06 at 08 47 31](https://user-images.githubusercontent.com/9569897/156914319-abdecd0f-dfb5-4bea-8171-3d5e78b64f31.png)

**Comment by marco-salcedo** [comment]
Yeah it's unfortunate... There's no point in trying to tidy-up commit history with these comments cutting in between code clean-ups 🧹

**Comment by mcmxcdev** [comment]
In our case, Vercel just started adding redundant comments to PRs again, although `github.silent` is already set for multiple months.

**Comment by sebmoonpay** [comment]
+1 on this, would be amazing to fix 🙏

**Comment by michaldudek** [comment]
Bumping for visibility. We have a monorepo with various apps deploying to Vercel and its overkill in our PR's, impossible to follow conversations :/

**Comment by inf1nite-lo0p** [comment]
Are there any plans to address this issue in the near future? Tracking commits and conversations within monorepos has become quite challenging due to this behavior.

It would be greatly appreciated if we could find a workaround or temporary solution to mitigate this problem until a proper fix is implemented.

**Comment by feliperugai** [comment]
+1 💔

**Comment by drianoaz** [comment]
The Vercel team [released a new feature](https://vercel.com/changelog/disable-git-integration-comments) and github.silent will be deprecated

> Previously, there was a `github.silent` setting available in `vercel.json` that didn't allow more granular control over disabling comments. We will be deprecating that option on **Monday, September 25, 2023**. There is no action required at this time to prepare for deprecation. Until that date, if you set that option in your `vercel.json` file we will continue to read it, and update the configuration in the dashboard accordingly.

**Comment by essenmitsosse** [comment]
Just to be clear, to new solution in the [link](https://vercel.com/changelog/disable-git-integration-comments) @drianoaz posted doesn't solve the problem of the deploy notifications in @HaraldNordgren's initial post in this issue.

**Comment by trek** [comment]
Hi @HaraldNordgren,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.

**Comment by HaraldNordgren** [comment]
@trek Has the issue been solved?
