### ISSUE TITLE
Hugo default template builds are failing

### ISSUE THREAD

**Issue by swarnava** [zeit/now#7525]
### Step to reproduce:-

- Go to https://vercel.com/new/clone?s=https%3A%2F%2Fgithub.com%2Fvercel%2Fvercel%2Ftree%2Fmain%2Fexamples%2Fhugo&template=hugo&id=67753070&b=main&from=templates
- Setup the project

### Result:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/1162991/156918663-820b1d92-57fa-4ffe-aaca-b2a64b0687c5.png">

`WARN 2022/03/06 07:07:25 Module "ananke" is not compatible with this Hugo version; run "hugo mod graph" for more information.
Error: add site dependencies: load resources: loading templates: "/vercel/path0/themes/ananke/layouts/partials/func/warn.html:15:1": parse failed: template: partials/func/warn.html:15: function "warnf" not defined
Error: Command "hugo -D --gc" exited with 255`

**Comment by swarnava** [comment]
cc @leerob for visibility

**Comment by leerob** [comment]
Very strange - it works locally for me with the latest version of Hugo (0.92.2).

**Comment by leerob** [comment]
It also worked when deploying here: https://vercel.com/now-examples/hugo/CjrLpgKLUFLX1Q9ZNPWRspgdUXQC

Original PR: https://github.com/vercel/vercel/pull/7467

**Comment by swarnava** [comment]
@leerob Thank you for looking into it. Do you think we can debug and potentially fix this anytime soon?

**Comment by leerob** [comment]
Maybe we should just revert the default Hugo version back to what it was before.

**Comment by eelzter** [comment]
The default project is still failing in the same way swarnava reported.

**Comment by leerob** [comment]
That was the minimum version listed in the repo, and it worked locally. Very strange. 

Might need to use a more barebones starter.

**Comment by leerob** [comment]
https://github.com/vercel/vercel/pull/7601

**Comment by leerob** [comment]
I'm at a loss... builds fine locally, deploys fine through the CLI

<img width="628" alt="CleanShot 2022-03-22 at 08 43 47@2x" src="https://user-images.githubusercontent.com/9113740/159495402-475a5d50-4df2-427c-981d-f83e8e09769a.png">

**Comment by syahnur197** [comment]
I still got this error message
![image](https://user-images.githubusercontent.com/18722385/173995527-a8976219-f525-493a-b1e7-3c5f7c1d3afc.png)

**Comment by swarnava** [comment]
> I still got this error message !

@syahnur197 Please create a support issue using https://vercel.com/support/request

**Comment by whyboris** [comment]
Just tried with the `ananke` theme and got the same error:
```
[17:59:52.608] Cloning github.com/whyboris/utilitarianism.net (Branch: main, Commit: da7cd8c)
[17:59:54.447] Cloning completed: 1.838s
[17:59:54.726] Looking up build cache...
[17:59:54.856] Build Cache not found
[17:59:54.900] Running "vercel build"
[17:59:55.566] Vercel CLI 28.2.2
[17:59:55.925] WARN 2022/09/02 21:59:55 Module "ananke" is not compatible with this Hugo version; run "hugo mod graph" for more information.
[17:59:55.959] Error: add site dependencies: load resources: loading templates: "/vercel/path0/themes/ananke/layouts/partials/func/warn.html:15:1": parse failed: template: partials/func/warn.html:15: function "warnf" not defined
[17:59:55.961] Error: Command "hugo -D --gc" exited with 255
```
When I run `hugo mod graph` as recommended locally, I get one line output `project ananke` 🤷 

Any suggestions appreciated 🙇

**Comment by whyboris** [comment]
**POSSIBLE SOLUTION**:

Include the exact version of _Hugo_ as an _environment variable_:

https://github.com/vercel/vercel/discussions/5834#discussioncomment-2547277

![add an environment variable](https://user-images.githubusercontent.com/67298905/162816903-906c04ed-6810-4ae6-85b9-fca5bebf127c.png)
