### ISSUE TITLE
Inability to use loadFilesSync (or any other dir requiring tool) in Vercel

### ISSUE THREAD

**Issue by EngHans** [zeit/now#7626]
Context
===

It is often useful to require several files in a directory, a very common example is that of [merging graphql schemas](https://www.graphql-tools.com/docs/schema-merging), for which the [file loading tool `loadFilesSync`](https://www.graphql-tools.com/docs/schema-merging#file-loading) is used.

There are also several packages out there that _[require dirs](https://www.npmjs.com/search?q=require%20dir)_ for other purposes. However the usage of any of these is problematic (if not impossible) at the time.

----------------------------

MWE
===
Code
---
Consider the following MWE (create the following files in the same directory or you can clone [this repo](https://github.com/EngHans/Vercel-Error)):
`index.js`
```
const http = require('http');
const requireDir = require('require-dir');
const exportsObject = requireDir(__dirname, { recurse: false });

http.createServer(function (req, res) {  
    res.write(`Hello World!, this moment is: ${exportsObject.myMoment.now}`);  
    res.end();  
}).listen(3000);

console.log('Server running at 3000'); 
```
`myMoment.js `
```
const moment = require('moment');

module.exports = {
  now: moment().format()
}
```
`package.json`
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "directories": {
    "test": "tests"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "moment": "^2.29.1",
    "require-dir": "^1.2.0"
  }
}
```
`package-lock.json`
```
{
  "name": "test",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "moment": {
      "version": "2.29.1",
      "resolved": "https://registry.npmjs.org/moment/-/moment-2.29.1.tgz",
      "integrity": "sha512-kHmoybcPV8Sqy59DwNDY3Jefr64lK/by/da0ViFcuA4DH0vQg5Q6Ze5VimxkfQNSC+Mls/Kx53s7TjP1RhFEDQ=="
    },
    "require-dir": {
      "version": "1.2.0",
      "resolved": "https://registry.npmjs.org/require-dir/-/require-dir-1.2.0.tgz",
      "integrity": "sha512-LY85DTSu+heYgDqq/mK+7zFHWkttVNRXC9NKcKGyuGLdlsfbjEPrIEYdCVrx6hqnJb+xSu3Lzaoo8VnmOhhjNA=="
    }
  }
}
```
`vercel.json`
```
{
  "version": 2,
  "builds":[
    {
      "src": "/index.js",
      "use": "@vercel/node"
    }
  ]
}
```
Issue an `npm ci` to install the dependencies in your machine.

Expected Result
---
When issuing `vercel dev` the application should run locally without any problem, as well as in the vercel platform

Current Result
---
When issuing `vercel dev` the application _does_ run locally without any problem. However issuing a `vercel` in the command line (or deploying the project via Git) results in a bug online, the app won't be built properly and the result is the following (you can check it [here](https://vercel-error.vercel.app/)):

![Vercel Error](https://user-images.githubusercontent.com/4950602/160269470-f4f7c858-5263-4d46-8b76-5bf9bbefa956.png)

In regards to the errors capture by the Logs, they can vary depending on the situation, a couple of examples are:
- `undefined	ERROR	Cannot find module 'module-name'`
- The one in the app in the MWE related to getting a method from the package.

Related Issues
===
I've identified a couple of issues here and there that are somewhat related to this problem, maybe they can be used as a frame of reference (or maybe another user can find a proper solution in their case) in any of those threads:
- https://github.com/ardatan/graphql-tools/discussions/4209
- https://github.com/vercel/next.js/discussions/25615
- https://github.com/vercel/next.js/issues/26987
- https://github.com/piglovesyou/graphql-let/issues/534

In the case reproduced by the MWE above, the solution is not in any of them (or I couldn't implement it).

**Comment by Gr33nLight** [comment]
Hello, 
I'm having a similar issue did you find a solution?

I load the resolvers with loadFilesSync like so:
`import path from 'path';

import { loadFilesSync } from '@graphql-tools/load-files';
import { mergeResolvers, mergeTypeDefs } from '@graphql-tools/merge';
import { DateTimeResolver } from 'graphql-scalars';

const typesArray = loadFilesSync(path.join(process.cwd(), 'lib/typeDefs'));
const resolversArray = loadFilesSync(path.join(process.cwd(), 'lib/resolvers'), {
  useRequire: true,
  requireMethod: require,
});

resolversArray.push({
  DateTime: DateTimeResolver,
});

export const resolvers = mergeResolvers(resolversArray);
export const typeDefs = mergeTypeDefs(typesArray);
`

And one of the resolvers that are loaded start like this:

`const { AuthenticationError } = require('apollo-server-micro');
const { serialize, parse } = require('cookie');
const { sign, verify } = require('jsonwebtoken');

const { randomBytes, pbkdf2Sync } = require('crypto');

const TOKEN_NAME = 'token';
const MAX_AGE = 60 * 60 * 8;
`

I'm getting an error that it can't load the cookie module

**Comment by EngHans** [comment]
@Gr33nLight Nope, I haven't been able to make it work automatically.

I asked directly in the vercel support service and received the following answer from a senior customer success engineer by the name of Samuel Ko:

> Hi there,
> 
> Unfortunately, Vercel is a Serverless and Edge-first platform and does not support running servers. Vercel is, however, committed to dynamic frontends coupled with [Serverless Functions](https://vercel.com/docs/concepts/functions/serverless-functions) and [Edge Functions](https://vercel.com/docs/concepts/functions/edge-functions).
> 
> You can find more information about why running servers is not possible using the Vercel platform in [this article](https://vercel.com/knowledge/npm-run-start-not-working).
> 
> Please let us know if you have any further questions or concerns.

It is not completely clear for me why it is not supported, as the answer is very vague. I believe it's because the incapability to run servers comes with the inability to have a filesystem running, the libraries do not know where to look for.

I had to require the modules manually as a temporary solution, that does not go without saying that I still need a proper way to require all modules in a directory without having to do it manually.
