### ISSUE TITLE
Change "serveless functions" folder.

### ISSUE THREAD

**Issue by tirrth** [zeit/now#7648]
### Discussed in https://github.com/vercel/vercel/discussions/5172

<div type='discussions-op-text'>

<sup>Originally posted by **gabrielgrs** September 10, 2020</sup>
Hello people!

I am starting to use vercel serveless functions and I am loving it! 
But I am not liking to use it inside "pages". 
Is there a way to change the path of the functions?

Thanks!
</div>

**Comment by KittyGiraudel** [comment]
Looks like this should be posted in the Next.js repository, not on the Vercel one?

**Comment by tirrth** [comment]
> Looks like this should be posted in the Next.js repository, not on the Vercel one?

Amm, I actually want this for all the Vercel supported frameworks and not just for the Next. I have one mono-repo and I really would not want to add the API folder on the root. Because if I do that, it's going to create serverless functions for all of my projects/apps from the mono-repo. Instead, I would like to put it in one specific directory and let Vercel know that I want to create the serverless functions for only this project and not for all from the mono-repo.

**Comment by trek** [comment]
Hi @tirrth,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
