### ISSUE TITLE
Issue With `microtime` Package (And Possibly Any  NPM Module) That Requires Node Add-Ons In Vercel's Serverless Node Runtime Environment

### ISSUE THREAD

**Issue by iknowhtml** [zeit/now#7706]
I'm having an issue with using the [`@toruslabs/customauth` package](https://github.com/torusresearch/CustomAuth) that has a dependency on the [`broadcast-channel` package](https://github.com/pubkey/broadcast-channel) that depends on the[`microtime` package](https://github.com/wadey/node-microtime) that uses the [`node-gyp-build` package](https://github.com/prebuild/node-gyp-build) to determine what Node addon to return (see https://github.com/wadey/node-microtime/blob/master/index.js). 

The Next.js app works locally with no issue, but once it's deployed, the following error occurs:
![image](https://user-images.githubusercontent.com/3343762/164762956-e567f414-b25f-4825-b64d-220b5e2ac3da.png)

I believe what's happening is that the Node addons are not being uploaded to the Vercel's Serverless environment:
![image](https://user-images.githubusercontent.com/3343762/164763822-1c7075b8-993d-4c56-b549-75c580195ec5.png)

According to [Vercel's documentation](https://vercel.com/docs/runtimes#advanced-usage/technical-details/including-additional-files), static analysis is used to determine what files to include in the Serverless Function by looking at calls to `require()` or `fs.readFile()`. 
I've tried using the `patch-package` to point the `require`  statement  in the [index file for `microtime`](https://github.com/wadey/node-microtime/blob/master/index.js) directly to the correct Node addon as below:
```javascript
const path = require('path');
module.exports = require(path.join(__dirname, 'prebuilds','linux-x64','node-napi.node'));
```
(**NOTE**: The above works locally on my MacBook if I switch `linux-x64` to `darwin-x64`) as well as the following Vercel configuration using `includeFiles`:
```json
// vercel.json
{
    "functions": {
        "pages/api/hello.js": {
            "includeFiles": ["node_modules/microtime/prebuilds/**"]
        }
    }
}
```

I believe this is an issue for any codebase that relies on package(s) that leverage Node addons as seen in https://github.com/nhost/nhost/issues/419.

Any help would be greatly appreciated. Thank you!

**Comment by RobertJif** [comment]
I'm having the same issue, have you found fix for this ?

**Comment by iknowhtml** [comment]
@RobertJif, I migrated our application from Vercel to Netlify for now.
I have an ongoing support ticket with Vercel, and I'm still waiting to hear back, but I need to deploy now, and can't wait for Vercel to get back to me.

**Comment by kallinlobus** [comment]
I also am having this issue.

**Comment by iknowhtml** [comment]
Issue is resolved (https://github.com/vercel/nft/pull/286).
