### ISSUE TITLE
Next.js middleware error not working on vercel

### ISSUE THREAD

**Issue by muhmushtaha** [zeit/now#7810]
Next: 12.1.6
Node: 14.x || 16.x
React: 17.0.2

I'm using nextjs middleware and facing an issue with the error method of NextResponse

Here is the code:

> if (request.method == 'HEAD') {
>     return NextResponse.error();
> }

The code ran without any issues on my machine but when I deployed the code on Vercel I got this error:

> Error: Failed to execute 'error' on 'Response': the method is not implemented.
>     at server/pages/_middleware.js:1918:0
>     at server/pages/_middleware.js:2237:0

**Comment by ntourne** [comment]
I got this issue running my Next.js app on Vercel. This the error log got on any request.

```
EvalError: Code generation from strings disallowed for this context
    at <anonymous>
    at ../node_modules/next/node_modules/regenerator-runtime/runtime.js:728:2
    at webpack/bootstrap:21:0
    at ../node_modules/next/dist/shared/lib/router/utils/querystring.js:51:11
    at webpack/bootstrap:21:0
    at ../node_modules/next/dist/shared/lib/router/utils/parse-relative-url.js:6:13
    at webpack/bootstrap:21:0
    at ../node_modules/next/dist/shared/lib/router/utils/parse-url.js:7:24
    at webpack/bootstrap:21:0
    at ../node_modules/next/dist/shared/lib/router/utils/prepare-destination.js:10:16
```

Also, there's no error at build time (on Vercel and locally) and no error running the app (locally). The only issue is at Vercel.

The hot fix solution was just removing `/pages/_middleware.ts` file.
This file didn't change for the last 5 months and also no new module was installed in the app.
So, it seems to be an issue related to Vercel  🤔

**Comment by j4nos** [comment]
Similar here: https://github.com/vercel/vercel/issues/8169

**Comment by guygreenleaf** [comment]
Dropping by to report that this seems to still be an issue in 12.3.0.  

Even though the docs [explicitly mention](https://nextjs.org/docs/advanced-features/middleware#using-middleware) that this is how things should be done in regards to directory structure and exports. 

Very disappointing that it seems as if there's hoops one must jump through to get what could be a fantastic solution to actually work.

**Comment by rajdeepdatta2898** [comment]
Is there any solution to this problem?

**Comment by trek** [comment]
Hi @muhmushtaha,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
