### ISSUE TITLE
Why all of my file is not showed when i am using vercel.json?

### ISSUE THREAD

**Issue by GuckTubeYT** [zeit/now#7848]
Why my all file on my github not showed when i am using vercel.json?
When i dont use the vercel.json, the HTTP Server Node JS is not running, but when i am using vercel.json, the HTTP Server Node JS is running, but the file, like .cpp .c is not showed

vercel.json
```
{
	"version": 2,
	"builds": [
		{
			"src": "index.js",
			"use": "@vercel/node"
		}
	],
	"routes": [
		{
			"src": "/(.*)",
			"dest": "/"
		}
	]
}

**Comment by GuckTubeYT** [comment]
sorry if my grammar is bad

**Comment by Schniz** [comment]
Hi! I'm not sure what you mean by that and/or how I can help. Can you give an example of what is the expectation and what actually happens?

i.e. a repo or something, some steps you've taken, etc? :pray:

thanks in advance
