### ISSUE TITLE
@vercel/node: Support ESM with TS

### ISSUE THREAD

**Issue by JuanM04** [zeit/now#7908]
Add support for ESM in Serverless Functions. AWS Lambda [supports ESM](https://aws.amazon.com/blogs/compute/using-node-js-es-modules-and-top-level-await-in-aws-lambda/) by having a `package.json` file with `{"type":"module"}`.

This is already possible with Build Output v3 ([SvelteKit](https://github.com/sveltejs/kit/blob/master/packages/adapter-vercel/index.js#L470) and [Astro](https://github.com/withastro/astro/blob/main/packages/integrations/vercel/src/serverless/adapter.ts#L49-L51) use this method), and it could be great to have something similar for standalone `api/` functions.

---

Related issues
- #7540

**Comment by styfle** [comment]
We do support ESM already and there is a fix for `vercel dev` here https://github.com/vercel/vercel/pull/7946

Can you share an example that isn't working?

**Comment by JuanM04** [comment]
I've tried with a `api/test.js` file and worked perfectly — I don't know when that was fixed, but thank you! Nonetheless, with an `api/test.ts` doesn't work: https://github.com/JuanM04/vercel-esm-repo

**Comment by styfle** [comment]
TS needs a tsconfig.json to enable ESM with

“module”: “esnext”

https://www.typescriptlang.org/tsconfig#module

**Comment by JuanM04** [comment]
Updated the repo and it continues failing.

**Comment by styfle** [comment]
Thanks, see #7954

**Comment by user72356** [comment]
I'm in the exact same boat. The PR above has been stuck for months?
