### ISSUE TITLE
[CLI] Feature Request: `vc pull` to support pulling envs from custom-defined environments

### ISSUE THREAD

**Issue by wiiiimm** [zeit/now#7970]
https://vercel.com/docs/cli#commands/pull

Right now `vercel pull` supports pulling envs from preview, production, and development environments. 
We should also allow it to pull from custom-defined environments.

**Comment by haneenmahd** [comment]
what do you mean by custom defined environments?

**Comment by trek** [comment]
Hi @williamli,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. At this time we don't have custom environments but that feature is coming soon!
