### ISSUE TITLE
First time using vercel, can't register or login to vercel via GitHub

### ISSUE THREAD

**Issue by YangWaldon** [zeit/now#7996]
When I try to log in to vercel with gith, it already shows successful authorization on GitHub, but it reports an error on the vercel page
![image](https://user-images.githubusercontent.com/49675185/174435750-42a2a267-09d7-475f-9d20-1252db8cf827.png)
![image](https://user-images.githubusercontent.com/49675185/174435694-ba5a1171-6690-4ba5-9888-dc5163cb58b9.png)
![image](https://user-images.githubusercontent.com/49675185/174435706-1ce5aa41-a65d-4b1c-9785-339f41c9ee98.png)

**_### When I tried to sign up for vercel with GitHub, I found that I actually still need a mobile number ------ Do I have to use a mobile number to sign up for vercel now?_**
![image](https://user-images.githubusercontent.com/49675185/174435726-9648be32-54ea-413c-928c-05d734c62396.png)

**Comment by haneenmahd** [comment]
you should probably use the signup page instead of the login page. you are now in login page and linking an account with GitHub and vercel does not find an existing account that was created.

**Comment by crmapache** [comment]
Same shit happens to me

**Comment by ghost** [comment]
Also facing similar issues. 

Is vercel closing account activation for new users?

**Comment by trek** [comment]
Hi @YangWaldon,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
