### ISSUE TITLE
Inappropriate "dead end" in ux when creating a sub-domain

### ISSUE THREAD

**Issue by Johnrobmiller** [zeit/now#8006]
Thank you for considering and reading this ticket. I am not asking for help to solve a problem, but rather reporting a bug that should be fixed.

I would have used the case-reporter tool provided by vercel, but they don't allow the user to upload images. This might be worth opening a ticket for in of itself since it is not known how many users with valid issues failed to report them because they were unable to upload images in the case-reporter tool and gave up.

I've been wrestling with the ux for creating a sub-domain for about 30 minutes now. Screenshot:

![image](https://user-images.githubusercontent.com/55205360/175324943-c23e334f-fef5-4557-8e41-47f44cf8b400.png)

The UX is telling me "invalid configuration", but it does not say why, nor does it point me to any useful resource that might help. The "learn more" button points to a resource unlikely to be relevant to the problem, as it is an article about domain verification, not domain configuration. Even if it were helpful, it is not co-located near the error icon, and the label does not in any way suggest that it would be helpful to solve this problem. 

This is a UX "dead end", which, although not a "bug" in a technical sense, it is still a "design bug" that should be handled.

**Comment by andymckay** [comment]
Thank you for the issue @Johnrobmiller I've sent this feedback over to the team that looks after user interface 🙇🏾

**Comment by jedahan** [comment]
Still seeing this issue, as reported in https://github.com/orgs/vercel/discussions/240

Just some clarification - does "completed" mean "this should be fixed, and if it isn't, this is a bug" or simply "we are now tracking this issue internally"?
