### ISSUE TITLE
Error: Detected linked project does not have "id"

### ISSUE THREAD

**Issue by yanstu** [zeit/now#8028]
### Discussed in https://github.com/vercel/vercel/discussions/8027

<div type='discussions-op-text'>

<sup>Originally posted by **yanstu** June 28, 2022</sup>
![image](https://user-images.githubusercontent.com/47344296/176066629-b5633f2a-5a39-4ad5-abf7-64da335cbf6f.png)
</div>

**Comment by amyegan** [comment]
Hi @yanstu. Can you verify that your `.vercel` directory has been set up correctly? This should happen automatically if you [link a project with the Vercel CLI](https://vercel.com/docs/cli#introduction/project-linking).

**Comment by Christopher-Hayes** [comment]
Had this happen when I used `vercel link`. Had to first run `vercel`. Seems weird that `vercel` would work, and `vercel link` wouldn't when they seem to do the same thing.

**Comment by hitesh-c** [comment]
Try changing project root folder name and redeploy, it worked for me.
