### ISSUE TITLE
Vercel CLI @25.2.1 Error 

### ISSUE THREAD

**Issue by sanjayheaven** [zeit/now#8046]
```sh
Vercel CLI 25.2.1
Retrieving project…
Error! Command failed: git status -s
/bin/sh: git: not found
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1
```

**Comment by jlarmstrongiv** [comment]
That probably means you don’t have git installed or git is not available in your path.  You can check by running `command -v git`

**Comment by muhammad-saleh** [comment]
We have the same error, our deployments through CI/CD are not working anymore.
Please check here: https://github.com/vercel/vercel/discussions/8043

**Comment by TooTallNate** [comment]
Indeed. Please let us know if you still are having issues @sanjayheaven.
