### ISSUE TITLE
Type error: Cannot find module 'xxx' or its corresponding type declarations.

### ISSUE THREAD

**Issue by nelsonlaidev** [zeit/now#8066]
# Info
Next.js: 12.1.6
Platform: Windows 11
Repo: [tszhong0411/honghong.me](https://github.com/TszHong0411/honghong.me)

---

Hello, I get this error when it is building on vercel. That error just happen on vercel. It can successfully build on local. It looks like a system platform issue. It is weird. The module was successfully imported at line 6.

![Snipaste_2022-07-01_15-36-38](https://user-images.githubusercontent.com/75498339/176847609-3de3b48f-7b18-4b17-a4d7-ff948a85c648.png)

---

# Another error

I tried to rename `@/components/analytics` to `@/components/Analytics`. Then get the below error.

## Similar question:
- [Stackoverflow #67172043](https://stackoverflow.com/questions/67172043/vercel-cli-build-fails-with-error-type-error-cannot-find-module-formik-or-it)

![Snipaste_2022-07-01_15-40-48](https://user-images.githubusercontent.com/75498339/176848328-707de879-a586-43a2-a52b-7dfffc185c8c.png)

**Comment by pan93412** [comment]
Seems like it is the case sensitive issue between NTFS and common partition formats in Linux (ext4). Maybe you need to rename the wrong file to another name, and rename it back to the version with correct case.

**Comment by nelsonlaidev** [comment]
> Seems like it is the case sensitive issue between NTFS and common partition formats in Linux (ext4). Maybe you need to rename the wrong file to another name, and rename it back to the version with correct case.

Thanks a lot. It works perfectly.
