### ISSUE TITLE
`rewrite()` from @vercel/edge not functioning

### ISSUE THREAD

**Issue by CTNicholas** [zeit/now#8081]
## Description
Hey everyone, I was trying out `rewrite()` from `@vercel/edge`, and it seems to have no effect. I've tried this in SvelteKit projects and also in an Astro project and it works in neither. The page loads normally as if `next()` was called:
```js
import { next, rewrite } from '@vercel/edge'

// Nothing happens when visiting `/other`
export default function middleware (request) {
  const url = new URL(request.url)
  url.pathname = '/'
  return rewrite(url)
}

export const config = {
  matcher: ['/other']
}
```

Returning `next()` and `Response.redirect()` both work. This issue occurs in production too. Rewrites work fine in Next.js 12.2 projects using `NextResponse.rewrite()`.

## Reproduction
I've set up a SvelteKit reproduction:
```
git clone https://github.com/CTNicholas/vercel-edge-middleware-rewrite-issue
cd vercel-edge-middleware-rewrite-issue
npm i
vercel dev
```
Then go to http://localhost:3000/other. The source code is in `/middleware.js`. Here it is in [production](https://vercel-edge-middleware-rewrite-issue.vercel.app/other).

## System Info
```
Windows 10
Node 16.7.0
vercel 25.2.3
@vercel/edge 0.01
```

Let me know if I can help more. Love what you're doing with all the edge features!

**Comment by j4nos** [comment]
Similar here: https://github.com/vercel/vercel/issues/8169

**Comment by EndangeredMassa** [comment]
I believe this is resolved with: https://github.com/vercel/vercel/pull/8535

I tested your reproduction repo (thanks for this!) and I could see the wrong behavior on latest CLI, but the correct behavior on the version from this PR.

We'll release a new version of the CLI with this fix soon.

**Comment by EndangeredMassa** [comment]
@CTNicholas can you try https://github.com/vercel/vercel/releases/tag/vercel%4028.2.4? That resolved the issue when I tried.

**Comment by CTNicholas** [comment]
> @CTNicholas can you try https://github.com/vercel/vercel/releases/tag/vercel%4028.2.4? That resolved the issue when I tried.

✅ That fixes it, amazing, thanks!
