### ISSUE TITLE
npm install vercel fails when npm cannot find @vercel/hydrogen

### ISSUE THREAD

**Issue by rrcobb** [zeit/now#8104]
```shell
$ npm install --global vercel
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vercel%2fhydrogen - Not found
npm ERR! 404
npm ERR! 404  '@vercel/hydrogen@0.0.2' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rob/.npm/_logs/2022-07-08T01_08_44_972Z-debug-0.log
```

It looks like @vercel/hydrogen was added as a dependency recently, and isn't currently published on npm, leading installs to fail. Fixes might include publishing that package to npm or removing the dependency.

**Comment by rrcobb** [comment]
With yarn:
```
$ yarn global add vercel@latest
error Couldn't find package "@vercel/hydrogen@0.0.2" required by "vercel@latest" on the "npm" registry.
```

**Comment by jasonaravanis** [comment]
Can confirm I am also encountering the same issue

Downgraded to vercel@25.2.3 and appears to be working again

**Comment by BronsonQuick** [comment]
Our team's hit this issue as well with our CI/CD build. I'm guessing it's because the `@vercel/hydrogen` package is either private or hasn't been published.

I can confirm that @jasonaravanis's downgrading issue works for us for now. Thanks for the heads up Sir!

**Comment by hwhmeikle** [comment]
Also having this issue. Using `vercel@25.2.3` works in the interim as @jasonaravanis mentioned.

**Comment by tedmiston** [comment]
Broke my CI as well.

Example of failure: https://github.com/tedmiston/qcbrunch/runs/7243835366?check_suite_focus=true#step:16:1

**Comment by tedmiston** [comment]
Everyone mentions pinning to 25.2.3 but there is also a 26.0.0 (published 3 days ago).  27.0.0 (published 2 hours ago) is the latest release and the one that's definitely broken.

Anyone tried pinning to 26.0.0 yet?

**Comment by BronsonQuick-APL** [comment]
@tedmiston Good call. I can confirm that `vercel@26.0.0` works.

**Comment by rrcobb** [comment]
@TooTallNate fyi, I think you're implicated in the commit that introduces this issue: https://github.com/vercel/vercel/commit/f8e5df749cd33ab585b03533aedd58391c23b808#r77978626

**Comment by tedmiston** [comment]
> @tedmiston Good call. I can confirm that `vercel@26.0.0` works.

Cool.  Confirmed this pin is working for me as well.

```npm install -g vercel@26.0.0```

**Comment by TooTallNate** [comment]
Very sorry about that folks. It's fixed now.

**Comment by rrcobb** [comment]
Thanks for the fast fix @TooTallNate !!

**Comment by bennyschmidt** [comment]
I am having this issue today. Published a new version of a library, deployed to Vercel - Vercel says it can't find it, going on an hour now. Even though the npm does exist with that version. 

Note: This only happens on projects where the `npm i` is overridden which I had to do to support legacy deps.
