### ISSUE TITLE
Fix deprecated SvelteKit dev command in CLI

### ISSUE THREAD

**Issue by kbrgl** [zeit/now#8119]
SvelteKit switched to `vite dev` and `vite build` for its build and dev commands, but this is not reflected in the CLI or the website. (https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next359)

The fix for this should just be changing the devCommand and buildCommand to use the dev and build scripts in the package.json, since this should use whatever underlying script runner in appropriate.

https://github.com/vercel/vercel/blob/628071f6599402e6b7d8fb47ae2e0ed8f1ea3b39/packages/frameworks/src/frameworks.ts#L1021

**Comment by EndangeredMassa** [comment]
There was a PR opened for this, but we need it to consider version numbers for older projects. The new command is required as of version `1.0.0-next.359`. https://github.com/vercel/vercel/pull/8111

**Comment by ollyde** [comment]
I've switch the command, it runs but nothing shows. Any ideas? ..

**Comment by EndangeredMassa** [comment]
@ollyde What version of SvelteKit are you using? Can you share your repo (or a reproduction)?

**Comment by ollyde** [comment]
Going from 

"svelte": "^3.46.0"

 to 

"svelte": "^3.54.0"

Converted to projects, nothing shows, just white screen with no errors hmm.

**Comment by EndangeredMassa** [comment]
@ollyde are you using SvelteKit? If so, what version.

If I can get access to your repository, I could look deeper into what is happening.

**Comment by ollyde** [comment]
@EndangeredMassa unfortunately I can't share the repo. I've solved this by making a new project and copy pasting the old one in, not desired but works :-) thanks for helping.
