### ISSUE TITLE
Why Next.js raise error 502 Bad Gateway when loading / rewriting image from AWS S3?

### ISSUE THREAD

**Issue by j4nos** [zeit/now#8169]
We use middleware for url rewrite, and when image is loaded from AWS S3, Next.js / Vercel raise this error:

ROUTER_EXTERNAL_TARGET_HANDSHAKE_ERROR

when opening: 

https://tikex-dev.com/kubl/b1a1/j1vd/vree

Middleware should load in this image: https://t44-post-cover.s3.eu-central-1.amazonaws.com/vree-patch and display it.

```jsx
//middleware.ts

import { NextResponse, userAgent } from 'next/server'
import type { NextRequest } from 'next/server'

export function middleware(request: NextRequest) {
	const hostname = request.headers.get('host')
	const { ua } = userAgent(request)
	//ua.includes('facebook') || hostname.includes('facebook.com')
	if (true) {
		const url = request.nextUrl.clone()
		const a = url.pathname.split('/')
		url.hostname = 't44-post-cover.s3.eu-central-1.amazonaws.com'
		url.pathname = a[a.length - 1] + '-patch'
		url.port = '80'
		return NextResponse.rewrite(url)
	}
}

export const config = {
	matcher: ['/:organizationShortId/:postId/:tempUserShortId/:imgId'],
}
```

Following this tutorial: https://www.ctnicholas.dev/articles/how-to-use-nextjs-middleware

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/1AbrU.png

---

Is it possible Vercel can not handle a filesize of 6MB?

---

Maybe Vercel limiation was hit: https://vercel.com/docs/concepts/functions/edge-middleware/limitations

```
Memory
An Edge Function can only use up to 128MiB. If it exceeds this limit, the execution will be aborted and we will return a 502 error.
```

**Comment by trek** [comment]
Hi @j4nos,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
