### ISSUE TITLE
"Assign Domain" - a frustrating experience

### ISSUE THREAD

**Issue by kidonng** [zeit/now#8282]
After several times of making mistakes, I'm motivated to open this issue (support ticket: #00092156).

For a Production deployment, you can do two very similar things: "Promote to Production" and "Assign Domain". The difference is that "Assign Domain" uses the same deployment (so it's instant, similar to rollback on Netlify), while "Promote to Production" will make a new deployment using the same source.

Instinctively, due to the location they are placed in the menu, I tend to think "Promote to Production" is what I needed to do a rollback, only to be baffled about the new, possibly slow building deployment.

<img width="173" alt="image" src="https://user-images.githubusercontent.com/44045911/182037456-19e23b35-ed8c-4a66-9ae0-0a54d61966e8.png">

When I come to senses and going to "Assign Domain", a more mystifying popup appeared:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/44045911/182037627-39ade706-74f6-45aa-bd71-87f31eef3ad1.png">

In my opinion, the message is inappropriate in every way:

- I'm unlikely to be looking for project settings when I open the menu of a _specific_ deployment
- I don't want to buy "command-line interface" because I remember [how it was killed](https://github.com/vercel/vercel/issues/3767). It's very strange at this time, this action still _requires_ using CLI, while a web interface seems trivial to implement (I mean, [the code is there](https://github.com/vercel/vercel/blob/fc3fa61b593265ae0d1519761142bc79154746b5/packages/cli/src/commands/alias/set.ts))
- And it's not enlightening that I have to fill in `<deployment>` myself, when the message can certainly replace the placeholder with the real thing
- And lastly, which is the ultimate reason why I'm opening an issue here: this very command (`vercel alias`) does not show up in `vercel help`

I sincerely hope Vercel can do better.

**Comment by swarnava** [comment]
Hi,

> And lastly, which is the ultimate reason why I'm opening an issue here: this very command (vercel alias) does not show up in vercel help

This was added recently in v27.3.3 https://github.com/vercel/vercel/commit/dc8293dc13da28a04b03b920df29a98517e95c07.

I have forwarded rest of the feedback to the team. Thank you!

**Comment by swarnava** [comment]
Good news, we are working on similar feature to instantly rollback your deployment via Web Dashboard. Unfortunately, I don't have any concrete ETA on this. Request you to keep an eye on vercel.com/changelog.

**Comment by kidonng** [comment]
Thanks for your response, and no hard feelings! I'm loving Vercel more when I see your (promptly) replies, especially the good news.

Pardon me for posting this in public, it's just the support page is not convenient for writing this long article.

**Comment by swarnava** [comment]
It's absolutely fine. We love community and always hunt for feedback. Keep them coming. :)
