### ISSUE TITLE
*.vercel.app is contaminated by DNS in mainland China

### ISSUE THREAD

**Issue by george-jiang-wow** [zeit/now#8509]
Domain Name Speed Record
![](https://www.helloimg.com/images/2022/09/03/Z7n1XP.png)
I'm sorry for machine translation.

**Comment by george-jiang-wow** [comment]
The record may takes a few moments to view.

**Comment by Jerry23011** [comment]
Same problem since the last few days of August

**Comment by george-jiang-wow** [comment]
Oops. I'm sorry to have submitted this question in the wrong place. Someone has submitted it in vercel/community.
