### ISSUE TITLE
Express post route not working/

### ISSUE THREAD

**Issue by 0nahid** [zeit/now#8522]
When I try to create a data it says  Status: 500 Internal Server Error

```
{
"name": "John 2",
"gender": "male",
"contact": "+91-123-4567-89 2",
"address": "Bangalore 2",
"photoUrl": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
}
```
url for create hit [https://users-node-api.vercel.app/user/save](url)

**Comment by kiron0** [comment]
I'm facing the same issue.

URL Link: https://user-api-ts.vercel.app/user/save

**Comment by andymckay** [comment]
Thanks for the issue @0nahid and @kiron0 but we don't have enough information to go on here. An example reproduction of your problem would be useful. Even then it might not be this team. I suggest the best place to go would be support: https://vercel.com/help#issues
