### ISSUE TITLE
.vercelignore not ignoring files in build output 

### ISSUE THREAD

**Issue by dpcdev1999** [zeit/now#8571]
**Vercel CLI Version:** 28.2.5
**Platform:** OSX

I am building and deploying my vercel app using the following commands... 
`
npx vercel build 
`
`
npx vercel deploy --prebuilt
`

Building works but deploying is failing with an error:
`Invalid request: files should NOT have more than 15000 items, received 18960.`

I investigated the build artifacts output in .vercel/output and discovered that node_modules were being included within the functions directory. I removed the node_modules and then then ran vercel deploy again and it worked. 

Now that I know the issue is having the node_modules in my .vercel/output directory, I'm stuck because the .vercelignore doesn't seem to be doing the trick.

I am positive that the .vercelignore file is in my root directory. I have even tried ignoring all files with it. No matter what, vercel CLI tries to deploy every file to Vercel without excluding anything.

Here is what my .vercelignore file looks like:

.vercelignore 
`
node-modules
`

Is there something obvious I am missing anyone can point out ? Or could there be a bug with .vercelignore ?

Thank you!

**Comment by giancarlosisasi** [comment]
I'm getting the same issue https://github.com/vercel/vercel/discussions/8643 😢

**Comment by swarnava** [comment]
Hi @dpcdev1999, can you try `vercel deploy --prebuilt --archive=tgz` and let us know how it goes?
