### ISSUE TITLE
Vercel 404 error for dynamic routes containing characters "[" or "]"

### ISSUE THREAD

**Issue by tony3918** [zeit/now#8731]
Expected: the following two urls should both get the chunk made from building "pages/[page].js"
- https://test-delta-taupe-74.vercel.app/_next/static/chunks/pages/page/%5Bpage%5D-8c772344b88370b9.js
- https://test-delta-taupe-74.vercel.app/_next/static/chunks/pages/page/[page]-8c772344b88370b9.js
(even if you click the "[page]" url, your browser will probably change it to %5B, %5D but if you manually change %5B, %5D to [, ] in the browser, then you can access the chunk file)
<img width="778" alt="Screen Shot 2022-10-15 at 11 59 57 AM" src="https://user-images.githubusercontent.com/34783801/195966001-247ea323-9c7e-4d75-a4df-469cec172f6f.png">

Actual: the url with encoding(%5B, %5D) results in 404.

Apparently, this only happens in production hosted on Vercel. When hosted on localhost through "next start", both of the following urls correctly retrieve the js file.
- http://localhost:3000/(...)/%5Bpage%5D-(hash).js
- http://localhost:3000/(...)/[page]-(hash).js

I'm quite sure this was not an issue until yesterday but I cannot find anything related to why this would happen.

Any suggestions on how to resolve this bug or where to start looking would be greatly appreciated.

**Comment by ryanBuzzni** [comment]
Yes, I have same issue. 

From about 10:00 today, a dynamically routed page chunk file issue has occurred on the server and the service is not available.
.e.g.
https://saja.market/_next/static/chunks/pages/product/%5Bpid%5D-7e2f8caef162da38.js
net::ERR_ABORTED 404

When I changed it to https://saja.market/_next/static/chunks/pages/product/[pid]-7e2f8caef162da38.js, it opened

Please, check it quickly

and, I submitted to Vercel Help.

**Comment by jujumilk3** [comment]
Same issues are here

https://www.parachutehome.com/collections/living-room-furniture
https://www.parachutehome.com/collections/bedroom-furniture
https://www.sumup.com/en-us/

Every sites using vercel are broken. 

https://github.com/vercel/vercel/commit/d0a5676c263d423146b884da3ed3b96f284e9aff
I think above commit causes this issue.

**Comment by tony3918** [comment]
thanks Ryan I as well submitted a help ticket. Wish this gets resolved asap as this completely broke my other project

**Comment by felixnoriel** [comment]
i have the same issue happening right now

**Comment by yoojinkimm** [comment]
I have exactly the same issue from this morning. My service gets a lot of customer complaint.

**Comment by LaDMasC** [comment]
same problem..
our consumer is leaving my product..

**Comment by junhoyeo** [comment]
This make calls from `next/image` and `next/future/image` dead too: `/_next/image?url=%2F_next%2Fstatic%2F...`

**Comment by wsong0101** [comment]
Exact same issue is happening here too.. :(
The build was working fine but it happened suddenly.

**Comment by andonghun** [comment]
All the static files are broken. 😭

**Comment by leye195** [comment]
same problem here too.. all the static image files are broken :(

**Comment by supertree-emjay** [comment]
I have exactly the same issue from this morning. My service gets a lot of customer complaint.

**Comment by kors21** [comment]
I'm dealing with the same problem here. 
Hope it gets fixed soon.

**Comment by ijjk** [comment]
Hi, sorry for the trouble here, the issue has been identified and a fix being rolled out, please follow our status page for updates https://www.vercel-status.com/incidents/tnrdjcqfbxd7

**Comment by hyun-park** [comment]
After resolving the issue, please let us know about the compensation policy for the damage from this issue. The issue here is very critical.

**Comment by hyun-park** [comment]
@ijjk Any update on the compensation for this issue?

On your SLA(Service Level Agreement) page, it says: (https://vercel.com/legal/sla)
> If the Services fail to meet the above Services Level, you will receive a Credit equal to the result of the Services Credit calculation in [Section 4](https://vercel.com/legal/sla#credits) of this SLA.

Does this also apply to other plans too? Since five-hour downtime is definitely much lower than 99%.

**Comment by Pieparker** [comment]
Hey there! Customers on our Enterprise agreements are SLA-bound, that's correct. If this applies to you, please reach out to your representative for more details!

If you are not on an Enterprise agreement and have follow-up concerns around any on-going issues or account details, please open a Support case with our team at https://vercel.com/help. We want to ensure that we can fully address each concern while maintaining your account privacy.

**Comment by Smirow** [comment]
Not sure if it's related, but **pre-fetching** dynamic routes like `app/test/[testId]/leaf/` throws a 404.

**Comment by ijjk** [comment]
Hi, gonna close this as the original issue is resolved, please reach per-above!
