### ISSUE TITLE
Experiencing preload error

### ISSUE THREAD

**Issue by kfbfarley** [zeit/now#8768]
### Discussed in https://github.com/vercel/vercel/discussions/8767

<div type='discussions-op-text'>

<sup>Originally posted by **kfbfarley** October 24, 2022</sup>
`Error: File /vercel/path1/node_modules/simple-update-notifier/node_modules/semver/preload.js does not exist.`

![image](https://user-images.githubusercontent.com/42237552/197576578-22bcc9de-829b-4a62-aae5-1f0320f3ebef.png)
</div>

**Comment by andymckay** [comment]
Haven't heard a reply to the discussion which provided a work around. We are planning on removing `simple-update-notifier` soon, so then this won't be an issue. For that reason I'm going to close this issue, but please reopen if its still happening or there's more to discuss.
