### ISSUE TITLE
Vercel CLI: no option for git branch using vercel env pull

### ISSUE THREAD

**Issue by woochica** [zeit/now#8772]
Hi,

On the Vercel web admin it's possible to [specify environment variables per git branch](https://vercel.com/changelog/environments-variables-per-git-branch) which is great.

However this feature is only available for deployments. It would be great if the `vercel env` CLI tool would also support it.

Use case: in the CI environment I would like to do a `vercel env pull --environment=preview branch=my-feature-branch` to get the environment variables specific to that branch only. If there are matching environments for variables of the same name, currently `vercel env pull --environment=preview` pulls one of them which is not so consistent behaviour either.

**Comment by cromosom** [comment]
We need this feature as well.

**Comment by Kohei909Otsuka** [comment]
we need too.

Without this feature, It's impossible to deploy from CI/CD like Github Action when we have more than two(production/preview) stages.

https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

![全画面_2022_11_04_16_48](https://user-images.githubusercontent.com/11783802/199920628-cf78889b-ade9-4a13-81d9-63a9bca92a1d.png)

**Comment by Alexandredc** [comment]
+1 need this feature 🙏

**Comment by Kohei909Otsuka** [comment]
it looks like they added this feature !!

https://github.com/vercel/vercel/discussions/8994#discussioncomment-4283727

**Comment by woochica** [comment]
Thanks @Kohei909Otsuka for the heads-up! Indeed, this problem is solved!

> 🚀 The `--git-branch` option is available on `vc pull` and `vc env pull` now in [vercel@28.9.0](https://github.com/vercel/vercel/releases/tag/vercel%4028.9.0)!
