### ISSUE TITLE
Error: An unexpected internal error occured

### ISSUE THREAD

**Issue by Bhaney44** [zeit/now#8782]
Hi,

I got this error message during a deployment.

<img width="385" alt="Screen Shot 2022-10-25 at 6 13 12 PM" src="https://user-images.githubusercontent.com/43055154/197912166-2c898b3a-4706-4ede-8f7c-80d2a3463eec.png">

I was updated code on website that was already working. This [post on the Vercel website](https://vercel.com/docs/error/platform/INTERNAL_UNEXPECTED_ERROR) says to contact support. Any advice would be appreciated, thanks!

*Side note the feedback box is also broken and does not allow the user to click submit on MacOS*

**Comment by tyrong** [comment]
Receiving this when trying to promote to production

**Comment by lgmarenco1987** [comment]
Seems to be related to this: https://www.vercel-status.com/incidents/86840k3bvvwk so we may need to wait until this is solved

**Comment by Bhaney44** [comment]
> Seems to be related to this: https://www.vercel-status.com/incidents/86840k3bvvwk so we may need to wait until this is solved

Yes. This is the issue I am having. But I have no experience with the CLI for the work around. So, I'll have to wait until it is fixed. Thanks for the update.

**Comment by andymckay** [comment]
Sorry about that, I don't think there's anything else to do this on this particular issue at this time.
