### ISSUE TITLE
![IMG_20221030_023207](https://user-images.githubusercontent.com/116979899/198856711-de9ec0b6-7e8b-41ad-b39e-ca28e2eda894.jpg

### ISSUE THREAD

**Issue by AnAtOlIy1994** [zeit/now#8804]
![IMG_20221030_023207](https://user-images.githubusercontent.com/116979899/198856711-de9ec0b6-7e8b-41ad-b39e-ca28e2eda894.jpg

_Originally posted by @AnAtOlIy1994 in https://github.com/vercel/vercel/discussions/8803_

**Comment by chandru89new** [comment]
Looks like spam.
