### ISSUE TITLE
ERROR MongooseError: Operation users.findOne() buffering timed out after 10000ms

### ISSUE THREAD

**Issue by m0x61h0x64i** [zeit/now#8809]
hi, i have pro vercel, and i am using nodejs & express & mongoose & mongodb to connect to the mongodb atlas database, after hundreds of deployments on hobby vercel account i didnt have database connecttion failure error like when i am using pro vercel! now when i deploy on pro vercel, my application fails to connect to the mongodb atlas database, however some deployments it connects fast and well but some other deployments it takes more than 5 minutes to connect the application to the mongodb atlas database! (in my vercel's hobby account it was okay and maybe it could connect in less than a minute!)

my connection code is the following:
```
const mongoose = require('mongoose')

const connectDatabase = async () => {
    try {      
        await mongoose.connect(process.env.MONGODB_URI)
        console.log('Connected to mongodb database successfully!')
    } catch (err) {
        console.log(err)
    }
}
connectDatabase()
```
mongodb version : `5.0.13`
mongoose version: `6.5.4`
vercel account type: `pro`

the error i get when i try to send a query using my deployed application on vercel to use mongodb atlas database after new deployments: 
`ERROR MongooseError: Operation users.findOne() buffering timed out after 10000ms`

had this error on hobby vercel account?
`true, but it took small amount of time to connect to the mongodb atlas database, some deployments connects fast and well.`

did you add your server ip address to mongodb atlas database > security > network aceess > ip address?
`yes, i allowed access from everywhere, 0.0.0.0/0`

Is your url correct in your connection string?
`yes, it sometimes connects fast and well.`

Is your mongoose.connect(......) code loading?
`yes, i imported database connection code on the top of the project codes to be executed first.`

Is your code inside a file? like config.js?
`i tried both ways, i imported my connection code inside and outside of index.js file.`

**Comment by andymckay** [comment]
Hi @m0x31h0x64i I think this is out of scope for this repository and the team that looks after it. As a pro account customer, you contact support and they might be able to help: https://vercel.com/help#issues

**Comment by andymckay** [comment]
Closing based on last comment.
