### ISSUE TITLE
Deploying a simple Next.js webpage to vercel ignores the ```pages``` folder

### ISSUE THREAD

**Issue by michele-nuzzi** [zeit/now#8812]
I'm trying to deploy a very simple webpage built using Nextjs; basically static

the project works locally both using ```npm run dev``` (mapped as ```next dev```) and using ```npm run build``` followed by ```npm run start``` ( respectively ```next build``` and ```next start``` )

deploying the project on Vercel the output of ```next build``` is the same as the one I see locally
![Screenshot from 2022-10-31 11-06-40](https://user-images.githubusercontent.com/64633004/198989293-66cb1f17-3b38-4d45-9616-d6fa5fb14e7e.png)

however, accessing any page (both ```pages/index.tsx``` or any other non-index) results always in a 404 error;

allowing directory listing only the stuff in the ```public``` repository is there

**Comment by nickspaargaren** [comment]
Is this the result from a new installation of [create-next-app](https://nextjs.org/docs/api-reference/create-next-app)? Try: https://vercel.com/templates/next.js/nextjs-boilerplate

**Comment by pauliusuza** [comment]
I am getting the same symptoms with the latest next.js 13 builds, output folder does not contain the built files. Using app folder + pages/api/* for serverless. Serverless functions are not recognised as well.

**Comment by pauliusuza** [comment]
I got a response from Vercel support and it resolved my issue - it was as simple as selecting Next.js as the framework in the vercel settings.
