### ISSUE TITLE
Ignore Build Step (With Environment Variables) example doesn't work

### ISSUE THREAD

**Issue by IHIutch** [zeit/now#8863]
The Ignore Build Step - [With Environment Variables](https://vercel.com/guides/how-do-i-use-the-ignored-build-step-field-on-vercel#with-environment-variables) example doesn't work as documented:
`[ "$VERCEL_ENV" != production ]`

<img width="904" alt="image" src="https://user-images.githubusercontent.com/20825047/200410523-4013a664-fd9b-40bb-afef-0cc8a4bbc5fd.png">

I was attempted to prevent builds from a specific branch by following the example like so: `[ "$VERCEL_GIT_COMMIT_REF" != my_branch_name ]` but that script seems to always return 0.

Writing a one line bash script does seem to work though:
`if [ "$VERCEL_GIT_COMMIT_REF" != my_branch_name ]; then exit 1; else exit 0; fi`

**Comment by andymckay** [comment]
I was able to get it work using `$VERCEL_ENV` but also using your explicit exit values. For example:

```
[11:11:48.060] Cloning completed: 309.793ms
[11:11:48.060] Running "if [ "$VERCEL_ENV" != "production" ]; then exit 1; else exit 0; fi"
[11:11:48.064] The Deployment has been canceled as a result of running the command defined in the "Ignored Build Step" setting.
```

I noted that there's no `"` around `production` in that example, so I've updated the documentation to look like the above ☝🏾 

Thank you 🙇🏾
