### ISSUE TITLE
Old update-notifier dependency creates dependabot security alert

### ISSUE THREAD

**Issue by osdiab** [zeit/now#8877]
I'm getting a dependabot security alert from the `got` library, which isn't directly depended upon by the `vercel` package; but it does get included via a chain that comes back to it based on inspecting my `yarn.lock`:

`got@npm:^9.6.0` -> `"latest-version@npm:^5.1.0":` -> `"update-notifier@npm:5.1.0"` -> `"vercel@npm:^28.4.17"`

To exorcise this demon i would be happy if this package updated its version of `update-notifier`. Thanks!

<img width="946" alt="Screen Shot 2022-11-09 at 13 39 02" src="https://user-images.githubusercontent.com/1890926/200740082-42331018-ea3b-4078-9d87-f31a3b5c6360.png">

**Comment by EndangeredMassa** [comment]
We will replace it. See this comment for details: https://github.com/vercel/vercel/pull/8878#issuecomment-1308317726

See this PR for status:
https://github.com/vercel/vercel/pull/8090

**Comment by osdiab** [comment]
When might this be released?

**Comment by EndangeredMassa** [comment]
@osdiab we are working on a blocker to this right now. We hope to release this change in the next few weeks.
