### ISSUE TITLE
Vercel "Domain" Docs: Found a typo in english sentence to be fixed 

### ISSUE THREAD

**Issue by snazzybytes** [zeit/now#8899]
Found a small typo/grammatical error in the sentence while reading your DOMAIN related docs here: https://vercel.com/docs/concepts/projects/domains

![image](https://user-images.githubusercontent.com/72365181/201553440-cbff16fe-65c8-4799-ae11-733e5d8f97ed.png)

Incorrect way (you should remove the **"is"** at the end of the sentence):
- Understanding how DNS works is important to ensure that you are configuring your `domain is correctly`.

Correct way:
- Understanding how DNS works is important to ensure that you are configuring your `domain correctly.`

**Comment by EndangeredMassa** [comment]
Thanks! I submitted the change internally. It will be updated soon.

**Comment by snazzybytes** [comment]
my pleasure 🙇 i see it live  for future readers 🚀 

<img width="671" alt="image" src="https://user-images.githubusercontent.com/72365181/204072784-57ef1962-9c15-47e0-abba-67e9d075436c.png">

**Comment by snazzybytes** [comment]
maybe if you could open source the docs as well for next time? i could have just PRed it. it probably would have made the devs life easier on Vercel's end 🤔
