### ISSUE TITLE
Deploys are passing even if "npm install" fails

### ISSUE THREAD

**Issue by jgtvares** [zeit/now#8901]
### Discussed in https://github.com/vercel/vercel/discussions/8900

<div type='discussions-op-text'>

<sup>Originally posted by **jgtvares** November 14, 2022</sup>
# Problem
I've been having this problem a lot.
When dependencies installation fails the build continues and the project is successfully deployed.
Then my app crashes with a lot of `MODULE_NOT_FOUND` errors.
This was not happening before (2 or 3 months ago).

# More details
To get more into details, the error I often get with `npm install` is a **401 Unable to authenticate**.
That happens because my project uses a couple of private libraries that I developed. 
In order to install them successfully, I'm using the `NPM_RC` environment variable to set npm token for authentication in my private repository.
This token expires after a while and I need to update the variable from time to time, that's why `npm install` fails sometimes.
Before, deploys used to fail because of this, then I knew I had to update the npm token.
But now, for some reason, this error gets bypassed and my project crashes and that's a huge problem!

Is anyone also going through this?

<img width="724" alt="image" src="https://user-images.githubusercontent.com/47645535/201676038-2c919358-c399-4916-9ac9-a7896250dd99.png">
</div>

**Comment by swarnava** [comment]
Will be fixed with #8909

**Comment by swarnava** [comment]
We will add it to next Vercel CLI release.

**Comment by jgtvares** [comment]
Just passing by to confirm that builds are now failing as they should!
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/47645535/203117097-11be41ab-c4ae-4ea6-b5f4-27e6fc2729f3.png">

Thank you guys!

**Comment by swarnava** [comment]
This looks like a separate error, can you file a ticket: vercel.com/help
