### ISSUE TITLE
Are you in the `cs50`/`me50` GitHub orgs by chance? There's a known issue on GitHub's side due to the size of these. If you leave those, it should work.

### ISSUE THREAD

**Issue by I-Johnson** [zeit/now#8943]
Are you in the `cs50`/`me50` GitHub orgs by chance? There's a known issue on GitHub's side due to the size of these. If you leave those, it should work.

_Originally posted by @leerob in https://github.com/vercel/vercel/discussions/5351#discussioncomment-4131660_

**Comment by I-Johnson** [comment]
Hey, I tried coming out of the organization(Every organization I'm in). But it's not working.

**Comment by andymckay** [comment]
Have you contacted GitHub Support about this? They are probably the best people to help https://support.github.com/

**Comment by swarnava** [comment]
Closing this issue. This is an issue on GitHub side not us.

**Comment by MrOrz** [comment]
You git checkout anytime you like
But you can never leave 🎶
