### ISSUE TITLE
Allow client routing with vercel dev

### ISSUE THREAD

**Issue by user72356** [zeit/now#8995]
I'm using React Router in an SPA built with Vite, deployed to Vercel.

In development everything works well, but it breaks when deployed on Vercel (405 errors). After some research I found that I had to create a `vercel.json` file that includes the following rewrites:

```
{
    "rewrites": [
        { "source": "/((?!api/.*).*)", "destination": "/" }
    ]
}
```

This redirects all requests to the index page at /, except for requests to the api/ folder. Then React Router can take it from there.

Unfortunately, with this configuration the app is now broken in development using `vercel dev`. I need `vercel dev` as opposed to just using `vite` because I'm using serverless functions that only `vercel dev` can run.

I'm not sure what to do? Can I only apply these rewrites rules to production and not development?

**Comment by andymckay** [comment]
Thanks for filing this issue. I'm slightly confused why you'd want different rules for production and development in this case, wouldn't you want them to be same. However at this time the `rewrites` rule cannot be conditional upon the environment.

Although rewrites can't be applied per domain, you could possibly do this in middleware which can then do any logic you'd like. Here's an example doing this in Next (I know you are using React Router) but this should prove helpful:

https://vercel.com/docs/concepts/functions/edge-middleware/quickstart#add-middleware-code

**Comment by user72356** [comment]
> Thanks for filing this issue. I'm slightly confused why you'd want different rules for production and development in this case, wouldn't you want them to be same. However at this time the `rewrites` rule cannot be conditional upon the environment.
> 
> Although rewrites can't be applied per domain, you could possibly do this in middleware which can then do any logic you'd like. Here's an example doing this in Next (I know you are using React Router) but this should prove helpful:
> 
> https://vercel.com/docs/concepts/functions/edge-middleware/quickstart#add-middleware-code

Please reopen this issue, it's not me wanting to use different rules in prod vs dev, but Vercel is broken when using react router. So the hack is to use the `vercel.json` as shown above. But this same `vercel.json` hack that fixes prod, breaks dev. So I guess the real fix is to fix Vercel so it lets me use React router out of the box.

**Comment by Panimaster** [comment]
@user72356 this worked for me on production and locally with vercel dev:

`{
  "rewrites": [
    {
      "source": "/:path",
      "destination": "/"
    }
  ]
}
`
