### ISSUE TITLE
Figure a way to enable providers to return something to us (aka `now.js`)

### ISSUE THREAD

**Issue by matheuss** [zeit/now#9]
We could, for example, let providers use `return 1` to indicate that the they want `process.exit(1)`.

Would be nice here: https://github.com/zeit/now/commit/a1dd06290a784311b05f3e486d609b832a1444de#diff-cec70a08c11a260d44b518126d174623R119

**Comment by leo** [comment]
This issue was moved to zeit/now-cli#773
