### ISSUE TITLE
Vercel REST API endpoint to retrieve environment variables always returns encrypted values.

### ISSUE THREAD

**Issue by aarondill** [zeit/now#9072]
# Vercel REST API endpoint to retrieve environment variables always returns encrypted values.

## Description of Issue:
The Vercel REST API endpoint at `https://api.vercel.com/v9/projects/:idOrName/env` returns encrypted values, regardless of whether or not the query string `?decrypt=true` is present.
[The documentation](https://vercel.com/docs/rest-api#endpoints/projects/retrieve-the-environment-variables-of-a-project-by-id-or-name) says that the query parameter "decrypt" is 
```
string - optional
If true, the environment variable value will be decrypted
```

## Expected behavior:
Including the query parameter in a valid request would yield env values whose `decrypted` values are `true`, and whose values are readable

## Actual behavior
Setting up a project with an ENV variable called `testing` and a value of `Hello World` and sending a request to either `/v9/projects/:idOrName/env?decrypt=true`  or `/v9/projects/:idOrName/env` with an Authentication heading of `Bearer <code goes here>` returns a response like the following:
```JSON
{ "envs":[
{ "type": "encrypted", "value": "GdJV2AeNZkvkbxcSV6cGsG/tG6QOVvR+1235OUqvo0c=",
"target": ["production", "preview", "development"], "configurationId": null,
"id": "G43g2zxrf9Ldc5TW", "key": "testing",
"createdAt": 1670456695838, "updatedAt": 1670456695838,
"createdBy": "<potentially-secret?-me-value-here!>", "updatedBy": null,
"decrypted": false },

{"<...More of the same encrypted values>":"here"}

]}
```
With or without the decrypt query parameter, the api returns the exact same response body, with decrypted = false, and the value encrypted. In both cases, it returns a `200` status,  not a 400 or 403 errors like you might expect if something went wrong:
```
Code | Description
200 | The list of environment variables for the given project
400 | One of the provided values in the request query is invalid.
403 | You do not have permission to access this resource.
```
## Environment:
I have tested this in Node.js using the node-fetch module, native JS using the fetch function, as well as cURL on Linux Bash and all returned the same values.

## Steps to reproduce:
1. Create a vercel project through any means.
2. Add an environment variable
3. Obtain your testing key [here](https://vercel.com/account/tokens)
4. Fetch with the following code:

- *JavaScript*: Navigate to `https://api.vercel.com/v9/projects/` (to avoid CORS) and run the following in the browser console:
```js
const appId = "<PUT_APP_ID_HERE>"
const authentication = "<PUT_AUTH_TOKEN_HERE>"
fetch(`https://api.vercel.com/v9/projects/${appId}/env?decrypt=true`, {
headers: {
Authorization: `Bearer ${authentication}`
}
}).then((r)=>(console.log(r),r)).then(r=>r.json()).then(j=>{console.log(j.envs);console.log("First:", j.envs[0])})
```
- *cURL*: open a terminal and run:
```bash
appId="<APP_ID_HERE>"
authen="<AUTHENTICATION_TOKEN_HERE>"
curl -X GET "https://api.vercel.com/v9/projects/$appId/env?decrypt=true" \
       -H "Authorization: Bearer $authen"
echo #Make a new line
```
5. Enjoy your thoroughly encrypted and useless data!

## Workaround:
You can fetch the variable IDs with `/v9/projects/:appId/env` and later fetch **each value** with `v9/projects/:appId/env/:varId`, however, this introduces significant delay, due to the necessity of multiple fetches and redundant downloading when one should've been sufficient.

## **Important Additional Notes**:
- The antiquated endpoints of `/v8/projects/:appId/env` and `/v7/projects/:appId/env` are both functional.
- v9 validates the contents of the query, returning an error if it is not `"true"|"false"`, however, the value of it does not affect a successful return.

**Comment by andymckay** [comment]
Thanks for filing a detailed issue. Sorry about this but, the V9 endpoint deprecated this feature and started returning the following Header: `x-vercel-warning-project-envs-decrypt-deprecated: The decrypt query parameter is deprecated. Please use the /v1/projects/:projectId/env/:envId endpoint to retrieve the value of an environment variable.`

I did some tests and confirmed that this endpoint above does indeed work as expected. 

Unfortunately at some point the docs didn't get updated with this, so they are incorrect. I'll follow up with the documentation team about fixing up those docs.

**Comment by malixswoop** [comment]
😢 
For those getting here from (mis)reading the documentation, another workaround is to use the CLI:
```bash
npx vercel env pull --yes --environment=production --scope=${{ secrets.VERCEL_TEAM_ID }} --token=${{ secrets.VERCEL_TOKEN }}
```
