### ISSUE TITLE
The wrong link was posted in the nextjs v13 blog post

### ISSUE THREAD

**Issue by destroyer22719** [zeit/now#9126]
https://nextjs.org/blog/next-13#streaming

The link "learn more about streaming" gives a link to a page about data fetching (the one after streaming) when instead it should've went to this page https://beta.nextjs.org/docs/data-fetching/streaming-and-suspense

**Comment by trek** [comment]
Hi @destroyer22719,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
