### ISSUE TITLE
Python ASGI functions crashing on incoming headers

### ISSUE THREAD

**Issue by rclement** [zeit/now#9132]
## Issue

When deploying a Python ASGI application (e.g. using FastAPI, Sanic) with Vercel Serverless, the function is built successfully but invoking the URL the function leads to a crash with a 500 error.

Here is the backend log from Vercel:
```
[ERROR] AttributeError: 'list' object has no attribute 'encode'
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 288, in vc_handler
      'headers': [[k.lower().encode(), v.encode()] for k, v in headers.items()],
  File "/var/task/vc__handler__python.py", line 288, in <listcomp>
      'headers': [[k.lower().encode(), v.encode()] for k, v in headers.items()],
```

## Investigations

It seems there is an issue with incoming complex headers parsing for ASGI functions:

- Python WSGI applications (e.g. using Flask) do not show this error
- Invocations of ASGI functions using `curl` or `httpie` works perfectly, no errors
- Bisecting headers from the web browser (Firefox, Chrome), here is a faulty header causing the crash:
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
```
- Invocations of ASGI functions using `curl` or `httpie` using the above header are triggering the error

## Reproduction

A simple hello world app with FastAPI or Sanic in a module name `app.py`:

```python
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def index():
    return {"message": "Hello World"}
```

```python
from sanic import Sanic
from sanic.response import json

app = Sanic(name=__name__)

@app.route("/")
async def index(request):
    return json({"message": "Hello World"})
```

`vercel.json`:
```
{
  "builds": [
    {
      "src": "app.py",
      "use": "@vercel/python"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "app.py"
    }
  ]
}
```

## Related issues

- https://github.com/vercel/vercel/issues/2526

**Comment by andymckay** [comment]
Thanks @rclement, I've confirmed and can reproduce.

**Comment by mayureshagashe2105** [comment]
@andymckay any update on the issue? Thank you!

I was able to replicate it, please find the [gist ](https://gist.github.com/mayureshagashe2105/15a74af242f5d3c9f9feb77ff99077d5)here.

**Comment by HemanthSai7** [comment]
Even I faced this issue today.

**Comment by jerguslejko** [comment]
experiencing the same issue

**Comment by chris48s** [comment]
Has this fix been deployed yet? I'm still seeing this exception on one of my apps. I'm just trying to work out if this will fix it, but it hasn't been deployed yet (which is fine - sometimes things get merged and then take a while to hit production) or if this has been deployed but the specific variation I am seeing is another bug requiring a different fix

**Comment by nlarusstone** [comment]
I'm still seeing this in the Vercel CLI `28.16.10`

**Comment by rclement** [comment]
Sorry to dig-up this thread but the issue does not seem to be fixed universally.

For instance when using the `sentry-sdk` ASGI integration, it is failing to read a list of value for a given header key:
```python
[GET] /

[ERROR] AttributeError: 'list' object has no attribute 'decode'
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 305, in vc_handler
    response = asgi_cycle(__vc_module.app, body)
  File "/var/task/vc__handler__python.py", line 208, in __call__
    loop.run_until_complete(asgi_task)
  File "/var/lang/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/var/task/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/var/task/sentry_sdk/integrations/starlette.py", line 333, in _sentry_patched_asgi_app
    return await middleware(scope, receive, send)
  File "/var/task/sentry_sdk/integrations/asgi.py", line 139, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
  File "/var/task/sentry_sdk/integrations/asgi.py", line 166, in _run_app
    self._get_headers(scope),
  File "/var/task/sentry_sdk/integrations/asgi.py", line 317, in _get_headers
    value = raw_value.decode("latin-1")
```

The [ASGI specification](https://asgi.readthedocs.io/en/latest/specs/www.html#http-connection-scope) mentions:
- The exact expected type of the `headers` parameter of the connection scope: `Iterable[[byte, byte]]`
- "Duplicates are possible and must be preserved in the message as received"

The patch in #9205 is now sending either a string or a list of string as header value (`Iterable[[byte, byte | [byte]]]`) to cope with duplicated headers but this does not seem aligned with the ASGI spec.

## Proposed solution

When duplicated headers are present, flatten the values as multiple entries.

For instance, when sending:
```bash
curl https://..../ -H "foo: bar" -H "foo: bar"
```

Vercel receives:
```python
headers = [{"foo": ["bar", "bar"]}]
```

Vercel should send:
```python
asgi_headers = [["foo", "bar"], ["foo", "bar"]]
```
