### ISSUE TITLE
My project can't read or open this file!

### ISSUE THREAD

**Issue by callme-MJ** [zeit/now#9137]
My project can't read or open this file!
```shell
2020-08-19T15:12:44.093Z	undefined	ERROR	Error: ENOENT: no such file or directory, open './_db/geolite2_country.mmdb'
    at Object.openSync (fs.js:458:3)
    at verifyOptions (/var/task/index.js:52887:17)
    at module.exports.module.exports (/var/task/index.js:52877:2)
    at Object.<anonymous> (/var/task/index.js:3280:12)
    at __webpack_require__ (/var/task/index.js:24:31)
    at startup (/var/task/index.js:43:19)
    at /var/task/index.js:49:18
    at Object.<anonymous> (/var/task/index.js:52:10)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './_db/geolite2_country.mmdb'
}
RequestId: 18664c01-70b0-44c6-9911-655454d915a4 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

_Originally posted by @Kadantte in https://github.com/vercel/vercel/discussions/5066_

**Comment by callme-MJ** [comment]
I'm facing the same issue as vercel doesn't read an excel file in public folder. The log in vercel shows it as 


> [POST] /api/hello
> 19:36:06:04
> 2022-12-27T14:06:07.711Z	1936e4ef-66ca-4785-9a10-c2da4e960745	ERROR	Error: ENOENT: no such file or directory, open 'public/result.xlsx'
>     at Object.openSync (node:fs:600:3)
>     at Object.readFileSync (node:fs:468:35)
>     at read_binary (/var/task/node_modules/xlsx/xlsx.js:3153:44)
>     at readSync (/var/task/node_modules/xlsx/xlsx.js:23698:69)
>     at Object.readFileSync (/var/task/node_modules/xlsx/xlsx.js:23738:9)
>     at handler (/var/task/.next/server/pages/api/hello.js:30:40)
>     at Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:363:15)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:487:9)
>     at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:749:37) {
>   errno: -2,
>   syscall: 'open',
>   code: 'ENOENT',
>   path: 'public/result.xlsx'
> }
> 2022-12-27T14:06:07.712Z	1936e4ef-66ca-4785-9a10-c2da4e960745	ERROR	Error: ENOENT: no such file or directory, open 'public/result.xlsx'
>     at Object.openSync (node:fs:600:3)
>     at Object.readFileSync (node:fs:468:35)
>     at read_binary (/var/task/node_modules/xlsx/xlsx.js:3153:44)
>     at readSync (/var/task/node_modules/xlsx/xlsx.js:23698:69)
>     at Object.readFileSync (/var/task/node_modules/xlsx/xlsx.js:23738:9)
>     at handler (/var/task/.next/server/pages/api/hello.js:30:40)
>     at Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:363:15)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:487:9)
>     at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:749:37) {
>   errno: -2,
>   syscall: 'open',
>   code: 'ENOENT',
>   path: 'public/result.xlsx'
> }
> RequestId: 1936e4ef-66ca-4785-9a10-c2da4e960745 Error: Runtime exited with error: exit status 1
> Runtime.ExitError
> 

```
import XLSX from 'xlsx';
import { readFileSync } from 'fs';
import path from 'path';
// import exelfile from "../../public/result.xlsx"

export default async function handler(req:any,res:any) {
  const creds = {
    code: req.body.code,
    regNo:req.body.regNo,
  }
  const file = path.join(process.cwd(), 'public', 'result.xlsx');
  const wb = XLSX.readFile(file);
  const ws = wb.Sheets[req.body.code];
  const data= XLSX.utils.sheet_to_json(ws,{defval:"",raw:false,header:"A"});
  if (ws) {
  
    const title = ws.A2.v;
    const sbj = ws.J2.v;
    const cs = ws.J1.v;
    const headers = data[2];
    const row1 = data[0];
    const row2 = data[1];
    
    
    const details =  data.filter( (item:any)=>  item.D
    === creds.regNo);
    
    res.send({title,details,headers,sbj,cs,row1,row2});
  }
  else{
    res.send("No code")
  }
 
}

```

**Comment by amityweb** [comment]
I have exact same problem with geolite2_country.mmdb. Did you find a solution please?

**Comment by amityweb** [comment]
Ah fixed it...

Change folder name in path (in my case utils) to path.join(process.cwd(), 'utils/')+

`const lookup = await maxmind.open<CountryResponse>('utils/GeoLite2-Country.mmdb');`

With

`const lookup = await maxmind.open<CountryResponse>(path.join(process.cwd(), 'utils/')+'GeoLite2-Country.mmdb');`

**Comment by callme-MJ** [comment]
thank you man... love it
