### ISSUE TITLE
SSG pages and API routes generating exessive amount of serverless functions with Next.js

### ISSUE THREAD

**Issue by njakob** [zeit/now#9180]
# Overview

When adding a [single API route handler](https://github.com/njakob/vercel-serverless-issue/blob/6862183aa52fe4500d29805304da79e0c282f7b3/pages/api/hello.ts) to a collection of static pages produced by SSG  (`getStaticPaths` + `getStaticProps`) through Next.js, Vercel is currently generating excessive serverless functions.

It is important to note the following:
- The code is compiled by the latest version of Next.js `13.1.1`
- The API route does not include anything related to other pages
- The API route is not even used by other pages
- Based on the legends below, static pages are always marked as SSG by Next.js

```
λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
```

I'm running into the scenario in another project where I generate ~50'000 static pages. There were no issues when deploying the generated output until I added API routes. From this point, Vercel has been trying to deploy more than 50'000 serverless functions.

# Expected results

When API routes are added, they should only generate a single extra serverless function without affecting SSG pages.

# Reproducible with

The issue can be reproduced with https://github.com/njakob/vercel-serverless-issue.

# Investigations

This is the output of a build on Vercel of this repository when an API route is present and the number of serverless functions is more than 2000.

[Source](https://github.com/njakob/vercel-serverless-issue)

```
Route (pages)                              Size     First Load JS
┌ ○ /                                      426 B          73.9 kB
├   /_app                                  0 B            73.5 kB
├ ○ /404                                   181 B          73.7 kB
├ λ /api/hello                             0 B            73.5 kB
└ ● /something/[key] (8316 ms)             296 B          73.8 kB
    ├ /something/0
    ├ /something/1
    ├ /something/2
    └ [+997 more paths]
+ First Load JS shared by all              73.5 kB
  ├ chunks/framework-114634acb84f8baa.js   45.4 kB
  ├ chunks/main-010ff0b6bbe5ac8f.js        27.1 kB
  ├ chunks/pages/_app-4b2041e059ed5a29.js  286 B
  └ chunks/webpack-8fa1640cc84ba8fe.js     750 B

Generated build outputs:
 - Static files: 16
 - Serverless Functions: 2003
 - Edge Functions: 0
```

However, when the [API route is removed](https://github.com/njakob/vercel-serverless-issue/commit/caddc00b7ab94e982edf8a538f9896368f9ce2a8), all the static pages are not being deployed as serverless functions.

[Source](https://github.com/njakob/vercel-serverless-issue/tree/without-api)

```
Route (pages)                              Size     First Load JS
┌ ○ /                                      426 B          73.9 kB
├   /_app                                  0 B            73.5 kB
├ ○ /404                                   181 B          73.7 kB
└ ● /something/[key] (6131 ms)             296 B          73.8 kB
    ├ /something/0
    ├ /something/1
    ├ /something/2
    └ [+997 more paths]
+ First Load JS shared by all              73.5 kB
  ├ chunks/framework-114634acb84f8baa.js   45.4 kB
  ├ chunks/main-010ff0b6bbe5ac8f.js        27.1 kB
  ├ chunks/pages/_app-4b2041e059ed5a29.js  286 B
  └ chunks/webpack-8fa1640cc84ba8fe.js     750 B

Generated build outputs:
 - Static files: 2016
 - Serverless Functions: 0
 - Edge Functions: 0
```

As an extra note, [adding pages that include SSR](https://github.com/njakob/vercel-serverless-issue/commit/0896c922678fabb6ac067b80a6b4c4d07013eb6c) (`getServerSideProps`) do not have the same impact and only generates the necessary serverless function.

[Source](https://github.com/njakob/vercel-serverless-issue/tree/without-api-with-ssr)

```
Route (pages)                              Size     First Load JS
┌ ○ /                                      426 B          73.9 kB
├   /_app                                  0 B            73.5 kB
├ ○ /404                                   181 B          73.7 kB
├ λ /search                                285 B          73.8 kB
└ ● /something/[key] (8484 ms)             296 B          73.8 kB
    ├ /something/0
    ├ /something/1
    ├ /something/2
    └ [+997 more paths]
+ First Load JS shared by all              73.5 kB
  ├ chunks/framework-114634acb84f8baa.js   45.4 kB
  ├ chunks/main-010ff0b6bbe5ac8f.js        27.1 kB
  ├ chunks/pages/_app-4b2041e059ed5a29.js  286 B
  └ chunks/webpack-8fa1640cc84ba8fe.js     750 B

Generated build outputs:
 - Static files: 2017
 - Serverless Functions: 1
 - Edge Functions: 0
```

Finally, adding a [second API handler](https://github.com/njakob/vercel-serverless-issue/commit/156cdcbe42061ea655e6078dbad0acd1e2f13a08) to the mix does not affect the number of serverless functions further.

[Source](https://github.com/njakob/vercel-serverless-issue/tree/with-2-api)

```
Route (pages)                              Size     First Load JS
┌ ○ /                                      426 B          73.9 kB
├   /_app                                  0 B            73.5 kB
├ ○ /404                                   181 B          73.7 kB
├ λ /api/hello                             0 B            73.5 kB
├ λ /api/hello-2                           0 B            73.5 kB
└ ● /something/[key] (6194 ms)             296 B          73.8 kB
    ├ /something/0
    ├ /something/1
    ├ /something/2
    └ [+997 more paths]
+ First Load JS shared by all              73.5 kB
  ├ chunks/framework-114634acb84f8baa.js   45.4 kB
  ├ chunks/main-010ff0b6bbe5ac8f.js        27.1 kB
  ├ chunks/pages/_app-4b2041e059ed5a29.js  286 B
  └ chunks/webpack-8fa1640cc84ba8fe.js     750 B

Generated build outputs:
 - Static files: 16
 - Serverless Functions: 2004
 - Edge Functions: 0
```

**Comment by ijjk** [comment]
Hi, this has recently been updated to show a separate group `Prerenders` which is different from serverless functions but was previously being conflated. 

`Prerenders` are a separate output type that are static but still allow leveraging features like preview mode and On-Demand ISR which are only able to be leveraged with API routes which is the reason you were seeing the difference with an API route present versus not present. 

Note also that serverless functions are automatically bundled in an optimized way on Vercel so typically only one or two actual functions are created. We are investigating providing this information in a more clear way as well.

**Comment by diegohaz** [comment]
@ijjk Is it possible to disable "preview mode and On-Demand ISR" altogether so those pages are static?
