### ISSUE TITLE
`stale-while-revalidate` on edge functions is never revalidated

### ISSUE THREAD

**Issue by remorses** [zeit/now#9189]
Reproduction: https://github.com/remorses/nextjs-edge-vercel-stale-while-revalidate-bug/tree/main

To reproduce
```sh
curl -i https://nextjs-edge-vercel-stale-while-revalidate-bug.vercel.app/api/hello
curl -i https://nextjs-edge-vercel-stale-while-revalidate-bug.vercel.app/api/hello
# age: 10
# x-vercel-cache: STALE
curl -i https://nextjs-edge-vercel-stale-while-revalidate-bug.vercel.app/api/hello
# age: 20
# x-vercel-cache: STALE
# ...
curl -ihttps://nextjs-edge-vercel-stale-while-revalidate-bug.vercel.app/api/hello
# age: 100
# x-vercel-cache: STALE
# it will always return stale cache without revalidating
```

Vercel will not revalidate the function cache and always return stale data

**Comment by smaeda-ks** [comment]
Hi @remorses, Could you confirm that if you set `stale-while-revalidate` directive with any value set (e.g., `stale-while-revalidate=10`) does that work? It looks like we're assigning a fallback value if there's no value. I'll confirm.

I believe `stale-while-revalidate` directive should have a value as per the spec:
https://www.rfc-editor.org/rfc/rfc5861#section-3

**Comment by remorses** [comment]
Most people use `stale-while-revalidate` without a value, this is because Vercel should revalidate the cache in max 10 seconds anyway. The default value for `stale-while-revalidate` should be something like "infinity": https://github.com/vercel/vercel/discussions/7882

The problem here is that the cache is never revalidated, you can see that because the `age` header always increases and never gets reset

**Comment by smaeda-ks** [comment]
> Most people use stale-while-revalidate without a value, this is because Vercel should revalidate the cache in max 10 seconds anyway. The default value for stale-while-revalidate should be something like "infinity": https://github.com/vercel/vercel/discussions/7882

I don't think that is semantically the correct implementation from sepc wise, but it's how we designed it at the time, so you see it with Vercel often.

I see the main problem here, as you mentioned. It seems it's indeed not working, and background fetch isn't invoked with edge functions. I'm checking this further. Thanks for raising this.

**Comment by remorses** [comment]
Let me know if I can help in any way

**Comment by hazae41** [comment]
I can confirm this issue also happens on regular (node, not edge) functions

**Comment by smaeda-ks** [comment]
@remorses We identified the bug and working on a fix. Will update here when we have an update to share. Thank you for your patience.

**Comment by smaeda-ks** [comment]
@hazae41 As far as I tested, this is only the case with Edge Functions. If it's reproducible with Serverless Functions, could you please share a minimal reproducible example repository?
https://vercel.com/guides/creating-a-minimal-reproducible-example

**Comment by hazae41** [comment]
@smaeda-ks 

It seems to only happen inside browser using fetch

Repository: https://github.com/hazae41/nextjs-vercel-stale-while-revalidate-bug/tree/main

- Open https://nextjs-vercel-stale-while-revalidate-bug.vercel.app/api/hello in your browser
- Then open dev tools and run the following twice (or more) within 5 seconds

```javascript
await fetch("https://nextjs-vercel-stale-while-revalidate-bug.vercel.app/api/hello")
```

- Then look at the Network tab, all responses have `X-Vercel-Cache: STALE` header

Maybe the browser request headers causes this issue?

**Comment by hazae41** [comment]
Sorry wrong link, edited

**Comment by smaeda-ks** [comment]
@hazae41 Thanks! I see what's going on there. This is a separate issue, but I'll check this one as well and get back to you.

**Comment by remorses** [comment]
This issue seems to be fixed

**Comment by smaeda-ks** [comment]
@hazae41 Your separate issue has also been fixed
