### ISSUE TITLE
`--git-branch` for `vc env pull` does not support branches with `/`

### ISSUE THREAD

**Issue by anthonyshew** [zeit/now#9237]
I'm trying to create a per-branch preview database configuration using PlanetScale and thought I'd use the CLI to to add, remove, and pull my per-branch variables. Here's an example of the set of environment variables I'm working with:
<img width="947" alt="image" src="https://user-images.githubusercontent.com/35677084/212597372-ec6b4c96-922e-4265-8ed5-f1c64605a191.png">

## Current/desired behavior matrix.

`vc env pull --environment=preview`
Current behavior: I get the `DATABASE_URL` for preview.
Desired behavior: I get the `DATABASE_URL` for preview.

`vc env pull --environment=preview --git-branch=testing`
Current behavior: I get the `DATABASE_URL` for the `testing` branch.
Desired behavior: I get the `DATABASE_URL` for the `testing` branch.

`vc env pull --environment=preview --git-branch=fix/test-schema-change`
Current behavior: I get the `DATABASE_URL` for the main Preview environment.
Desired behavior: I get the `DATABASE_URL` for the `fix/test-schema-change` branch.

`vc env pull --environment=preview --git-branch="some/deal"`
Current behavior: I do not get any `tester` variable.
Desired behavior: I would like to get a `tester` variable with a value of `valueeeee`.

You'll notice that I was hoping that some double quotes in the last example would help things along but had no luck! This leads me to my conclusion: It would appear the CLI doesn't allow `/`, although git does and git tooling elsewhere does.

## Additional info
It's possible that this behavior holds true for other commands, not just `vc env pull`. I have not investigated other commands.

**Comment by anthonyshew** [comment]
Looks like a found an error message when using `vc env add`! As mentioned in the original issue, I'd expect this command to accept `/`s for consistency with other tooling (including Vercel itself!).

<img width="991" alt="image" src="https://user-images.githubusercontent.com/35677084/212599029-5eac586e-12eb-46c3-8602-7bc1df93c3e5.png">

**Comment by cb1kenobi** [comment]
After some quick testing, I was unable to reproduce the `vc env add` issue with Vercel CLI 28.12.4. I need a bit more time to create a clean test case.

**Comment by cb1kenobi** [comment]
Quick note, it appears the `vc env add` error is coming from the server side, not the CLI. Initial quick look indicates the error happens validating the env variable. There doesn't appear to be any validation of the git branch as far as format is concerned, only that the branch exists.

**Comment by cb1kenobi** [comment]
I'm able to reproduce the `vc env pull` issue.

**Comment by anthonyshew** [comment]
@cb1kenobi Ah, that does indeed make sense. I definitely didn't have a branch called `a/test` on my project at that time. Was the error message misleading me there then?

Glad you could reproduce the `pull` one! Thought I was going crazy. 😀

**Comment by cb1kenobi** [comment]
I have a pull request up that resolves the `vc env pull` issue. I'll update this thread as soon as the fix has been deployed.

**Comment by cb1kenobi** [comment]
The fix has been deployed and branches with `/` are working as expected. Thank you for reporting the issue!
