### ISSUE TITLE
`vercel rm <project> --safe` is not working

### ISSUE THREAD

**Issue by chrismeyers** [zeit/now#9321]
The `vercel rm <project> --safe` command is not working as intended in the latest version of the CLI (currently v28.13.1).

### Steps to reproduce:

1. Create a few deployments
2. Run the command `vercel rm <project> --safe`
3. Receive the incorrect error:
    ```    
    > Could not find unaliased deployments or projects matching "<project>". Run `vercel ls` to list.
    ```

### Expected:

The command should print all deployments except for the current production deployment and prompt you to delete.  Example:
```
> Found N deployments for removal in <scope> [723ms]
> The following N deployments will be permanently removed:
  dpl_<id>      <url>     11h ago
  ...
> Are you sure? [y/N]
```

To confirm this expected behavior, I ran the command with a version of the CLI from several months ago (v28.4.8) and the command worked as expected.

### Additional Information

Here is the debug output from each CLI version when running these commands:

<details>
<summary>Working (v28.4.8)</summary>

```
> [debug] [2023-01-26T05:30:45.414Z] user supplied known subcommand: "rm"
> [debug] [2023-01-26T05:30:45.434Z] #1 → GET https://api.vercel.com/v2/user
> [debug] [2023-01-26T05:30:45.590Z] #1 ← 200 OK: sfo1::mxm5k-1674711045582-e0f2f1d06c51 [156ms]
> [debug] [2023-01-26T05:30:45.592Z] Spinner invoked (Fetching deployment(s) "<project>" in <user>) with a 300ms delay
> [debug] [2023-01-26T05:30:45.596Z] #2 → GET https://api.vercel.com/v5/now/deployments/<project>?
> [debug] [2023-01-26T05:30:45.598Z] #3 → GET https://api.vercel.com/v8/projects/<project>?
> [debug] [2023-01-26T05:30:45.747Z] #2 ← 404 Not Found: sfo1::rt842-1674711045747-041940a27823 [151ms]
> [debug] [2023-01-26T05:30:45.765Z] #3 ← 200 OK: sfo1::pjfmt-1674711045743-da54e38ad74e [167ms]
> [debug] [2023-01-26T05:30:45.771Z] #4 → GET https://api.vercel.com/v4/now/deployments?projectId=prj_<id>&limit=100
> [debug] [2023-01-26T05:30:45.935Z] #4 ← 200 OK: sfo1::25qb8-1674711045913-b68a0f7843e5 [163ms]
> [debug] [2023-01-26T05:30:45.943Z] #5 → GET https://api.vercel.com/now/deployments/dpl_<id>/aliases?
> [debug] [2023-01-26T05:30:45.947Z] #6 → GET https://api.vercel.com/now/deployments/dpl_<id>/aliases?
> [debug] [2023-01-26T05:30:45.950Z] #7 → GET https://api.vercel.com/now/deployments/dpl_<id>/aliases?
> [debug] [2023-01-26T05:30:46.172Z] #5 ← 200 OK: sfo1::5rpvc-1674711046085-392d8e79c6a5 [229ms]
> [debug] [2023-01-26T05:30:46.180Z] #7 ← 200 OK: sfo1::n8tp4-1674711046096-1290a6aa6f33 [230ms]
> [debug] [2023-01-26T05:30:46.183Z] #6 ← 200 OK: sfo1::qncbd-1674711046096-e79353408dfa [236ms]
```
</details>

<details>
<summary>Not working (v28.13.1 latest)</summary>

```
> [debug] [2023-01-26T05:30:20.722Z] user supplied known subcommand: "rm"
> [debug] [2023-01-26T05:30:20.744Z] #1 → GET https://api.vercel.com/v2/user
> [debug] [2023-01-26T05:30:21.032Z] #1 ← 200 OK: sfo1::8xsng-1674711021021-f4a5ccad3cbc [288ms]
> [debug] [2023-01-26T05:30:21.035Z] Spinner invoked (Fetching deployment(s) "<project>" in <user>) with a 300ms delay
> [debug] [2023-01-26T05:30:21.041Z] #2 → GET https://api.vercel.com/v13/deployments/<project>
> [debug] [2023-01-26T05:30:21.045Z] #3 → GET https://api.vercel.com/v8/projects/<project>
> [debug] [2023-01-26T05:30:21.214Z] #2 ← 404 Not Found: sfo1::pcrkt-1674711021205-b85db600fed1 [173ms]
> [debug] [2023-01-26T05:30:21.228Z] #3 ← 200 OK: sfo1::b54z9-1674711021205-8b4f8c3faed3 [183ms]
> [debug] [2023-01-26T05:30:21.235Z] #4 → GET https://api.vercel.com/v4/now/deployments?projectId=prj_<id>&limit=100
> [debug] [2023-01-26T05:30:21.423Z] #4 ← 200 OK: sfo1::b54z9-1674711021376-b4b5efb94e4c [187ms]
> [debug] [2023-01-26T05:30:21.431Z] #5 → GET https://api.vercel.com/v3/now/aliases?limit=20
> [debug] [2023-01-26T05:30:21.435Z] #6 → GET https://api.vercel.com/v3/now/aliases?limit=20
> [debug] [2023-01-26T05:30:21.437Z] #7 → GET https://api.vercel.com/v3/now/aliases?limit=20
> [debug] [2023-01-26T05:30:21.642Z] #7 ← 200 OK: sfo1::dhsr6-1674711021588-a5ed20901dbd [205ms]
> [debug] [2023-01-26T05:30:21.661Z] #5 ← 200 OK: sfo1::h58kr-1674711021578-57a823bcb98c [230ms]
> [debug] [2023-01-26T05:30:21.668Z] #6 ← 200 OK: sfo1::kslfr-1674711021593-a41f58517c08 [233ms]
```
</details>

**Comment by jablonski** [comment]
Same problem here with 28.15.1. Worked with earlier versions as mentioned above without problems.

**Comment by aarubui** [comment]
Same problem here. I've been keeping my CLI on v28.11.0, which was the latest working version.
Suspected change that broke the feature: [cli] Rollback team check (https://github.com/vercel/vercel/pull/9120) [@cb1kenobi]

**Comment by cb1kenobi** [comment]
A while back, you could perform actions on projects/deployments that belonged to a scope that was different than the current scope in the CLI. You need to use `vercel switch` to change team/scope to the one that the resource belongs to, then you can inspect, delete, rollback, etc.

**Comment by jablonski** [comment]
Just tried with latest version (28.16.2) and linked a project, re-switched to my organisation and tried to remove obsolete deployments via

`vercel rm -s projectname`

and it gave exact the same error:

_Could not find unaliased deployments or projects matching "projectname". Run `vercel ls` to list_

`vercel ls`

works fine and show all deployments. So something is broken in the current versions.

**Comment by aarubui** [comment]
@cb1kenobi The changes in #9476 will fix the command for use with `<project>` but will break it when used with `<deploymentId>`. Can you make the necessary changes and the PR instead?

Summary of the issue:
* `getDeploymentsByProjectId` (`packages/cli/src/util/deploy/get-deployments-by-project-id.ts`) calls `/v4/now/deployments` and returns data with `uid` and `created` properties.
* `getDeployment` (`packages/cli/src/util/get-deployment.ts`) calls `/v13/deployments` and returns data with `id` and `createdAt` properties.
* `packages/cli/src/commands/remove.ts` handles data from both as if they're both in the `getDeployment` format.

**Comment by cb1kenobi** [comment]
I've confirmed the bug and I've submitted a PR https://github.com/vercel/vercel/pull/9477 to fix it.

Regarding `vercel list`, I've created an internal issue to discuss the behavior with the CLI team.
