### ISSUE TITLE
Using private github repository as npm dependency without committing secrets

### ISSUE THREAD

**Issue by Banou26** [zeit/now#9338]
Reading from https://vercel.com/guides/using-private-dependencies-with-vercel it seems like committing the link containing auth credentials is the only way to use a private github repository as an NPM dependency.

We should have a way to use a private github repository as a dependency without committing these informations.

NPM allows you to `npm i` github repo URLs and they are set under the format: `"myPackageName": "github:myOrg/myPackage",`
AFAIK vercel does not support this kind of dependency at all if they're private repos.

This, i assume is the recommended way to include github repositories as NPM dependency, no leaked credentials, and environment dependent, as each users with an authentified git setup can locally run `npm i` and it'd work.
So it'd be great if vercel natively supported this.

I tried passing things like `GITHUB_TOKEN` and other similar names as environment variables with my PAT but it always end up erroring with
```
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/myOrg/myRepo.git
npm ERR! command-line line 0: unsupported option "accept-new".
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

Using a git submodule with a local `file:` package dependency as a workaround right now.

**Comment by trek** [comment]
Hi @Banou26,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
