### ISSUE TITLE
[Docs] Yarn 2 Nomenclature

### ISSUE THREAD

**Issue by coopbri** [zeit/now#9380]
The [Vercel Yarn 2 support docs](https://vercel.com/guides/does-vercel-support-yarn-2) currently describe Yarn Berry/Yarn Modern as "Yarn 2", however the current major is at v3 with v4 on the horizon. I think it would be more scalable for the docs to refer to the current version of Yarn as its development code name, "Yarn Berry", or something similar such as "Yarn Modern". Alternatively, the docs could say "Yarn 2+" if it is desirable to keep the v2 notion.

Yarn as it is still commonly referred to has been rebranded to "Yarn Classic" or "Yarn 1" and is now officially deprecated software aside from hotfixes/patches, so I think it is worth facilitating that knowledge (the Vercel docs do refer to the legacy version of Yarn as "Yarn 1", I think that could stay untouched).

**Comment by trek** [comment]
Thanks @coopbri. This appears to be fixed in the docs now.
