### ISSUE TITLE
[gatsby-plugin-vercel-builder] Gatsby builds are not being cached increasing build time

### ISSUE THREAD

**Issue by tsamantanis** [zeit/now#9452]
I think this change has increased the build times of one of my medium sized projects (couple hundred pages). After this change was released, the build times more than doubled from around 4 minutes to 9+. The major problem is that the site utilizes a source plugin and there are tasks such as `Running gatsby.IMAGE_CDN jobs` and `gatsby-plugin-sharp.IMAGE_PROCESSING` which are very time consuming and need to run again. 

Is it possible to specify the version of `@vercel/gatsby-plugin-vercel-builder` used for the build? I'd like to somehow test using `v1.0.3`. I tried adding the package in `package.json` but then it runs twice and throws an error.

See [this commit](https://github.com/vercel/vercel/commit/aa6b957b23101cff6c265bd4baa1c06a3fd1f1bd)

**Comment by Ethan-Arrowood** [comment]
Hi @tsamantanis I'm not sure which change you are referring to. The cache related PR you link to only touches our CI

**Comment by TooTallNate** [comment]
Hi @tsamantanis, I did a test and the Gatsby `.cache` directory and `node_modules` were properly cached on subsequent builds. Can you share a deployment URL where you are seeing the issue? Thanks!

**Comment by tsamantanis** [comment]
Hello @TooTallNate. I looked further into the issue and the problem is that Gatsby cannot find the `public` directory, since it is moved into `.vercel/output/static` after the build. Gatsby displays this message during the build

```
info We've detected that the Gatsby cache is incomplete (the .cache directory exists
but the public directory does not). As a precaution, we're deleting your site's
cache to ensure there's no stale data.
```
When testing subsequent builds without the `@vercel/gatsby-plugin-vercel-builder` package, the cache is initialized correctly. 

By looking at Gatsby's repo it is clear that they [explicitly look for a `public` directory upon build](https://github.com/gatsbyjs/gatsby/blob/000e23e0f1247af61b8ecdc2f7274e53e89e82bf/packages/gatsby/src/services/initialize.ts)

It seems like the `public` folder must somehow remain in order for Gatsby to find it during the build process. I looked at [this commit](https://github.com/vercel/vercel/commit/aa6b957b23101cff6c265bd4baa1c06a3fd1f1bd) and I understand that the copying the folder over does not work for every project. However I tested the following in `gatsby-plugin-vercel-builder/src/helpers/static.ts` and it worked as expected.

```
import { join, dirname } from 'path';
import { copy, ensureDir } from 'fs-extra';

export async function createStaticDir(prefix?: string) {
  const publicDir = join(process.cwd(), 'public');
  const targetDir = join(
    process.cwd(),
    '.vercel',
    'output',
    'static',
    prefix ?? ''
  );
  await ensureDir(dirname(targetDir));
  await copy(publicDir, targetDir);
}
```

Perhaps the proper way to go about this is to calculate the disk space needed and only move the directory if the limit will be exceeded. 


P.S Sorry @Ethan-Arrowood you are correct I did reference the wrong commit there.

**Comment by tsamantanis** [comment]
Update: Setting VERCEL_GATSBY_BUILDER_PLUGIN = 0 stops the plugin from being injected and fixed the issue.
