### ISSUE TITLE
NextJS serverless function timing out in Vercel but works fine locally

### ISSUE THREAD

**Issue by ShimantaBhuyan** [zeit/now#9460]
### Discussed in https://github.com/vercel/vercel/discussions/9459

<div type='discussions-op-text'>

<sup>Originally posted by **ShimantaBhuyan** February 16, 2023</sup>
So I have created a NextJS project and created an api handler. This handler fetches data from an external api endpoint using axios and then I do some processing to produce a certain value.
Then, using `google-spreadsheet` library I push this value along with a timestamp to my google sheet.
When I run the project locally and hit my api endpoint, it works perfectly and returns the result almost immediately.
![apiSnap](https://user-images.githubusercontent.com/32566682/219276015-60ee6b77-1cb7-4ea8-bad1-fc5e1a56c75d.png)

Also note that none of the console logs are shown in the real-time function logs, I just get a timeout error after 10 seconds.

Things I've tried debugging, with some help from @Nutlope :
- Checked if environment variables are present and correct, in Vercel
- Redeployed couple times (can't help, ingrained in me as a programmer :P)
- There was a bodyparser config earlier in my code which I've removed and checked as well.
- Tried out different fetch libraries (inbuilt http/https, node-fetch and now axios)

Here's the code for the api handler, would appreciate any help

```
import { NextApiRequest, NextApiResponse } from "next";
const { GoogleSpreadsheet } = require("google-spreadsheet");
const axios = require("axios");

const API_ENDPOINT = "https://www.nseindia.com/api/option-chain-indices?symbol=NIFTY";

const doc = new GoogleSpreadsheet(process.env.GOOGLE_SHEET_ID ?? "");

const saveToSheets = async (pcr: number) => {
  console.log("INSIDE SAVE TO SHEETS...");
  try {
    await doc.useServiceAccountAuth({
      client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL ?? "",
      private_key: (process.env.GOOGLE_PRIVATE_KEY ?? "").replace(/\\n/g, "\n"),
    });

    await doc.getInfo();
    const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
    console.log({ sheet });

    const headers = ["timestamp", "pcr"];
    const reqbody = {
      [headers[0]]: getDateTime(new Date(Date.now())),
      [headers[1]]: pcr,
    };

    const addSheetResult = await sheet.addRow(reqbody);
    console.log({ addSheetResult });
  } catch (error) {
    console.log({ error });
  }
};

const getDateTime = (dateTime: any) => {
  let day = dateTime.getDate();
  let month = dateTime.getMonth() + 1;
  let year = dateTime.getFullYear();
  let hours = dateTime.getHours();
  let minutes = dateTime.getMinutes();
  let seconds = dateTime.getSeconds();

  if (day < 10) {
    day = "0" + day;
  }

  if (month < 10) {
    month = "0" + month;
  }

  if (hours < 10) {
    hours = "0" + hours;
  }

  if (minutes < 10) {
    minutes = "0" + minutes;
  }

  if (seconds < 10) {
    seconds = "0" + seconds;
  }

  const formattedDate = month + "/" + day + "/" + year + " " + hours + ":" + minutes + ":" + seconds;

  return formattedDate;
};

const fetchOptionsData = (OPTIONS_DATA: any) => {
  const UNDERLYING_VALUE = OPTIONS_DATA.records.underlyingValue;
  const SPOT_PRICE = Math.round(UNDERLYING_VALUE / 50) * 50;

  const MOMENT_DATA =
    OPTIONS_DATA.filtered.data[OPTIONS_DATA.filtered.data.findIndex((data: any) => data.strikePrice === SPOT_PRICE)];

  const LOWER_STRIKE_PRICE = SPOT_PRICE - 500,
    UPPER_STRIKE_PRICE = SPOT_PRICE + 500;

  const OPTION_CHAIN_DATA = OPTIONS_DATA.filtered.data.filter(
    (data: any) => data.strikePrice >= LOWER_STRIKE_PRICE && data.strikePrice <= UPPER_STRIKE_PRICE,
  );

  const CALLS_CHNG_IN_OI = OPTION_CHAIN_DATA.map((data: any) => {
    return data.CE.changeinOpenInterest;
  });
  const SUM_CALLS_CHNG_IN_OI = CALLS_CHNG_IN_OI.reduce((total: number, num: number) => total + num, 0);

  const PUTS_CHNG_IN_OI = OPTION_CHAIN_DATA.map((data: any) => {
    return data.PE.changeinOpenInterest;
  });
  const SUM_PUTS_CHNG_IN_OI = PUTS_CHNG_IN_OI.reduce((total: number, num: number) => total + num, 0);

  const PCR = SUM_PUTS_CHNG_IN_OI / SUM_CALLS_CHNG_IN_OI;

  console.log({
    MOMENT_DATA,
    CALLS_CHNG_IN_OI,
    PUTS_CHNG_IN_OI,
    SUM_CALLS_CHNG_IN_OI,
    SUM_PUTS_CHNG_IN_OI,
    PCR,
  });

  saveToSheets(PCR);
};

async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method === "GET") {
    axios
      .get(API_ENDPOINT)
      .then((response: any) => {
        console.log(response.data);
        const OPTIONS_DATA = response.data;
        fetchOptionsData(OPTIONS_DATA);
        res.status(200).json({
          success: true,
          message: "Data pulled successfully",
        });
      })
      .catch((error: any) => {
        console.error(error);
        res.status(500).json({ statusCode: 500, message: error.message });
      });
  } else {
    res.setHeader("Allow", "GET");
    res.status(405).end("Method Not Allowed");
  }
}

export default handler;

```

</div>

**Comment by jopfre** [comment]
I am also having the same issue. My getServerSideProps function times out but it can't really be any simpler.

```
export const getServerSideProps = async (ctx) => {
  const { report, client } = ctx.query;
  return { props: { report, client } };
};
```
Works fine on local as well.

Surely this can't take 10seconds?

**Comment by Fasa2509** [comment]
Same here, my app was working fine two weeks ago and now any api call takes more than 10 seconds and use a lot of memory, it just returns an error of timing out in production, but it's working as expected in development.

**Comment by drumst0ck** [comment]
Same here, 0 change, my app works fine 10 days ago but now all my serverless function timing out in vercel, I have paied pro membership but dont work

**Comment by Fasa2509** [comment]
> Same here, 0 change, my app works fine 10 days ago but now all my serverless function timing out in vercel, I have paied pro membership but dont work

Are you using Material UI on your project? If that is the case you should check how are you importing all the icons of your project, you should import them by default. If you're not using Material UI check out the bundle size of your app.

**Comment by blechatellier** [comment]
Same issue here, they changed the default max duration from 60s down to 15s for PRO users without prior notice.

**Comment by trek** [comment]
Hi @ShimantaBhuyan,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
