### ISSUE TITLE
Vercel build and install options unable to setup monorepo

### ISSUE THREAD

**Issue by WINOFFRG** [zeit/now#9507]
Hello! 

I have a `docs` folder in this https://github.com/WINOFFRG/limeplay/tree/b8a3dfc72a006072d60f211d496a130c49f76d9e repo which is a nextjs website. Now, The case is that to generate the static content for docs a script needs to be run in root directory. 
https://github.com/WINOFFRG/limeplay/blob/b8a3dfc72a006072d60f211d496a130c49f76d9e/scripts/docgen.ts 

So, what I did was to specify the `docs` directory as root directory in vercel build options and allowed to include source files outside the root. Overwritten the installation command to `pnpm install && pnpm run docs:build` Which should first install the dependencies in `docs` directory and then generate the static content for documentation site. "docs:build" will `"pnpm install && pnpm run docs:docgen && pnpm run build"` do this where `pnpm run build` should run the final command in root directory to build the nextjs site. 

I am not sure if there is any issue with pnpm setup, or imporperly managed (as it looks to me) but I tried almost each and every possible combination I could think of to get this up and running. Unfortunately 100+ commits didn't worked for me. The task is pretty simple to just run a script in root directory before build of `docs` so that static content is generated.

Have to say this, but Vercel being so popular has just got poor support. I am facing this issue from past 1 month created so many tickets in Discord server, tried to initiate conversation with people in `#general`, created ticket in github discussion but no luck. I would then consider this issue as something uncommon. 

Maybe there are some great tools out there which I am missing which could help me manage this pnpm workspace properly. Please do let me know. Also, It's humble request if anyone can help with this issue as it has been over a month I am creating tickets and waiting for response.

**Comment by EndangeredMassa** [comment]
@WINOFFRG sorry for the delay on responding to your issue.

If you are still experiencing this problem, I'd be happy to dig into it.
