### ISSUE TITLE
Error: File /vercel/path0/api/index.js does not exist

### ISSUE THREAD

**Issue by harshgour** [zeit/now#9524]
**Vercel deployment for remix is not working after the latest update.**

No build errors but throwing error while deployment - `Error: File /vercel/path0/api/index.js does not exist.`
Tried deploying a new branch or redeployed already built branch, failed with the above error. This happened after today's latest update.

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/60436404/220876457-934e92d1-a0f9-4725-a6f1-a13eae023cd8.png">

**Comment by harshgour** [comment]
@TooTallNate need your help here, I see that there were few support updates went live for remix.js today. Not able to deploy remix builds on vercel now after the latest vercel update.

**Comment by Sotatek-DaiNguyen4** [comment]
face similar issues today, please someone help to check

**Comment by Sotatek-DaiNguyen4** [comment]
attach some images related to this issue
<img width="706" alt="Screenshot 2023-02-23 at 6 11 44 PM" src="https://user-images.githubusercontent.com/102936574/220890659-75c99636-cc3a-40bd-b74c-50f6af5d8ecd.png">

**Comment by andreuBiset** [comment]
Same issue with a remix project. We have tried to redeploy an already successful build, and it fails with the same error.

**Comment by robipop22** [comment]
A temporary solution is to set Vercel CLI to a lower version.
Set this to your env variables inside your Vercel Project:

VERCEL_CLI_VERSION=vercel@28.16.4

**Comment by andreuBiset** [comment]
> A temporary solution is to set Vercel CLI to a lower version. Set this to your env variables inside your Vercel Project:
> 
> VERCEL_CLI_VERSION=vercel@28.16.4

Works, thank you!

**Comment by TooTallNate** [comment]
Does anyone have an open source repo that is reproducing this issue?

**Comment by cmnord** [comment]
@TooTallNate https://github.com/cmnord/jep my open source repo is experiencing this issue! thank you for looking into it

**Comment by TooTallNate** [comment]
Ok I see the problem now. PR coming to fix it soon. If you want an immediate fix, then remove `serverBuildTarget` from `remix.config.js` - it's no longer necessary (but the PR I'm creating will make it still work for backwards compat).

**Comment by cmnord** [comment]
Removing `serverBuildTarget: "vercel"` from my `remix.config.js` fixed it for me, thank you!
