### ISSUE TITLE
Slow TTFB

### ISSUE THREAD

**Issue by sdoigmm** [zeit/now#9661]
### Discussed in https://github.com/vercel/vercel/discussions/9570

<div type='discussions-op-text'>

<sup>Originally posted by **sdoigmm** February 28, 2023</sup>
Our site has a TTFB of 1.1s when measured by Google Pagespeed.
https://pagespeed.web.dev/report?url=https%3A%2F%2Fmandoemedia.com%2F

This seems like a slow response.

I am new to NextJS & Sanity.io, so will have to look into increasing NextJS website performance, but thought TTFB was not related to NextJS, more the Vercel server.</div>

**Comment by sdoigmm** [comment]
Still a TTFB of 0.9s on desktop, and 1.6s on mobile, which is slow.

**Comment by trek** [comment]
Hi @sdoigmm,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
