### ISSUE TITLE
vercel --local-config not working

### ISSUE THREAD

**Issue by overshom** [zeit/now#9670]
### Discussed in https://github.com/vercel/vercel/discussions/9648

<div type='discussions-op-text'>

<sup>Originally posted by **overshom** March 10, 2023</sup>
I use vercel cli to build app locally and then `vercel deploy --prebuilt` .
`Vercel CLI 28.16.15` - the latest version - still not working. Before this version tried `28.16.12` no luck as well.

For that I want to use command like `vercel --local-config vercel-dev.json build` as per documentation https://vercel.com/docs/cli/global-options#local-config

But it does not work 🐛 
json file ignored 🤷‍♂️ 

I tried other names for json file like `vercel -A vercel/dev/vercel.json build` but still no success at all.

I need to use different buildCommand for different branch deployment
So, my `vercel.json` file looks like that:
```
{
  "buildCommand": "yarn build:dev"
}
```

What am I doing wrong? Why vercel cli cannot pick up specified config file?

P.S. it is not only about different env, but in general about `json` config with all the other options including buildCommand.</div>

**Comment by mutaharIU** [comment]
Firstly, it's important to make sure that the vercel-dev.json file is located in the root directory of your project. If it's not in the root directory, the Vercel CLI won't be able to find it.

Next, make sure that you're running the vercel command from the same directory where the vercel-dev.json file is located. If you run the command from a different directory, the Vercel CLI won't be able to find the configuration file.

You can also try specifying the path to the vercel-dev.json file explicitly using the --local-config flag, like this:

Copy this code in (Bash)

vercel --local-config=./vercel-dev.json build

If none of these solutions work, you can try creating a .vercelignore file in the root directory of your project and add vercel-dev.json to the list of ignored files. This will ensure that the configuration file is not ignored by the Vercel CLI.

I hope this helps you.

**Comment by mutaharIU** [comment]
You are correct that TTFB (Time to First Byte) is a measure of the time it takes for the server to respond to the initial request from the client, before any content is downloaded. It can be influenced by various factors including server response time, network latency, and server load.

In the case of Vercel, it's possible that the TTFB could be affected by the server response time or server load, but there are also other factors that could contribute to slow TTFB times.

Here are some suggestions to help improve your TTFB:

Optimize images: Large images can significantly increase the TTFB time. Make sure to compress images and reduce their file size.

Use caching: Utilize server-side caching to store frequently accessed data to avoid repeating queries that can slow down TTFB.

Use a CDN: A content delivery network (CDN) can help improve TTFB by serving static assets from a network of servers that are geographically closer to the user.

Minimize HTTP requests: Reduce the number of HTTP requests by combining CSS and JavaScript files, reducing the number of images, and avoiding unnecessary plugins.

Optimize server configuration: Make sure that the server is properly configured to handle requests and optimize the use of available resources.

I hope these suggestions help you improve your TTFB. Good luck!

**Comment by overshom** [comment]
@mutaharIU I guess you replied in a wrong thread.
I have no issues with TTFB https://github.com/vercel/vercel/issues/9670#issuecomment-1468063777

**Comment by cb1kenobi** [comment]
This issue has been fixed and shipped in Vercel CLI 28.17.0. Run `npm install -g vercel` to upgrade!
