### ISSUE TITLE
BUG: Vercel is somehow overwriting `fetch` from `undici` with a non-spec compliant implementation

### ISSUE THREAD

**Issue by TillaTheHun0** [zeit/now#9690]
## Background

We have multiple applications that use `undici`, as it implements `fetch`, `Request` and other Web Standards.

Our usages of `undici` `fetch` looks like this:

```js
fetch(new Request('https://jsonplaceholder.typicode.com/todos/1'))
```

> Passing a `Request` to `fetch` is valid according to the [the spec](https://fetch.spec.whatwg.org/#fetch-method) and `undici` implements the spec.

## Problem

Recently, some of our application lambdas deployed on Vercel started throwing errors like:
```js
{
input: "[object Request]",
code: "ERR_INVALID_URL"
}
```

Doing some digging, we tracked it down to our `fetch` calls. It seems like Vercel or NextJS or _something_ is **overwriting the `unidici` spec-compliant `fetch` for an implementation that does NOT fully implement `fetch`**

 **This error only happens when the app is deployed on Vercel. This does not happen locally**. This also only seems to happen for some applications, but not others, which makes me think some environment variable up on Vercel lambdas is causing this error on some applications and not others, but I have nothing to confirm this.

## Reproduce

I was able to reproduce this with NextJS 12 and NextJS 13 on Node v16 and Node v18.

Here is a repo that reproduces the issue: https://github.com/TillaTheHun0/vercel-undici-repro. It has two lambdas with identical behavior, except one passes `Request` to `fetch` and one passes a `string` to `fetch`. It is a request to the same url on both though. `unidici` is being imported in the file, so not sure how this bug could even occur without something overwriting `undici`

Steps to reproduce:

1. deploy that repo to `vercel`
2. hit `/api/request` and observe the error shown above
3. hit `/api/string` and observe a successful response

## Other Notes

While I was debugging this, I found some code in NextJS that references a [Next compiled version of `undici`](https://github.com/vercel/next.js/blob/e601a3b53292278e1b7d1ef1f692ed340ef8be10/packages/next/src/server/node-polyfill-fetch.ts#L6) as part of a `fetch` polyfill? I couldn't tell you if that's related or not.

**Comment by TillaTheHun0** [comment]
I outlined some of my debugging around this here: https://github.com/hyper63/hyper/issues/566#issuecomment-1476335850

Hopefully that's helpful, and please correct me if I am misunderstanding Vercel/NextJS behavior W.R.T `undici` or `fetch` polyfill

**Comment by kaloyanBozhkov** [comment]
I am experiencing the same issue! On Vercel, my network requests are defaulting to using undici and I am getting this error because of that:
```
TRPCClientError: fetch failed
    at TRPCClientError.from (file:///var/task/node_modules/@trpc/client/dist/transformResult-6fb67924.mjs:13:16)
    at file:///var/task/node_modules/@trpc/client/dist/links/httpBatchLink.mjs:211:64 {
  meta: undefined,
  shape: undefined,
  data: undefined,
  [cause]: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:14062:11) {
    cause: RequestContentLengthMismatchError: Request body length does not match content-length header
        at AsyncWriter.end (node:internal/deps/undici/undici:9704:19)
        at writeIterable (node:internal/deps/undici/undici:9614:16) {
      code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
    }
  }
}
```

which I tried replicating locally by using the same node v. as on Vercel, but could not. It is only happening on Vercel. 

The issue with undici might link to this issue:
https://github.com/nodejs/undici/issues/2046

**Comment by luixo** [comment]
I got a similar bug with a clear reproduction so I decided I'll comment here.
So what's happening is that body length doesn't match `Content-Length` header that is generated somewhere on the way to sending request, but it only happens on Vercel.

How to reproduce:
1. Go to `/api/hello` [endpoint](https://vercel-content-length-bug.vercel.app/api/hello) and verify it returns headers / body of the request.
2. Go to `/api/fetch-local-api` [endpoint](https://vercel-content-length-bug.vercel.app/api/fetch-local-api) and verify that instead of proxying data from `/api/hello` it fails to run.
3. Read the [code](https://github.com/luixo/vercel-content-length-bug/tree/main/src/pages/api).

**Comment by ivan-gerov** [comment]
ran into this as well, could we prioritize this please :/

**Comment by MCangelov** [comment]
Absolutely the same issue as previously mentioned, using Vercel causes errors that do not appear locally.

**Comment by kyle-ssg** [comment]
Wow, that was unexpected. Can confirm that at least api side importing explicitly from node-fetch works for now. I'd imagine isomorphic-unfetch will work too.

```
import fetch from 'node-fetch'
```

**Comment by julioxavierr** [comment]
I don't use `undici` directly, but I'm encountering the same issue. It appears when I'm running Node 18.x or the latest version of Next.js, which seems to make `undici` the default.

**Comment by nevolgograd** [comment]
@kyle-ssg seems like `node-fetch` solves the problem, but caching is lost, right? 

Btw, downgrading node version to 16 didn't help. Is there anything we can do besides waiting?

**Comment by swapnil233** [comment]
Any updates on this? I had this bit of code in my API handler, which just makes two fetch() requests. It was also failing with `RequestContentLengthMismatchError: Request body length does not match content-length header`, ONLY on Vercel deployments - worked fine on local.

```typeScript
...
const baseUrl = process.env.VERCEL_URL ? 'https://' + process.env.VERCEL_URL : 'http://localhost:3003'

const response = await fetch(`${baseUrl}/api/aws/getSignedUrl?key=${key}`);
const responseJson = await response.json();
const signedUrl = responseJson.url;

const deepgramResponse = await fetch(`${baseUrl}/api/deepgram/`, {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json'
    },
    body: JSON.stringify({ uri: signedUrl })
});

const deepgramJson = await deepgramResponse.json();
const transcription = deepgramJson;
...
```

@kyle-ssg's workaround of explicitly importing and using node-fetch's fetch does seem to fix the issue, but this is very weird. I recently switched my calls from using Axios to Fetch, so if anyone wonders, using Axios will also fix the issue.

**Comment by 0xc00010ff** [comment]
Ran into this issue cloning the Supabase template https://vercel.com/templates/next.js/supabase. Reproducible on the login page which calls the form actions.

**Comment by TooTallNate** [comment]
The original [repro](https://github.com/TillaTheHun0/vercel-undici-repro) seems to work fine for me now. This was probably fixed at some point after creating this issue.

For future reference, this issue tracker is specifically for the Vercel CLI, not for the platform itself. You would have gotten more traction on this issue by posting to the [Discussions board](https://github.com/orgs/vercel/discussions) and/or emailing support directly (support@vercel.com).

**Comment by kmvan** [comment]
> The original [repro](https://github.com/TillaTheHun0/vercel-undici-repro) seems to work fine for me now. This was probably fixed at some point after creating this issue.
> 
> For future reference, this issue tracker is specifically for the Vercel CLI, not for the platform itself. You would have gotten more traction on this issue by posting to the [Discussions board](https://github.com/orgs/vercel/discussions) and/or emailing support directly ([support@vercel.com](mailto:support@vercel.com)).

iOS/MacOS safari will set `content-type: 0` to request(DELETE method). And cause server error.
