### ISSUE TITLE
Vercel.App domain name is contaminated in mainland China

### ISSUE THREAD

**Issue by Tiger-Coder-C** [zeit/now#9693]
Hello, on August 27 last year, Vercel.App domain name was polluted in mainland China, please urge you to solve it.

**Comment by trek** [comment]
Hi @Tiger1228cym,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
