### ISSUE TITLE
Vercel.APP is blocked by China

### ISSUE THREAD

**Issue by lucasjinreal** [zeit/now#9714]
Please help China developers!

**Comment by lucasjinreal** [comment]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/21303438/227717564-848fec13-3124-485a-a0c1-8cb3c98fe7d1.png">

**Comment by evannotfound** [comment]
You can use VPN

**Comment by lucasjinreal** [comment]
@EvanNotFound the website I setup is not for me to use? I hope you can understand.....

**Comment by evannotfound** [comment]
> @EvanNotFound the website I setup is not for me to use? I hope you can understand.....

You can also use your own domain. Vercel's target is not only china, so I doubt they would do anything about it.

**Comment by lucasjinreal** [comment]
@EvanNotFound  Yes, but a backup domain could help us a lot.

**Comment by trungthecelestial** [comment]
This also affects Viet Nam.

**Comment by lucasjinreal** [comment]
@trungthecelestial why does Vieetnam effected? It also have GFW?

**Comment by trungthecelestial** [comment]
Not sure but same things happened to all Vercel related domains in Vietnam.

**Comment by Giresharu** [comment]
并不是被ban了，只是dns污染了域名。解决方案是自己申请一个域名，然后随便配置一个二级域名 **CNAME** 给 `cname-china.vercel-dns.com.` 然后在 vercel 项目设置的 **domain** 里去添加这个二级域名再编辑把 **redirect** 设为 no
等你域名那边过多时间刷新了，再试试就发现可以了

确实要花点域名钱，不过如果本来就有域名需求的话就正好了

Vercel.APP hasn't been banned, it's just that the domain has been affected by DNS pollution. The solution is to apply for a new domain, then randomly configure a subdomain as a **CNAME** pointing to `cname-china.vercel-dns.com.` Then, in the **domain** settings of the Vercel project, add this subdomain and edit the **redirect** to 'no.' Once your domain refreshes after some time, you can try again and you will find it works.

Indeed, it may cost some money to obtain a new domain, but if you already have a domain requirement, it works out perfectly.

**Comment by NoFearInMyHeart** [comment]
@Giresharu 我二级域名配置了，结果跳反诈app下载页了，还有别的解决方法么，大佬儿?

**Comment by huayemao** [comment]
现在 ip 也被墙了，有什么替代方案吗

**Comment by trek** [comment]
Hi @lucasjinreal 

We have a community article on this topic: https://vercel.community/t/resolving-ip-blocking-issues/171
