### ISSUE TITLE
Next.js `[...slug]` is not correctly parsed when using `edge` runtime

### ISSUE THREAD

**Issue by remorses** [zeit/now#9723]
On a page `[...slug]`, the slug param will be ['x/x'] instead of ['x', 'x'] when visiting the `x/x` path

[Reproduction](https://github.com/remorses/vercel-next-bug-dynamic-param)

1. deploy on vercel
2. open deployed site on a path with 2 parts (like x/x) (https://vercel-next-bug-dynamic-param-fy6g23d6i-xmorse.vercel.app/x/x as an example)
3. the slug param will be ['x/x'] instead of ['x', 'x']

**Comment by trek** [comment]
Hi @remorses,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js).
