### ISSUE TITLE
How do I change the output directory in vercel.json

### ISSUE THREAD

**Issue by Byron2016** [zeit/now#9818]
### Discussed in https://github.com/vercel/vercel/discussions/5081

<div type='discussions-op-text'>

<sup>Originally posted by **jakobrosenberg** August 23, 2020</sup>
I need to use the build option in vercel.json, but I can't find anything about changing the output directory in the documentation.

It can be changed in the GUI, so I expect it can also be changed in the config file.</div>

@jakobrosenberg  @paulogdm

I have problems deploying my API ( nodejs + typescript )  application  [temporary github code example](https://github.com/Byron2016/025_borrar)  

**my vercel.json file is:**

`
{
  "builds": [
    {
      "src": "package.json",
      "use": "@vercel/static-build",
      "config": { "distDir": "dist" }
    },
    {
      "src": "dist/index.js",
      "use": "@vercel/node",
      "config": {
        "includeFiles": ["dist/**"]
      }
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "dist/index.js"
    }
  ]
}
`

**my package.json file is:**

`
"scripts": {
    "start": "npm run build && node dist/index.js",
    "build": "rimraf dist && tsc",
    "ts.check": "tsc --project tsconfig.json",
    "dev": "set debug=* && ts-node-dev --respawn --transpile-only ./src/index.ts"
  },
`

![image](https://user-images.githubusercontent.com/15000602/232235752-27f2d154-7d13-4a47-99cf-7d740969ac75.png)

![image](https://user-images.githubusercontent.com/15000602/232235774-2b136520-3b6d-492b-b011-8fd2e20ba19a.png)

**Comment by trek** [comment]
Hi @Byron2016,

Unsure if you mean https://vercel.com/docs/projects/project-configuration#outputdirectory or not. But we use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
