### ISSUE TITLE
Next.js usesSrcDirectory function does not behave like the documentation

### ISSUE THREAD

**Issue by msjonker** [zeit/now#9873]
[src Directory documentation](https://nextjs.org/docs/advanced-features/src-directory) states: "src/pages will be ignored if pages is present in the root directory." However, the usesSrcDirectory function doesn't check for the existence of pages in the root directory. I have both a pages and src/pages in my project, which caused warnings like the following during deploy: "WARNING: Unable to find source file for page api/zip_code.js with extensions: js, jsx, ts, tsx, this can cause functions config from `vercel.json` to not be applied"

Only after renaming my "src" directory to something else did this warning go away and the function settings from vercel.json to be applied.

https://github.com/vercel/vercel/blob/cc140d6e2852ade7934e9fe6db2b3437ddfad3a4/packages/next/src/utils.ts#L1218

**Comment by trek** [comment]
Hi @msjonker,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
