### ISSUE TITLE
Deploying Express/Node backend

### ISSUE THREAD

**Issue by st3fus** [zeit/now#9946]
### Summary

So I'm trying to deploy a Express/Node backend for my frontend that's also hosted on Vercel. Frontend works fine but it's not communicating properly with the backend, my guess is that Backend isn't getting deployed properly. I have no idea what to do more to make it work, any insight could be helpful! Thanks

### Additional information

This is the current error I'm getting on backend once I go to the deployment:
```
This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: cdg1::bhr54-1683888166238-ab87b2fe09a5
```

This is the vercel.json i'm currently using:
```
{
	"version": 2,
	"public": true,
	"builds": [
		{
			"src": "src/server.js",
			"use": "@vercel/node"
		}
	],
	"rewrites": [
		{
			"source": "/(.*)",
			"destination": "/src/server.js"
		}
	],
	"headers": [
		{
			"source": "/api/(.*)",
			"headers": [
				{ "key": "Access-Control-Allow-Credentials", "value": "true" },
				{ "key": "Access-Control-Allow-Origin", "value": "*" },
				{ "key": "Access-Control-Allow-Methods", "value": "GET,OPTIONS,PATCH,DELETE,POST,PUT" },
				{
					"key": "Access-Control-Allow-Headers",
					"value": "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version"
				}
			]
		}
	]
}
```

### Example

https://eko-servis-ns-admin.vercel.app/

**Comment by akash1520** [comment]
This has happened to me more than once and all the time it had something to do with src and destination. Read the documentation again and check if you're mentioning their values correctly according to your file structure.

**Comment by trek** [comment]
Hi @st3fus,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
