### ISSUE TITLE
Websocket connection on Vercel deployment

### ISSUE THREAD

**Issue by SpruceVedant** [zeit/now#9957]
I am encountering an issue with my deployed application on Vercel, where the frontend is served but the websockets are not able to establish a connection. Is this because vercel does have a serverless way of building ?

**Comment by karim-moon** [comment]
Exactly.
I had same issue.
There are two way to make realtime datatransfer pipeline.

1. Make another websocket server, which is not serverless method like EC2 instance or something.
2. You should find something else, with that you can exchange offer, answer, ICE candidates in real-time.
    I currently use firestore of firebase and using snapshot to subscribe update of DB. 
    But, I think Vercel has own database service, which act like real time database. (not sure)
    
In case of 2, You need something to catch one of client disconnected like authorization system.

I've been struggling same issue.
Good luck to solve your issue 
Thanks.

**Comment by SpruceVedant** [comment]
Glad to know I am not the only one struggling with this issue. At first, I thought I may be doing something wrong.
I will definitely give a try to one of the two ways. It's helpful to know that creating another WebSocket server is a viable option for achieving real-time communication on ICE candidates between different peers.

Thank you for sharing your insights and suggestions, I appreciate it

**Comment by trek** [comment]
Hi @SpruceVedant,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
