### ISSUE TITLE
Next.js 13 - File-based Metadata - opengraph-image wrong URL

### ISSUE THREAD

**Issue by ciruz** [zeit/now#9968]
I created a small example repo with the latest next.js 13 canary ( https://github.com/ciruz/next-og ).
Where I defined an opengraph-image with the File-based Metadata option, and deployed this project to Vercel.

Now when you check out the project ( https://next-og-lyart.vercel.app/ ) and inspect the source, you will see that there must be some kind of misconfiguration in the background coming from Vercel itself, since the `og:image` has a different URL then the project itself, it has the deployment URL as `og:image` URL.

```html
<meta property="og:image" content="https://next-bof7pedda-ciruz.vercel.app/opengraph-image.jpg?3672c8818f51ad56"/>
```

You would assume it has the correct URL from the project, like so:
```html
<meta property="og:image" content=" https://next-og-lyart.vercel.app/... "/>
```

I never set any URL or metadataBase URL in my next.js project.

Related issue on next.js: https://github.com/vercel/next.js/issues/49859

**Comment by icetee** [comment]
This problem also exists with Kubernetes clusters. The domain cannot be set, localhost:port is listed in a production environment.

**Comment by RusseII** [comment]
SAME ISSUE

**Comment by ephemeral-ai** [comment]
Seeing the same issue. This breaks og-image because often the preview url (`https://next-bof7pedda-ciruz.vercel.app`) is behind an authentication wall, which means crawlers cannot see the image at all.

I tried setting `metadataBase` in `layout.tsx` and `page.ts`, but these were ignored.

**Comment by ciruz** [comment]
@ephemeral-ai are you on Next 13 or 14? The issue itself is closed in the next.js repo https://github.com/vercel/next.js/issues/49859?

**Comment by ephemeral-ai** [comment]
@ciruz I am on Next 14. vercel/next.js#49859 lists several issues, and some of them were addressed. 
However, I believe the problem framed in this current issue has not been addressed.

**Comment by Lukas1h** [comment]
Currently experiencing the same issue on NextJS 14.0.4

**Comment by gmonte** [comment]
The same for Next 14.1.0

**Comment by clevertree** [comment]
Same for 13.x.
I found a fix which is working for me. Just make it an absolute url, and vercel doesn't rewrite it. Annoying, but can be managed with env variables
```
openGraph: {
    images: `${process.env.NEXT_PUBLIC_URL}/path/to/file.jpg`,
}
```
until they fix their product. good luck!

**Comment by chuckcg** [comment]
This is still an issue...

**Comment by voidstar0** [comment]
This is somehow still an issue.

**Comment by Starvingg** [comment]
I can't believe I'm not alone.
You guys are having this issue too???

**Comment by Starvingg** [comment]
Typing the following into my layout file worked

layout.jsx

```
export const metadata = {
  metadataBase: new URL('https://acme.com'),
}
```

layout.tsx

```
// /app/layout.tsx
import type { Metadata } from 'next'

export const metadata: Metadata = {
  metadataBase: new URL('https://acme.com'),
}
```


```
Note:
For the .jsx file I didn't import anything. I only exported the metadata
```

https://stackoverflow.com/questions/77834556/ogimage-on-next-14-site-hosted-on-vercel-needs-an-auth-to-display

**Comment by clevertree** [comment]
@Starvingg absolute urls work. relative urls use their internal routing, which breaks.

**Comment by Starvingg** [comment]
This is working for me, I haven't specified a URL.
(Granted, I'm applying this open graph image across the website)

Try the facebook sharing debugger, it gives you a response of what their web-scraper sees 
@clevertree 

<img width="826" alt="image" src="https://github.com/vercel/vercel/assets/19302804/495b858a-76be-40dd-9f80-2244b1d83099">

**Comment by trek** [comment]
Hi @ciruz 

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
