### ISSUE TITLE
`npm install --global vercel@latest` crashes and doesn't install

### ISSUE THREAD

**Issue by raphaelbadia** [zeit/now#9992]
My CI started crashing 30 minutes ago with the error:

```
npm install --global vercel@latest
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vercel/gatsby-plugin-vercel-builder@1.3.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

I reproduce this locally on node 18 : 

<img width="661" alt="CleanShot 2023-05-19 at 19 05 16@2x" src="https://github.com/vercel/vercel/assets/1901628/e5d63a08-0f1a-4256-b92a-81c570ebe782">

**Comment by ryandunnewold** [comment]
Running into same issues on CI

**Comment by galtalmor** [comment]
It seems the latest version of `@vercel/gatsby-plugin-vercel-builder@1.3.4` was not published (or the dependency was mistakenly upgraded) prior to the release of `vercel@29.3.5`.

**Comment by galtalmor** [comment]
A workaround would be to keep using the previous Vercel CLI version `npm i -g vercel@29.3.4` until this gets fixed.

**Comment by raphaelbadia** [comment]
fixed now, thanks
