### ISSUE TITLE
npm install vercel@latest fails

### ISSUE THREAD

**Issue by defunctzombie** [zeit/now#9993]
The latest CLI version of vercel fails to install.

```
npm install --global vercel@latest
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vercel/gatsby-plugin-vercel-builder@1.3.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Indeed there is no v1.3.4 for `@vercel/gatsby-plugin-vercel-builder`

**Comment by ryandunnewold** [comment]
Duplicate of #9992

**Comment by defunctzombie** [comment]
Both filed at the same time :D I'll close this one since the other one has more chatter on it.

**Comment by ryandunnewold** [comment]
Clearly we're pretty dependent on Vercel because I was about to file an issue too 😅
